### ISSUE TITLE
Losing the 65534th character

### ISSUE THREAD

**Issue by Remspop** [theophilusx/ssh2-sftp-client#107]
Hello,

I'm trying to get a csv file on a SFTP server but when i'm comparing it to the file downloaded with my ftp client manually, it seems that every 65534th character is losed...
The file is encoded in UTF8, i have tried every possibilities with that but always the same at the end.

I can't figure out if it's the writing stream or the data transfert that cause this issue.

Thanks!

**Comment by theophilusx** [comment]
This sounds like a similar issue I ran into when using the library with node v10.x. It was not a problem with node 8.x. Looking into it, the problem seemed to be with the underlying ssh2 library. I did log an issue, but have not revisited the problem for a while.

**Comment by smulder** [comment]
I had a very abrupt concatenation of csv data on upload that is not in the original file. This happens unpredictably from what I can tell. The data changes at character 262144 and has caused major pricing problems for us on upload.

**Comment by theophilusx** [comment]
@smulder It would really help if you also provided some specific details e.g. version of node, version of this package, which methods were being used to transfer the files, what platforms and OS etc. In order to fix, it is first necessary to reproduce the issue and without being able to narrow down versions, platforms etc, that is nearly impossible.

I suspect that if there is an issue, it is a problem with the underlying ssh2 module as this module is largely just a wrapper around the functionality in that module. See for example https://github.com/mscdex/ssh2/issues/739

It would be useful to know which methods were being used when data is lost or concatenated. For example, the fastPut and fastGet methods do multiple streams and I can imagine this could result in data corruption if the streams are not re-assembled in the right order. However, the slower get/put methods only use a single stream, so such problems are less likely. 

Note that the issues I previously encountered where data transfer for larger files would hang or truncate the data when using node 10.x seems to have been resolved. I have been testing with much larger files this week (i.e. 6Mb+) without any issues using node 10.x. We have been using this module for 12 months to download large data sets and apart from the previously mentioned node 10.x issue, have not encountered any data corruption issues.

**Comment by smulder** [comment]
I am having data "Rearranging" for both the put and fastPut methods. I will work to get more information right away

**Comment by smulder** [comment]
I am using Node Version 9.11.1
latest version of this package 2.4.3
OSX 10.12.3
I am uploading to the eBay MIP FTP server: mip.ebay.com

I have verified that uploading the identical file via forklift FTP works fine and the integrity is still there

I would be happy to send a file directly to you, but would rather not post it publicly.

What other information would you be interested in?

**Comment by smulder** [comment]
If it helps anyone, I am optimistically reserved that using fastPut with the options setting as {concurrency:1} the mangled / rearranged file data is not there... I will monitor and post back if it resurfaces. Is this something that helps resolve things on your end?

Thanks, Scott

**Comment by theophilusx** [comment]
@smulder Yes, that information is useful. The initial aim is to try and reproduce this issue - for all we know, it may be some incompatibility with the remote server you are using, so being able to narrow down things is important. If I can find the time, I might see if I can reproduce the issue and if I can, then see if it can be reproduced just with ssh2 and eliminate ssh2-sftp-client. This is going to take some time though.

**Comment by smulder** [comment]
Let me know what I can do to help!

**Comment by wmagda** [comment]
I'm seeing the same issue currently - it's only happening with a specific server (I have no access to that servers configuration) I've downloaded the same file from different server using exact same code/client and the file downloads correctly.

**Comment by theophilusx** [comment]
I do suspect it is a server specific issue. From issues logged against ssh2 and ssh2-streams, it seems that some servers fail to honour the chunk size and/or highWaterMark requests AND ssh2 does not adjust to whatever size the server does use.  As a result, you end up with a mismatch between what the server understands the packet sizes are and what the client thinks. 

There are people far more talented than me looking at this in the ssh2/ssh2-streams community - the big problem they are having is being able to reliably reproduce the problem. If you cannot reliably reproduce the issue, you cannot verify the fix. What is needed is access to a server where this can be reliably reproduced - so far, it seems all reported instances are either on servers which are not open to testing or servers where the issue is only intermittent. My guess is that ssh2/ssh2-streams will need to become more 'liberal' in what it will accept i.e. allow user to request chunk size and/or highWaterMark, but actually use whatever the server does.

**Comment by wmagda** [comment]
I can definitely reproduce this issue every time but I can't share the server... If it helps here is the server version: SSH-2.0-CerberusFTPServer_10.0

**Comment by theophilusx** [comment]
I have added some checksum tests to my fork at https://github.com/theophilusx/ssh2-sftp-client. It would be interesting to see what results anyone seeing data corruption get if they try and run the tests against the server they are using. 

To do this, just create a .env file in the root directory with the following properties

```
SFTP_SERVER=<sftp host>
SFTP_USER=<username>
SFTP_PASSWORD=<password>
SFTP_URL=<path to dir where we can read/write files/dirs>
```

Then just execute 

```
npm test
```

or 

```
npm test test/checksum-tests.js
```

to run just the checksum tests. 

So far, I've tried 2 different sftp servers, both have passed with no failures.

**Comment by wmagda** [comment]
My concern here is that I can use FileZilla to download this file just fine so their code somehow handles this weird server config just fine.  Because of that I can't complain to server owner about this issue.

**Comment by theophilusx** [comment]
@wmagda I don't think anyone would deny that filezilla is a more mature bit of software which undoubtedly includes a number of checks and workarounds for various sftp server quirks. That software has been around for longer than nodejs has existed and has a lot more contributors and developers both testing and working on it. 

Note also that I'm not suggesting that this issue can or should only be fixed at the server issue. The problem is, in order to fix it, we have to reliably reproduce it in an environment where which can be used for testing. I personally have not been able to find such an environment. I don't think complaining to server administrators will achieve anything. A more constructive approach may be to ask the server administrators if they would be willing to provide an account for testing (or access to a testing server with the same configuration). This would then allow the ssh2 developers access to an environment where they can test and debug the problem and hopefully find a solution.

**Comment by rkaw92** [comment]
Are you using an encoding option? Have you tried setting encoding to `null` in the .get() invocation?

**Comment by wmagda** [comment]
In the end I found a "workaround"? (or is it a fix?)
 https://github.com/jyu213/ssh2-sftp-client/issues/37
That  { highWaterMark: 65535 } fixes the issue for me and I don't see any side effects so far.

**Comment by theophilusx** [comment]
I would say it is a workaround. 

This adds further weight to my suspicion the problem is related to the underlying SSH2 module issue I referenced earlier. Basically, client and server are not correctly negotiating the same values. Seems some servers don't indicate when they are going to ignore requested values, so things get out of sync. 

Would probably be best to only apply this to server connections where you know it is an issue and watch out for updates which include updates to the underlying SSH2 module as I expect this will be addressed once someone works out the best approach. 

Gald you at least have a workaround.

**Comment by theophilusx** [comment]
I cannot reproduce this issue. Have tried against a number of different servers. Have added tests which perform checksums for both upload and download of data. As there have been a number of changes since the original issue, together with the known issues logged against the ssh2 and ssh-streeams libraries. I think this issue can be closed.  If others experience similar problems, we can open a new issue (or reopen this one).
