### ISSUE TITLE
Unable to connect to ftp server

### ISSUE THREAD

**Issue by cnp96** [theophilusx/ssh2-sftp-client#124]
Hi,

I'm unable to connect to public FTP server `ftp://speedtest.tele2.net:21`.

Here is my implementation,
```
const SFTPClient = require('ssh2-sftp-client');
const sftp = new SFTPClient();

sftp.connect({
  host: 'speedtest.tele2.net',
  port: 21,
  username: 'anonymous',
  password: '',
  debug: console.log
}).then(async conn => {
  console.log('connected');
  let data = await conn.list('./');
  console.log(data);
  await sftp.end();
}).catch(e => console.log(`Unable to connect -- ${e.message}`));
```

Debug log
```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.2'
DEBUG: Client: Trying speedtest.tele2.net on port 21 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
Unable to connect -- Timed out while waiting for handshake
```

**Comment by svda** [comment]
Are you trying to connect to a regular FTP server instead of SFTP?

**Comment by theophilusx** [comment]
As there has been no response to this question since May, closing it as a dead issue

**Comment by goors** [comment]
I have the same issue. I am trying to connect to ftp (vsftpd).

```DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.6'
DEBUG: Client: Trying 52.29.188.96 on port 21 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.6'
DEBUG: Client: Trying 52.29.188.96 on port 21 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT

{ Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/node_modules/ssh2/lib/client.js:695:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) level: 'client-timeout' 
}
```
And no idea how to resolve it.

**Comment by theophilusx** [comment]
You appear to be trying to connect to port 21, which is the default port
for ftp, but not for sftp, which is normally port 22. The error message
you are getting indicates your getting connected to the host at the TCP
level, but there is no sftp protocol negotiation occurring, which
suggests whatever is listening on remote port 21 is not sftp.

First thing I would do is try to connect using a command line utility,
such as openSSH's sftp, making sure you are using the same port,
credentials etc. If sftp also fails, then you know your problem is not
in your JS code or the ssh2-sftp-module.



-- 
Tim Cross
