### ISSUE TITLE
compressed files 

### ISSUE THREAD

**Issue by mpostman** [theophilusx/ssh2-sftp-client#125]
`sftp.connect({
host: 'partnerupload.google.com',
port: '22',
username: 'username',
password: 'password',
compress:false //or true
});`
With fastPut
`sftp.fastPut('pathtolocalfile.zip','remote.zip',{
                step: function ( totalTx, chunk, total ) {
                    console.log( 'uploadFile.step totalTx', totalTx, 'chunk', chunk, 'total', total );
                }
              })`
with put  and binary
`sftp.put('pathtolocalfile.zip','remote.zip',[false],null,{
                step: function ( totalTx, chunk, total ) {
                    console.log( 'uploadFile.step totalTx', totalTx, 'chunk', chunk, 'total', total );
                }
              })`
at the end on server-side I have corrupted file. Same size, but file are corrupted.

What I'm doing wrong?

**Comment by theophilusx** [comment]
Not clear exactly what your trying to do, but all those additioinal options are not required. For fastPut, you just need the local and remote file paths. For put(), the first argument can be either a local file path or a stream (e.g. to compress files on the fly). The only additional argument you may  want to specify is encoding, which should be null since you are sending binary data (gzipped). However, null is the default, so not really necessary.

**Comment by theophilusx** [comment]
No response on issue. Closing.

**Comment by theophilusx** [comment]
Treat them as if they are binary files i.e. null encoding. This is the
default, so don't specify an encoding.
