### ISSUE TITLE
Unable to disconnect from sftp with sftp.end()

### ISSUE THREAD

**Issue by zohon** [theophilusx/ssh2-sftp-client#129]
i try to end the connection after the connect function but get an error

**the code**

```
const sftp = new Client();
sftp
    .connect({
      host: host,
      port: "22",
      username: username,
      password: password
    })
    .then(() => {
      sftp.end();
    }) .catch(err => {
      console.error(`ERROR ${err}`);
    });
```
and i get this error message : 

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)

**Comment by KieranMcKeefery** [comment]
I've also had this exact same issue, especially when looping through files to upload. I get an undefined error after a while.

**Comment by theophilusx** [comment]
I cannot reproduce this error. There has been considerable changes in the current development branch since this issue was logged, especially in the area of error handling. I suspect these changes have resolved this issue. I have added the above code as one of the unit tests as well as a number of additional tests designed to generate various errors and all are currently passing.  Testing has been against the release-4.0.0 branch. I hope to release this version in a couple of weeks time.
