### ISSUE TITLE
Zero length files using `.get()` with `2.5.0`

### ISSUE THREAD

**Issue by createthis** [theophilusx/ssh2-sftp-client#132]
I'm running node `v8.15.1`.

Noticed my files were coming down as zero byte files since March 30th 2019 when we did a release.

checked the logs and saw this error:

```js
(node:10933) UnhandledPromiseRejectionWarning: TypeError: stream.pipe is not a function
```

Code at this point looks like this:
```js
await this.sftp.get(remote_filename).then((stream) => {
  stream.pipe(fs.createWriteStream(local_path));
});
```

So there is no `.pipe()` on the `stream` object at this point for some reason. I did a console log on the `stream` object and it is a `Buffer`.

Checked the `ssh2-sftp-client` version and we were running `2.5.0`.

Downgraded to `2.4.3` and the problem resolved itself.

I'm not sure what changed between `2.4.3` and `2.5.0`, but clearly it broke my code.

**Comment by viamuli** [comment]
This happens because you have something like "~2.x.x" or "^2.x.x" in your package.json. NPM uses the semtantic version toolkit to determine which version to install and if it's "^x.y.z" then the latest minor release (y) is installed.

The public API changed with 2.5.0 which actually should be 3.y.z to prevent errors like these. Changes made from 2.4 to 2.5 are best (and fastest) seen at the type definition pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34739

**Comment by smulder** [comment]
yeah, 2.5 has another issue: 
Error: Failed get on FILE_PATH_GOES_HERE: dst.on is not a function
    at Promise (/FILE_PATH_GOES_HERE/node_modules/ssh2-sftp-client/src/index.js:190:23)
    at new Promise (<anonymous>)
    at SftpClient.get (/FILE_PATH_GOES_HERE/node_modules/ssh2-sftp-client/src/index.js:154:10)
    at sftp.list.then (/FILE_PATH_GOES_HERE)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

**Comment by theophilusx** [comment]
Agree that the version should have been increased to 3.x.y because the changes broke the existing API. This was in the PR, but did not occur - don't know why.

**Comment by theophilusx** [comment]
The next release which alters API ini any way will have a new major version  number. This will also be the practice for all future releases.
