### ISSUE TITLE
(SSH) Channel open failure for a particular FTP Server

### ISSUE THREAD

**Issue by apasrini** [theophilusx/ssh2-sftp-client#138]
I am seeing (SSH) Channel open failure error for Wing FTP Server. demo.wftpserver.com/login.html. I am using the SFTP server of it. 

Can you please tell me the cause of this issue?

**Comment by apasrini** [comment]
For Example i have a piece of code execute twice -

let Client = require('ssh2-sftp-client');
let sftp = new Client();
sftp.connect({
    host: 'demo.wftpserver.com',
    port: '2222',
    username: 'demo-user',
    password: 'demo-user',
    readyTimeout: 25000
}).then(() => {
    return sftp.list('/download');
}).then((data) => {
    console.log(data, 'the data info');
}).catch((err) => {
    console.log(err, 'catch error');
});
sftp.connect({
    host: 'demo.wftpserver.com',
    port: '2222',
    username: 'demo-user',
    password: 'demo-user',
    readyTimeout: 25000
}).then(() => {
    return sftp.list('/download');
}).then((data) => {
    console.log(data, 'the data info');
}).catch((err) => {
    console.log(err, 'catch error');
});

Response
undefined 'catch error'
undefined 'catch error'



let Client = require('ssh2-sftp-client');
let sftp = new Client();
sftp.connect({
    host: 'demo.wftpserver.com',
    port: '2222',
    username: 'demo-user',
    password: 'demo-user',
    readyTimeout: 25000
}).then(() => {
    return sftp.list('/download');
}).then((data) => {
    console.log(data, 'the data info');
}).catch((err) => {
    console.log(err, 'catch error');
});
let sftp1 = new Client();
sftp1.connect({
    host: 'demo.wftpserver.com',
    port: '2222',
    username: 'demo-user',
    password: 'demo-user',
    readyTimeout: 25000
}).then(() => {
    return sftp1.list('/download');
}).then((data) => {
    console.log(data, 'the data info');
}).catch((err) => {
    console.log(err, 'catch error');
});

Proper Response is received.

**Comment by apasrini** [comment]
Should let sftp = new Client(); - be initialized for every call ?

**Comment by theophilusx** [comment]
If I understand your examples correctly, in the first one, you have created 2 promises, but used the same variable for both of them, whioch is going to be an issue. Don't forget that just because you call two promises one after the other that they will be executed one after the other - they are asynchronous code blocks not synchronous. In the second example, you are using two different variables sftp and sftp1, so they don't conflict with each other and probably explains why they work when the first one does not.  If you just wanted to use one variable name, then you would need to wrap it all in an async and use await on each promise chain. This would force the promises to be executed synchronously.  Alternatively, you could use Promise.all()

**Comment by theophilusx** [comment]
Did the suggested changes help or is this still an issue?
