### ISSUE TITLE
Missing file segements in upload

### ISSUE THREAD

**Issue by Bern222** [theophilusx/ssh2-sftp-client#145]
Im running a job to upload a group of csv files async to a sftp.  For some reason I get the error:
"Missing file segements in upload:0" randomly.  I set a loop to retry the upload 5 times before failing and 90% of the time the upload would complete after failing 2-3 times.  The files that are failing range from 40KB to over 20MB. 
I searched ssh2-sftp-client and ssh2 for this error but I've found nothing.  The error does have "segements" misspelled but I still couldn't find anything with the correct or incorrect spelling. 

node 9.11.2

**Comment by theophilusx** [comment]
There are no errors of that type/name generated by ssh2-sftp-client, so the errors must either be coming from the udnerlying SSH2 or SFTP_ST%REAMS libraries this module uses. I have seen issues in the ssh2 and ssh-streams issue logs referring to problems with lost/truncated data due to buggy SFTP servers which don't report/respond to network chunk size requests correctly. Maybe have a look that their issue logs to see if you can get more details?
