### ISSUE TITLE
Does this node module support all file types

### ISSUE THREAD

**Issue by apasrini** [theophilusx/ssh2-sftp-client#162]
File transfered getting corrupted. I am trying to add a base64 encoded string as data and creating a file and see the file is corrupted when adding. I see this issue with jpg and files which are not a text file.

**Comment by theophilusx** [comment]
There are no restrictions on file types and I have used it successfully with both binary and text data. Will need a lot more details (ideally, sample code and configuration, platform and node version) in order to provide any help/advice. If you are setting encoding to utf-8, try not setting it or setting it to null (which is the default). Which methods are you using? If using put, what source are you using (buffer, stream or path)?

**Comment by apasrini** [comment]
This issue is resolved. Content has to be base64
