### ISSUE TITLE
In Windows, the generated path uses the Windows path separator, which results in errors.

### ISSUE THREAD

**Issue by bigfacewo** [theophilusx/ssh2-sftp-client#174]
In line 668 of index.js `await this.delete(join(absPath, f.name));`, the join method is used, which is called under windows. The resulting path uses the windows delimiter, resulting in an error of "Error: sftp.rmdir: sftp.rmdir: sftp.delete: No such file".

**Comment by theophilusx** [comment]
Good catch. I have to admit, I'm not a windows user and testing on that platform is not as complete as on Linux or macOS. I need to fix my Windows VM before I can test a fix for this. 

A full fix is tricky if we also don't want to impact perfromance too much. Some bits will be easy to fix, but others are more challenging due to the possible different path combinations (windows client and windows server, windows client and linux/mac server, linux client and linux server, linux client and windows server). 

I will create a new branch to develop this fix. Any assistance with testing will be appreciated. Will update this issue as progress is made.

**Comment by wukaikailive** [comment]
I have two ideas:
1. The user specifies the type of target server, windows or Linux.
2. Can you get the version information of the server from the connection of sftp?

**Comment by theophilusx** [comment]
@wukaikailive. Yes, those are my thoughts as well.

What I'm considering is once the SFTP connection has been established,
do a call to client.realPath('.'), which will return the base path of
the connection. Should then be able to parse this path to determine
server type and set the remote path separator.  From then, use that
instead of path.join() to create remote file paths. This should also
have the advantage of eliminating some of the existing calls to
client.realpath() as we can store the base path and use it to work out
the fully qualified path without doing remote call, making some
operations faster (will still want realpath call to verify file exists
when appropriate). 

If that doesn't work out or has performance problems, then I guess I'll
have to revert to adding a new parameter to the connect config which
allows users to specify the type of remote server.

Would like to avoid having to add new parameter as I think in some
cases, this will be a bit of a pain for users (they may not necessary
know, without testing/experimenting, what type of platform the remote
server is, plus sometimes people change server platforms, but retain
original IP address)

-- 
Tim Cross

**Comment by theophilusx** [comment]
OK, have pushed a fix into the windows-path--fix branch which is an initial go at fixing the path problems when client or server are different platform to each other. Needs testing.

**Comment by theophilusx** [comment]
Testing of the fix in the windows-path--fix branch is looking good. All tests, with the exception of some permission tests, are passing. The permission tests are failing because of inherent differences in the windows file system and probably just need to be skipped when testing from a windows platform. 

I will probably merge changes into master branch later this week. In the meantime, if anyone has time to also do some testing (especially if windows is your 'native' platform) that would be really helpful.

**Comment by theophilusx** [comment]
The windows-path--fix branch has been merged into master

**Comment by bigfacewo** [comment]
Thanks for your work. 
I think I can close this issue.
