### ISSUE TITLE
Now impossible to just read data from sftp file

### ISSUE THREAD

**Issue by Tirke** [theophilusx/ssh2-sftp-client#184]
Hello,

This is more a question than an issue but still maybe an issue.

We were using the version 2.0 of this package and I'm trying to migrate.
The `get` method no longer returns a `ReadableStream` and the only alternative is now to wait for the whole Buffer or to pass a WritableStream as dst.

The problem is that I don't need to write the file on the filesystem. I just want to read the file and start processing it **immediately** to write it to AWS S3. Previously I used the readStream with `BlockStream` to chunk it and doing a multipart upload.

It seems more hard to do this now. `ssh2-streams` still has a `createReadStream` method so I don't really know why it has disappeared from `ssh2-sftp-client`.

If you can help me a little bit it would be great.

**Comment by theophilusx** [comment]
The new get() method is actually easier as you don't need to create the readStream. Just pass in your block stream object and get() will pass the data to it via pip().

**Comment by Tirke** [comment]
Block is not a `Writable` it is a `Transform`. I don't think `get()` can accept a stream that is not `Writable` but maybe it does?

**Comment by theophilusx** [comment]
All get() cares about is that the stream supports pipe(). For example, I use the gunzip object to unzip *.gz files, which I then pip() to another stream which processes the output from gunzip. You can use a similar approach. I believe transform streams need to support pipe() in order to meet the spec, so you should be fine. Suggest you try it and see.

**Comment by Tirke** [comment]
Yep I tried it, everything is working alright. Thanks for your time.
