### ISSUE TITLE
Error handling using codes.

### ISSUE THREAD

**Issue by Tirke** [theophilusx/ssh2-sftp-client#185]
Hello again,

You changed the error handling some times ago. You no longer provide the end user with the code that is present in the `ssh2` lib. 
We have a lot of code that does different things according to the error code but it seems we can no longer do that because you don't provide us with the code anymore.
The error message provided are also too vague to be able to use that instead.

Is it possible for you to bring back the error codes? Or is it a voluntary change on your end? In that case can you explain how I can achieve the custom error handling?

Thanks a lot and sorry for bothering you today.

**Comment by theophilusx** [comment]
Yes, this is on the todo list. There are some issues with inconsistency in error reporting from dependencies and I was waiting until EOL for node v8 so that I can take advantage of the error codes introduced in node v10.  Ultimately, the objective is to provide error reporting with consistent error message formats as well as consistent error codes.  Now that v8 is nearly EOL, it is probably time I revisited this issue.

In the meantime, you might be able to work around the limitation using the on() method to add your own  error listener. This won't give you access to ssh2-sftp-client errors as they are not 'emitted', but it would give you access to the underlying ssh2 errors.

**Comment by Tirke** [comment]
Thanks again for your support. We will try the workaround while waiting for those great looking enhancements 😄

**Comment by theophilusx** [comment]
I have added basic error codes into the formatError function, so it should now be possible to use error.code in error handling etc. The changes are in the error-codes branch. If you would like to try out that version, that would be great.  I will likely release it as a new version later this week.

**Comment by theophilusx** [comment]
Released this enhancement as part of v4.3.0
