### ISSUE TITLE
Timeout waiting for handshake.

### ISSUE THREAD

**Issue by corsmond** [theophilusx/ssh2-sftp-client#188]
I am getting the above error more often than not running on a windows machine connecting to and external sftp server. 
Using the console "sftp" command I can connect evertyime very quickly and list my folders, but using this or any of the other ssh2 modules, I get a timeout waiting for handshake. Running debug it gets stuck at `DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP`

**Comment by theophilusx** [comment]
What version of node and which version of ssh2-sftp-client?

Can you also indicate what options you are using to connect (port,
password or key file etc).

Claudius Orsmond <notifications@github.com> writes:

> I am getting the above error more often than not running on a windows machine connecting to and external sftp server. 
> Using the console "sftp" command I can connect evertyime very quickly and list my folders, but using this or any of the other ssh2 modules, I get a timeout waiting for handshake. Running debug it gets stuck at `DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP`


-- 
Tim Cross

**Comment by corsmond** [comment]
Node v12.13.0
 ssh2-sftp-client@^4.2.3

{
  "host": "vltrader.supergrp.net",
  "port": 22,
  "username": "xxxxx",
  "password": "xxxxxxxxxxxxxxx"
}

**Comment by corsmond** [comment]
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.6
debug1: Remote protocol version 2.0, remote software version Cleo VLTrader/5.6.1.0 SSH FTP server

**Comment by theophilusx** [comment]
From what you say about other ssh2 modules and the type of error you are seeing, I suspect the issue may be with either the ssh2 or ssh2-streams module. If this is the case, then there is nothing I can do at the ssh2-sftp-client module and you would need to lodge an issue with the maintainer of those libraries. 

To try and verify this, there are two scripts you can try. In the ssh2-sftp-cleint repository, there is a directory called 'tools'. In this directory is a script called lowlevel-realpath.js. This script will take a remote file path on the command line and verify if it exists on the remote server. It only uses the ssh2 and ssh2-streams libraries (no ssh2-sftp-client module). If this also fails, then the problem is definitely with those modules and you will need to work with their maintainer to get the issue resolved. 

In the ssh2-sftp-client repository, there is also a script called realpath.js which does the same thing as the lowlevel-realpath.js script, but uses the ssh2-sftp-client module. If the lowlevel.realpath.js script works and this one does not, then we know the issue is with the ssh2-sftp-client. 

If both scripts work, then the issue must be with your code. Happy to try and spot the problem if this is the case and you can post your code. 

So, first step is to try running these two scripts and see what occurs. You will need to adjust the scripts for host, port, username and password and likely fix the paths in the require statement (depending on how you download and what you run etc).

**Comment by corsmond** [comment]
It seems to be ssh2 or ssh2-streams. Thank you very much for your assistance.

**Comment by corsmond** [comment]
Fixed it by setting kex algorithm to 'diffie-hellman-group1-sha1'
