### ISSUE TITLE
Error While Uploading large file (around 27 kb or more) using "put" or "fastPut"

### ISSUE THREAD

**Issue by wahajahmed** [theophilusx/ssh2-sftp-client#193]
Version using: 4.3.0

I am getting this error while uploading large file (around 27KB or more) using "put" or "fastPut" to a SFTP server.

> 
> Error: my-client: read ECONNRESET
>     at formatError (D:\xxxxxx\node_modules\ssh2-sftp-client\src\utils.js:54:18)
>     at Client.<anonymous> (D:\xxxxxx\node_modules\ssh2-sftp-client\src\utils.js:80:11)
>     at Client.emit (events.js:182:13)
>     at Client.EventEmitter.emit (domain.js:441:20)
>     at Socket.<anonymous> (D:\xxxxxx\node_modules\ssh2\lib\client.js:307:10)
>     at Socket.emit (events.js:187:15)
>     at Socket.EventEmitter.emit (domain.js:441:20)
>     at emitErrorNT (internal/streams/destroy.js:82:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

Below is my sample code

```
function UploadFileToSFTPServer(localFilePath, remoteFilePath) {
  const sftp = new SFTPClient('my-client');
  return sftp.connect(SFTP_CREDENTIALS)
    .then(() => {
      console.debug('UploadFileToSFTPServer put', 'Uploading file');
      return sftp.put(localFilePath, remoteFilePath);
      // or return sftp.fastPut(localFilePath, remoteFilePath);
    })
    .then(() => {
      console.debug('UploadFileToSFTPServer end', 'sftp end');
      return sftp.end();
    })
    .catch((err) => {
      console.error('UploadFileToSFTPServer error', err.message);
    });
}
```

Small files (2KB to 5KB) are uploading fine but getting above error while uploading large file.

**Comment by theophilusx** [comment]
That error indicates the remote server is closing the connection. If you can access the remote server logs, you might be able to find something which would help to explain the error. 

Another thing to try is to use put() instead of fastPut(). some sftp servers don't support 'chunking', which is required for the fastPut() to work successfully. 

Also note that there are known issues with BrickFTP (files.com). The issues impact on ssh2 and ssh2-streams (the modules used by this module to do the heavy lifting), so if your using that site, your probably out of luck. 

The test cases I use have large file upload/download and perform CRC checks to ensure file inegrity. this doens't mean there is no issue, but it does mean I will need a way to reproduce the issue in order to debug it. 

I would start by seeing if you can find out why the remote server is dropping the connection. If put() works, it is likely the remote sftp server does not use chunking and uou will have to use the slower put() method.

**Comment by theophilusx** [comment]
I now see in your code you have tried put(), so I guess you need to try and find out why the remote server is closing the connection. Nothing in your code jumps out as being incorrect.

**Comment by theophilusx** [comment]
Any update on this issue? Were you able to make any progress towards resolving it or tracking down the cuase or creating a mihnimal reproducible example?

**Comment by wahajahmed** [comment]
Hi @theophilusx,

I was some issue with our company's network firewall IDS (Intrusion Detection System) system. Network guy told me that OpenSSH version on the target SFTP server is old/obselete. Some rule defined in IDS was considering this remote OpenSSH as non-trusted. So after making connection with remote server, small file uploading was taking very less time. But for large file, data transmission/propagation was taking large amount of time and the Firewall IDS was assuming that this is some (sort of) DOS attach, hence terminating the connection.

After by-passing our network firewall (using another network) solved this issue.

Thanks for your help and suggestions.

**Comment by theophilusx** [comment]
Thaks for letting me know. This provides useful information for others
who may run into similar issues and stumble across this issue.


-- 
Tim Cross
