### ISSUE TITLE
5.0.0 Breaking Change - list method fails when parent path permissions are not allowed

### ISSUE THREAD

**Issue by zjrosen1** [theophilusx/ssh2-sftp-client#205]
Prior to 5.0.0 the list method did not call checkRemotePath which is going up a remote path and calling exists on each path. If a user has permission in a subfolder of a root path but not a root path. The list call will fail with a permission error.

Example

/users/john

If you only have read access on /users/john list will still call exists on /users and / paths which will fail

This would apply for anywhere checkRemotePath is being used as well not just on the list method

**Comment by theophilusx** [comment]
Actually, that is a very important point I had over looked. I had
forgotten that in many cases, under ftp/sftp, you remove execute
permission on directories, primarily when they are shared amongst
multiple users, to prevent others from being able to see what is in
there. I'll need to re-think checkRemotePath().

I'll  comment out checkRemotePath and release an update for the time
being.

thanks.

Tim


-- 
Tim Cross

**Comment by theophilusx** [comment]
Have pushed a new version to the repo and will publish v5.0.1 soon. 

For clarity, the previous checking didn't check all the path, only the parent directory. However, as it did use list(), this was a problem if the user did not have read and execute permissions on that parent directory. Have modified the exists() method to use stat() instead of list(), which should avoid the need to list the parent directory and is probably faster. Have also removed a number of calls to realPath() as they were not absolutely necessary and realPath fails if you don't have read/execute permission on the parent. 

The checking /might/ still be too stringent. However, I want to try and find the right balance here. Majority of issues raised against this module turn out to be permission or file/dir conflict problems. Unfortunately, many of the errors reported by underlying systems just report 'Failure', which doesn't help users identify the issue. If we can provide more meaningful errormessages, this will help users, but the downside is ensuring we can adequately cater for sftp servers which set permissions to prevent users from listing contents of directories (a common setup for anonymous sftp setups). 

If this still proves to be an issue, we may need to completely remove the additional error checking on some operations. For now, suck it and see!

If you can try out the new version and let me know if it still cases you issues. If it does, can you specify exactly which operations you cannot perform and what the exact permissions are on the parent and parent's parent directories so I can develop better test cases.

**Comment by theophilusx** [comment]
Have published v5.0.2 which had some further fixes for local file tests. I think this issue is now resolved and am closing it.

**Comment by zjrosen1** [comment]
Thanks for closing @theophilusx, I'm yet to try it 5.0.2 but will follow up if I see any new problems arise
