### ISSUE TITLE
Downloading large files having issue

### ISSUE THREAD

**Issue by anuborah** [theophilusx/ssh2-sftp-client#214]
I am trying to download large files to my local connecting through SFTP , but its not downloading the whole large files.Suppose the PDF file in FTP is 4MB , when I bring to local the PDF size reduces to 2MB and the PDF file cannot be open. I have tried to use both get() method and fastGet() method , in both cases it doesnot download the large pdf. And also if I intent to download large Zip .Let say 1 GB of data , please suggest me on how to download large file.What configuration change I need to do , to make it work.
i have noticed the issue occured when we close the SFTP connection.If we dont close the connection , then the file gets downloaded successfully locally.

The ftp connection get closed before getting the files
![image](https://user-images.githubusercontent.com/47774591/75005017-fed70f00-54a7-11ea-9492-63dd6022ffbb.png)

Please kindly let me know how to fix this issue

**Comment by theophilusx** [comment]
Your script has a bug. You need to add 'return' inside the then handlers so that the new promise is passed back into the chain correctly. Because you don't have the return, the .then() block with the end() call is running as soon as the statement calling fastGet runs rather than when the promise generated by fastget() resolves.
