### ISSUE TITLE
"close" event in connect not unsetting this.sftp

### ISSUE THREAD

**Issue by james-pellow** [theophilusx/ssh2-sftp-client#219]
Hey Tim, when we removed the close handler from the constructor we are now no longer unsetting this.sftp on the "close" event.  There is a side effect in `utils.makeCloseListener`'s returned function.  I think we need to put that handler back in the constructor.  Originally `this.client.on('close', utils.makeCloseListener(this));` was found in the `connect` method, but that was creating a handler that was never removed and `connect` can be called multiple times, so the handlers would stack up.  That's why I had moved it to the constructor, and all listeners are removed when you call `end`.  If we move it back to `connect` we have to handle the possibility of `connect` being called multiple times.  Anyway, we need to unset this.sftp on "close" or we get "'An existing SFTP connection is already defined" error when we try to reconnect.  Thoughts on restoring it to the constructor?

**Comment by theophilusx** [comment]
Hmm - thats a drag. Thinking about it, I think we probably need a close handler which
is never removed and stays active during the life of the object - a
global close handler.

A close event can occur at any time. This includes in-between other
method calls and we need the global close handler to unset the sftp
object so that any subsequent attempts to use one of the methods will
fail with a no connection error. In addition, we need per method close
handlers so that we can reject the promise (this is the bit that was
missing before as I assumed you always got an error event before a close
event) - so two levels of close handlers with the method close handlers
being added with prependListener so that they are called before the
global close handler. (We can also get an error event 'outside' any
method, but we don't really care about those errors provided we know
when they have resulted in the connection being closed, so I don't think
we need a global error handler as the close handler will deal with that).

The global close handler needs to be added and left, never removed. If
we remove it, things will break if it is added in the constructor and
then the connection is closed and then re-opened (rather than a new
object being created).

I'll try to add it later today or early tomorrow. I hate releasing
another version straight after, but I also noticed just after releasing
5.1.1 that the underlying ssh2 and ssh-streams libraries the module uses
had a new release put out only a few hours before I released 5.1.1, so
now we have a second reason to release another version.

**Comment by james-pellow** [comment]
Sounds good.  I completely agree with your analysis.  I had moved both the error and the close handlers to the constructor, but I think you are right that we only need a "close" handler there.  It does need to be a global thing that stays alive for the life of the object.  I'll just keep using my fork till you make a new release.  Thanks!

**Comment by theophilusx** [comment]
Hi James,

I have updated the master branch and I think it now handles close
correctly. Can you try it to verify it still fixes the issue you had?

Note that I added a new function in utils call dumpListeners, which just
dumps out a count of how many listeners each event type has (if they
have any). There is a call to this function commented out in the finally
clause of the end() method. When I run it, it shows only one close
listener exists for each of the tests I have defined, so I think it is
working OK. You might want to uncomment it before running in your
context and verify there is no listener 'leakage'.

I have also bumped the ssh2 dependency to be the latest version.

**Comment by james-pellow** [comment]
Seems to work very well.  Thanks.  I was having a hard time getting time today.

**Comment by theophilusx** [comment]
OK, thanks. I have released 5.1.2
