### ISSUE TITLE
How can I know the real-time network speed during uploading ?

### ISSUE THREAD

**Issue by KingGanZeng** [theophilusx/ssh2-sftp-client#222]
This package helps me a lot for building a `sftp` tool.
Although it has fundamentally finished its job, i think it will be better if it can provide a method to test real-time network speed during uploading or downloading files from a server.

**Comment by theophilusx** [comment]
I have no plans to implement this feature myself. The idea of this module is
to provide minimal basic sftp operations. This sort of function is more
along the lines of what I'd expect a client to implement rather than
part of this module. I suspect adding such a feature could adversely
impact performance, especially for uploads, where you would need to
query the remote server to calculate data uploaded (there is nothing in
the ssh2/ssh2-streams API to report bytes in/out. You could possibly do
something locally for the stream/buffer based operations, but not the
file based ones like fastGet/fastPut). 

Having said that, I'm more than happy to consider a pull request, so if
you feel it would be a valuable addition. please feel free to contribute!

**Comment by KingGanZeng** [comment]
@theophilusx thanks for your explication. I will try to find another way to satisfy my requirement. Besides, if it works, i will be glad to make a contribution to this excellent project.

**Comment by theophilusx** [comment]
Closing this issue. If this functionality is required, it can probably be achieved by using a stream which monitors/calculates throughput and passes the data through. This stream can then be used as the input or output stream in an upload/download call as the stream API simply pipes input/output streams (so you can chain as many additional stream objects to do things like monitor throughput, limit throughput, convert throughput etc). Basically, the developer can control this.
