### ISSUE TITLE
Await sftp.get(remote,local) fail cause await/async

### ISSUE THREAD

**Issue by fatoldsun00** [theophilusx/ssh2-sftp-client#223]
Hi; 

i have trouble when i do a sftp get with await. With list, put and delete no prob but get method fail and tell me that remote file not exist 

`"get->get: No such file: /get/test.txt"`

with stfp.get(remote, local).then() everything is fine. 

On clean projet await get works, but not in my script. I haven't mix then and await. My code is into a callback but like i say, put delete and list works fine

Any idea ?

Thank

**Comment by theophilusx** [comment]
Without analysing your code, I have no idea. The fact it works in some
contexts and not others does suggest a bug in your script. The methods
in the module do not know what context they are being used in i.e. await
or promise chain or what project or anything else. If you get success
with a Promise chain and the same fails when used with async/await, then
the problem is definitely a bug in your code.

**Comment by fatoldsun00** [comment]
Hi,

Thank for your reply. 
Now it's okay... and i don't know why...
But everythind it's fine, sorry for bad issue
