### ISSUE TITLE
Double-byte characters "broken" using .fastGet()

### ISSUE THREAD

**Issue by QAnders** [theophilusx/ssh2-sftp-client#227]
First off, thanks for your superb work! Very much appreciated!

I am currently re-writing some code and migrating a server install to AWS Lambdas and during this process I wanted to move the old `child-process` calling Linux SFTP to something a bit "niftier", i.e. `ssh2-sftp-client`!

All testes this far works great except for "broken" double-byte characters when using `.fastGet()`. E.g. the Swedish "å ä ö Å Ä Ö" becomes two "garbage" characters.

I did some experimentation and found that the files written to the `/tmp` of the AWS Lambda is still "intact" if I pick them up as `Latin1`:

`const fileContentL1 = await fs.readFileSync(`/tmp/${file.name}`, 'latin1');`

So, this however wrecks any files that happen to be `utf-8` instead and as it is an external source adding the files I can't control the encoding...

I wrote this as a work-around:

```
          await sftp.fastGet(`${path}/${file.name}`, `/tmp/${file.name}`);
          let dataBuf = await fs.readFileSync(`/tmp/${file.name}`);
          // data3 now holds the file data content
          try {
            // This seems like an overkill solution but we need to know if data fetched is UTF-8 or Latin1
            // If Latin1 we need to wobble it around to not wreck "double-bytes", e.g. Å, Ä or Ö
            const td = new util.TextDecoder('utf8', { fatal: true });
            td.decode(Buffer.from(dataBuf));
            dataBuf = dataBuf.toString('utf8');
            console.log('Buffer data is UTF-8!');
          } catch (err) {
            // It is not UTF-8, since it failed so we'll assume it is Latin1.
            // If not it will throw it's own Buffer error or transformation will fail...
            if (err.message === 'The encoded data was not valid for encoding utf-8') {
              const l1Buffer = Buffer.from(dataBuf, 'latin1');
              const l1String = l1Buffer.toString('latin1');
              dataBuf = Buffer.from(l1String, 'utf8');
              console.log('Buffer data was Latin1, now converted into UTF-8 successfully!');
            }
          } // This now has the "clean" data
          console.log('Final values:', dataBuf.slice(0, 265));
```

This runs in a "loop" where we fetch hundreds of files at a time so using a "try/catch" doesn't feel too good...

Is there any way of "converting" on the fly using `.fasGet()` making sure the data is always stored as `utf-8` ?

**Comment by theophilusx** [comment]
Unfortunately, I don't think so. The fastGet() method is implemented by
the SSH2-streams library. All that ssh2-sftp-client does is wrap that
call in a promise. Essentially, it is a black box and we don't have
access to the internals (plus, it achieves the increased speed by
downloading the file in parallel 'chunks'). It does have an option to
set the encoding, but you need to know what that is, which sounds like
you don't.

The only other thing you could do is use get() instead of fastGet and
pipe that into your code to test and convert when necessary. This would
be slower, but perhaps not any slower than what your doing now? I have
used this approach when I want to decompress zipped files 'on the fly'
and have found the performance acceptable (though that of course will
depend on your requirements, network and number of files needing to be
processed).

**Comment by QAnders** [comment]
Ah, OK, thanks for the quick response!

I'll stick with my solution for now and see if it isn't too bad om the performance (but initial tests looks like it doesn't add much).
