### ISSUE TITLE
Is it possible to store the datas in variable instead of a LocalFile with fastGet

### ISSUE THREAD

**Issue by Preethamveigas** [theophilusx/ssh2-sftp-client#228]
**fastGet(remotePath, localPath, options) ===> string**
Issue:- fastGet destination constraints. 
Testing environment :- Aws Lambda.
Limitations :- 512 Mb Local File Space and 15mins of run time.
 
While testing the sftp.get if the target file size is above 800mb lambda runs into timeout,
and with sftp.fastget the local file size limited to 512Mb. so if sftp.fastget has any workaround or implementation which allows to store data in variable instead file path am assuming it will work.

**Comment by theophilusx** [comment]
If I understand your question correctly, no. The fastGet() method is
implemented by the SSH2-Streams library which ssh2-sftp-client uses.
There is no facility/api options which would allow putting the data into
a variable, buffer or stream. The destination can only be a file on the
filesystem.

Your only choice would be to use the get() method, which would allow you
to write data to a buffer or stream rather than a file.

**Comment by Preethamveigas** [comment]
Thanks @theophilusx.
