### ISSUE TITLE
Get Return value Throws Permissions error when Get(..dst) works fine

### ISSUE THREAD

**Issue by vfrank66** [theophilusx/ssh2-sftp-client#232]
I am using .get() and getting an error on permissions

> Error: _get: 550 Can't access file. /xxxx yy.xlsx

```
conts buff = sftpClient.get( `${remoteDir}${x.fileName}`,
        undefined,
        {
          // flags?: string,
          encoding: null
          // handle?: Buffer,
          // mode?: number,
          // autoClose?: boolean,
          // start?: number,
          // end?: number,
        }
);
```

But this successfully downloads a file:

```
let dst = __dirname + 'data.xlsx';
    await sftpClient.get(
      `${remoteDir}${x.fileName}`,
      dst
    );
```

Something in the get with undefined dest, create some other access that .get() with a destination does not, although I am not sure. I looked through this codebase but did not see anything in the options that would lead to different functionality.

**Comment by theophilusx** [comment]
>
>> Error: _get: 550 Can't access file. /xxxx yy.xlsx
>

That error message looks suspicious. I don't use error numbers e.g. 550

What version of node and what platform are you working on?

There have been other reports of issues with the underlying
concat-streams library and incompatibilities with later versions of
node. If I know the version of node you are using, I can try and
reproduce.

-- 
Tim Cross

**Comment by vfrank66** [comment]
Actually this may not be a problem. I left out in my code the fact that I am downloading 55 files with await Promise.all() and this error appears to be an issue with the concurrency. Maybe the sftp server threading?

**Comment by theophilusx** [comment]
Yes, I suspect you will run into issues if your trying to use the same
ssh2-sftp-client object to download multiple files in parallel. The
underlying ssh2 and ssh2-streams library is not written to handle
multplexing of the underlying ssh connection. If you wanted to do this,
you really need to open 55 connections i.e. have 55 ssh2-sftp-client
instances. This is not too hard to do, but my experience has been that
you quickly just flood your local LAN or NIC, so overall throughput may
not be as high as you expect plus you have the additional complexity and
overhead associated with making the network connections. 

Note that if all your doing is downloading files, your better off using
fastGet() rather than get(). The fastGet() method will download the file
contents in concurrent parallel streams, making it much faster on larger
files (for small files, I suspect the overhead of breaking up the data
and re-assembling it over takes the benefits of any parallelism).

The get() method is most useful when you want to do something with the
data, either as part of the download (such as zip/unzipping) or if you
want to then immediately process the data and want it in a buffer. Some
sftp servers also don't support parallel file downloads, in which case
fastGet won't work and you have to use get().

-- 
Tim Cross

**Comment by vfrank66** [comment]
@theophilusx Thank you that is helpful info I did not know ssh2 and ssh2-streams does not handle multplexing. 

Yeah so my use case, which is does work with this library in use with `npm install nest-sftp`, is a AWS Lambda function that connection to sftp downloads all the files to s3. I wanted to use buffers so that I had more control over where to put the file and changing file format after getting the file into the buffer. In my case that is .xlsx to .csv. Flooding the lan would not really be much of a concern for me, although it could happen.

**Comment by theophilusx** [comment]
Am I correct in my understanding that the issue was with trying to use the same connection in parallel, which is not supported by the underlying modules and therefore this issue could now be closed?

**Comment by vfrank66** [comment]
Yes this can be closed
