### ISSUE TITLE
Add ignore pattern in upload/downloadDir method.

### ISSUE THREAD

**Issue by hsh2001** [theophilusx/ssh2-sftp-client#237]
I want ignore some files when using `uploadDir` and `downloadDir` method.

e.g.:
```js
client.uploadDir(buildLocal, buildRemote, '.git/**'); // ignore files in .git directory
```

**Comment by theophilusx** [comment]
That seems like a reasonable requirement. It isn't possible at present,
but happy to take it on board as a feature enhancement. Will look at
implementation when I get time. Pull requests are welcome.

**Comment by hsh2001** [comment]
Nice! But I think we need to update README.md a little bit. I will send the PR to update READme.md first.

**Comment by theophilusx** [comment]
Seung-hyun Hwang <notifications@github.com> writes:

> Nice! But I think we need to update README.md a little bit. I will send the PR to update READme.md first.

You need to update README.org. The README.md is generated from the
README.org file (I can do that once it is updated).


-- 
Tim Cross

**Comment by hsh2001** [comment]
README.org has code highlighting; README.md is not. I make #238 to solve this problem.

**Comment by theophilusx** [comment]
The highlighting issue needs to be fixed in the org to md exporter.

**Comment by theophilusx** [comment]
Have added the ability to filter files/directories in uploadDir/downloadDir in the version-6 branch. will be releasing an updated package once testing is complete.

**Comment by huruji** [comment]
In my opinion，there seems a bug，if I only want to download some file，like `.thrift`, it can't work now. because it filter in root dir，so，how about we should add `dirFilter` and `fileFilter` option.

![image](https://user-images.githubusercontent.com/15937065/113739810-bbcf0e00-9732-11eb-8edf-22000087fa0a.png)

I just download thrift, but the `idls` dir was ignored by the `filter` option.

```js
let rslt = await client.downloadDir(info.projectPath, projectDir, /\.thrift/);
```

![image](https://user-images.githubusercontent.com/15937065/113739954-dd2ffa00-9732-11eb-9b9e-662c82268d29.png)

**Comment by theophilusx** [comment]
I'm not sure I understand exactly what you are trying to do (maybe a
language issue?). The filter is used to exclude things it matches. Your
filter matches the files in idls, so there are no files to download from
that directory. The filter is not just applied to the root directory. It
is applied to all the entries in every directory (downloadDir recurses
into all sub-directories). It looks like idls was ignored because all
the files in that directory match your filter, so no files were
downloaded from that directory. 

What version of ssh2-sftp-cleint are you using?
What version of node are you using?
What platform is the client running on?

The filter is a regular expression - it can be as sophisticated or as
simple as you want. Your filter is very simple and it is matching all
files or directories with '.thrift' in the name. If you want some files
with thrift in the name, you need to refine your regexp filter.
