### ISSUE TITLE
SSH-2.0 server - can't put file

### ISSUE THREAD

**Issue by eagress** [theophilusx/ssh2-sftp-client#242]
Looking at the remote ident, this code works well with a remote SSH-2.0 Cerberus server. It fails every time trying to go to another server that also uses SSH-2.0.

I've tried using put and fastPut. I've enabled every algorithm type available. It's made no difference.

I enabled debug and captured everything in the attached log (send-failure-debug-log.txt).

The code node javascript is attached (code.txt).

[code.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4783161/code.txt)

[send-failure-debug-log.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4783144/send-failure-debug-log.txt)

Any suggestions are appreciated. Sorry the code is a bit rough. I've been trying everything I could think of to no avail.

**Comment by theophilusx** [comment]
It is a little hard to tell frm your code, but from the debug log, you appear to be connecting fine. I'm not sure you need all the algorithm settings and I would try without. The log seems to indicate that a bad value is being passed to the exists() method. This might be a bug, I will need to look closer. It is a little unusual to do a exists('./') as that is the same as exists('.'), which is asking if the current directory is a directory (which of course it is). To handle different platforms, the interpretation of '.' and '..' is a litle complicated and what I guess might be happening is that './' is being translated to './/', which is fine on some servers and causes an error on others. 

Looking at your code, you would be far better off using async/await rather than trying to wrap things in another promise. I am attaching a version of your code which uses async/await (untested) as an example. I ahve also reversed the calls to cwd() and exists().  

Note that in your final code, I would not have a function called sendFile which also creates a connection. I would separate these two actions. You amy want to send more than one file and you don't want to create a new connection for each (it is the slowest operation). Instead, you would create a connection and then pass that into your sendFile function.  Also, be wary about using the path module in your client. This can cause all sorts of problems when your client and server are different platforms e.g. client is windows and server is unix/linux. I've seen people get into strife when they build the remote path in the client using path and end up with something like \dir1\dir2\file.txt which is a legit FILENAME (no directories) under unix and then they look for a file in the dir 'dir2' and no file is there - what they have is a file in cwd with the name \dir1\dir2\file.txt.

Finally, I would be careful about using ECM6 module syntax with node. While node is now supporting ES6 modules, I've run into problems with some node versions. I've found it much safer to stick to the commonJS 'require' syntax for node and use the ES6 fror browsers (likely less of an issue for more recent node versions). 
[fastput.js.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4783906/fastput.js.txt)

**Comment by eagress** [comment]
Thank you for the amazingly quick response and the example code.

I refactored my code based on your suggestions. Stopped using so many promises. Moved the connect outside the loop that transfers multiple files. Got rid of the excess algorithms and left only ssh-dss which I need to get connected.

The company owning the server set up a test account for me to use. I ran the new code and it worked great.

Then we tried to upload the file that had the problem into the same folder that had not worked. It still does not work. It does use different credentials and it is a different folder than the test user. But, we can upload to it with FileZilla. Many other people upload to that same folder every day. Please take one more look at the newest code and the latest log to see if you can pinpoint anything.

There is a very obvious error message from fastPut:
"msg": "Bad path: / parent not exist",

I don't know why this happens because the slash (/) folder definitely exists on the server.

Thank you again.
[code-v2.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4789003/code-v2.txt)
[send-fail-log-2.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4789005/send-fail-log-2.txt)

**Comment by theophilusx** [comment]
OK, I think I may have found the issue. The problem only occurs when
trying to write to the root directory e.g. '/'. I'm testing a fix and
will let you know when it is ready.

**Comment by eagress** [comment]
Tim, that's wonderful news. I'll be happy to try it when it's ready.

Sent from my Verizon, Samsung Galaxy smartphone

________________________________

**Comment by theophilusx** [comment]
I have updated the master branch in the repository with changes that
should fix the error you were seeing. Please try using the code from the
repository and let me know if it works. If all works, I'll release a new
version.

**Comment by eagress** [comment]
I'll be able to try it later tomorrow. I will let you know what happens.

Sent from my Verizon, Samsung Galaxy smartphone

________________________________

**Comment by eagress** [comment]
Good news. We were able to send a file today. We only had one file to try, but it worked and it had never worked before. We'll be able to try multiple files tomorrow. I think this issue might be fixed. I'll know for certain after tomorrow's run.

**Comment by theophilusx** [comment]
OK, that is good news. I will wait until I hear from you and if all goes
well, will bundle up and release a new minor version.

Tim

-- 
Tim Cross

**Comment by eagress** [comment]
Tim, everything worked yesterday. This is fixed. You've been a tremendous help. Thank you very much. I don't know if I should close this, so I'll leave that to you.

**Comment by theophilusx** [comment]
Thanks for letting me know. Maintaining this stuff is much easier when
you have users willing to engage. I'll close the job once I have
released a new version.

**Comment by theophilusx** [comment]
Published version 5.1.3 with root dir fix.
