### ISSUE TITLE
Guidance on connection lifecycle

### ISSUE THREAD

**Issue by ncjones** [theophilusx/ssh2-sftp-client#246]
Please help me understand how to reliably manage connections in a long-running process that integrates with an FTP server.

I have read through the docs and some of the previous issues about connection error handling (https://github.com/theophilusx/ssh2-sftp-client/issues/217 and 
https://github.com/theophilusx/ssh2-sftp-client/issues/226) but it's still not clear to me what is the recommended usage pattern for managing the SFTP connections in a long-running process.

In particular the following comment makes me nervous: 
>"if remote server does not raise either an error signal or a close signal, hangs would still be possible. There isn't much I can do in that situation - if the client doens't recieve any signal to indicate the connection has closed or an error has occured, it can't do much."

 -- _Originally posted by @theophilusx in https://github.com/theophilusx/ssh2-sftp-client/issues/217#issuecomment-598744313_

Ultimately I would like to know if clients should be treated as ephemeral or if they should be reused and also how to ensure both a) severed connections do not break my application and b) reconnecting does not create memory leaks.

**Should clients be ephemeral?**
 
Should I create a new client every time I interact with the remote server? If so, is calling "end" before discarding the client enough to prevent memory leaks?

**Should clients be shared?**

Should I reuse the same client every time I interact with the remote server? If a client is shared between operations, when should "connect" and "end" be invoked? What should I do if a server connection was severed ?

**Comment by theophilusx** [comment]
It is fine to use a connection for multiple requests provided the
requests are serialised i.e. don't try to download a second file until
the first one has completed. However, it is a bad idea to try an open a
connection and keep it open for extended periods, especially if there is
large amounts of idle time. Connections will timeout if left idle for
extended periods of time, plus there is an increased likelihood of 'lost
connections' when a connection is left idle for extended periods.

There is a balance you need to find between making connections too
frequently and leaving them idle too long. The correct balance depends
on many factors, including stability of the network, reliability of
remote server, types of firewalls in place etc. Creating a connection is
a relatively slow process, so you don't want to make a connection for
every request. However, you also don't want to generate a connection and
keep it open for hours at a time. The right balance depends on your
application. If you have a long running process, I would not expect to
start the process, open a connection and then keep it open until your
process ends unless that process was constantly using the connection to
transfer data. I would also be careful about opening multiple
connections at the same time. Many remote servers have connection
limits, especially if you try to open multiple connections very quickly.

Memory leaks are not typically an issue due to the way garbage
collection works in node. However, failing to call end on a connection
can result in further connections being refused because you have reach
the limit for allowed connections by the remote server. The remote
server does not know a connection has ended until you issue an 'end'
command or a connection timeout occurs. These days, I recommend using
async/await rather than simple promise chains because you can wrap
things in a try block with a finally clause to ensure 'end' is called.

The current version of the client now includes a global error handler,
which has addressed most, if not all, of the previous issues with
connections failing without the client being aware of them. There may
still be some edge cases, but there are none I am currently aware of and
all recent issues have been due to failures in client code to handle
error signals correctly. 

In my use of the library, I will typically 'bundle' up the SFTP work
into a 'block' of actions, generate a connection at the beginning,
perform whatever requests are necessary and then end the connection.

**Comment by ncjones** [comment]
Thank you for the in-depth reply. This is very helpful. I think it would be worth having something like this in the usage docs.
