### ISSUE TITLE
sftp hangs after sending approximately 200 files

### ISSUE THREAD

**Issue by kvelaro** [theophilusx/ssh2-sftp-client#253]
Someone, please help.

I have following code and have more than 500 files. When I run this function, it hangs after ~200 files transferred. Between these I have ECONNRESET, which is not catchable.

Could someone give me advice?

`function sendXML() {
    let currentDirectory = path.dirname(__dirname)
    let directoryPath = currentDirectory + "/web/xmls"

    fs.readdirSync(directoryPath).forEach(file => {
        let readStream = fs.createReadStream(directoryPath + '/' + file)
        readStream.on('open', function () {
            let sftp = new Client();
            sftp.connect({
                host: config.minimaxConnection.host,
                port: config.minimaxConnection.port,
                username: config.minimaxConnection.user,
                password: config.minimaxConnection.password,
                debug: console.info
            })
            .then(() => {
                return sftp.put(readStream, '/traffic/' + file)
            }).then(() => {
                console.log('File:' + file + ' transferred')
                // fs.unlink(directoryPath + '/' + file, err => {
                //     if(err) {
                //         console.log(err)
                //         notify.send(err)
                        // fn(err)
                //     }
                // })
                return sftp.end()
            })
            .catch(err => {
                console.log(err)
                notify.send(err)
            })
        })
        readStream.on('error', function(err) {
            console.log(err)
            notify.send(err)
            throw err
        });
    })
}`

**Comment by AndrewLane** [comment]
Would you be better off only connecting once?  That is, put the code that establishes the connection outside of your forEach loop?

**Comment by theophilusx** [comment]
This is almost certainly because of either sftp server or firewall
limits being triggered by the large number of short connections. Most
sftp servers and many firewalls have rate limiting protections to
prevent connection flooding, DoS attacks and other security threats.

When you connect to an SFTP server, the initial connection is
unauthenticated. The two ends of the connection negotiate the
authentication and setup keys, ciphers etc. This takes a few round trips
between client and server. Nearly all sftp servers have a limit on the
number of concurrent unauthenticated connections (often around 10). Once
you pass the first limit, the server begins to randomly drop connections
until another limit is reached, at which point, all connections are
dropped. This is one thing which can generate the error you are seeing.

You need to do one of two things -

- Increase delay between making connections.
- Make fewer connections.

The first thing I would try is to move your code which establishes the
connection outside your loop which uploads the files. Connections are
the slowest part of the protocol (because of the negotiation outlined
above). There is no need to make a separate connection for each upload.
However, you do need to ensure that each upload is completed before you
start the next upload i.e. you can only upload one file at a time over a
connection.

For this type of application, I would recommend using async/await rather
than promise chaining. It is easier to work with when dealing with loops
where you need to wait for a process to complete.

**Comment by kvelaro** [comment]
Thank you! It was actually firewall
