### ISSUE TITLE
Download a file from SFTP --> Node JS --> Client browser Through File Stream API

### ISSUE THREAD

**Issue by Arunachalam** [theophilusx/ssh2-sftp-client#254]
**How to download a file from SFTP --> Node JS --> Client browser Through File Stream & don't store the download file in node js application?**

We migrated this ssh2-sftp-client module from 2.2 to 5.21 version in the application, after facing the issue of download a file from SFTP.

Noticed the get method parameter & new approach has upgraded in the latest version.
**get(path, dst, options) ==> String|Stream|Buffer**

1) string or stream - **Storing the file content in Node JS, if go with this parameter.**

2) Undefined or Buffer - **get the buffer data, if go with this parameter, will get the performance issue on sever, when upload big size data by concurrent users.**

Please help & provide ur inputs.

**Comment by theophilusx** [comment]
I'm not clear or do not understand what it is your trying to do. If your downloading a file, it has to be stored either in memory or on the filesystem where node is running before it can be sent to a browser (using some other mechanism). I guess you could possibly do something with a socket, in which case, you could just pipe the stream into the socket?

Note also that in version 2.x, the method just used a stream. What has changed is that instead of returning a stream, it accepts the stream or a string or a buffer as the destination. So instead of taking the stream returned and doing something with it, you can just create the stream, pass it to get() and do whatever you want with it i.e. pipe it to a socket connected to the browser.

**Comment by Arunachalam** [comment]
Thanks theophilusx for replying the answer.

Let explain our query briefly here.

1) When User hit a download the attachment API, then call goes to Node JS application.
2) Connecting the SFTP server in node JS application & provide absolute path to get the file from SFTP server.

Previous version 2.x is not saving the file content in node server & returning as a stream & we used this code stream.pipe(APIresponse); to pass the same stream data of SFTP without manipulate to the API response. Able to download the file content through stream & not storing big chunk data in memory & on application server.

But New Version 5.x, has be to stored either in memory(buffer data) or on app system(stream data). 

//Stream (store the remote file on app system, then download a file from app system to client browser through read stream. & here double process to download a file & delete a file from app system, once user done the download file.)
this.sftpClient.get(path, dst).then((stream) => {	
	const readStream = **rm.fs.createReadStream(stream.path);**
	return readStream
}, (error) => {
	
});

//Buffer (Need to be wait in client side for collect all buffer data from SFTP server & will get API performance issue, when upload  big size content by concurrent users, because the buffer data is storing in memory, until action is completed).

this.sftpClient.get(path).then((buffer) => {	
	
}, (error) => {
	
});

https://medium.com/javascript-in-plain-english/how-to-read-files-with-buffer-stream-in-node-js-d77de6ae6b49


Please share the example codes us(download a file through stream API from sftp server without storing on app system & don't store full buffer data in memory also).

**Comment by theophilusx** [comment]
In version 2.x, a local (node) stream is still created. The difference
with v5.x is that you now can pass in the stream destination rather than
receiving the stream and having to pipe it into a stream manually.

So, in your situation, you need to create the stream before calling
get() and pass that stream as input to the get() method. This will
provide the same outcome as the 2.x version (in 2.x, the creation of the
stream was inside get(), you now creating it outside get() and passing
it in).

**Comment by alanhg** [comment]
if use fs.createWriteStream().

It must pass in a path, then there will still be local files.

**Comment by theophilusx** [comment]
I'm having trouble understanding what you expect to happen here. 

Yes, if you use fs.createWriteStream() it will create a write stream on
the file system associated with the process running the
fs.createWriteStream() call. 

However, you don't have to use fs.createWriteStream. The writeStream
object can come from anywhere/anything - for example, you might have
some code or use a library which creates a write stream on a remote
system and passes that back to your application which in turn passes it
to ssh2-sftp-client. 

Alternatively, you might have a web server which returns a write stream
and you would just pass that into the call to get() to stream the remote
file directly into that stream. 

Or you could have some other network service, like a database
connection, which is able to create a write stream which will write all
the data sent to it into a database table

or .....

There are many ways to create a write stream. The ssh2-sftp-client
library doesn't care where the stream comes from - it just has to be a
node compliant write stream. Basically, you are passing in the end of a
hose. The ssh2-sftp.client library doesn't care where that hose goes -
it just takes the end you pass it, connects it to the read stream from
the sftp server and lets all the data flow into it. How that hose is
created or where the far end data output is does not matter to
ssh2-sftp-client.
