### ISSUE TITLE
Not working on Linux when trying to connect to a Windows SFTP server

### ISSUE THREAD

**Issue by ferlauf** [theophilusx/ssh2-sftp-client#257]
I'm running the code on my Linux machine and trying to connect to a Windows machine where the SFTP server is running.

There are several issues:
- Wrong remote platform detection, so it always returns `unix`. This is in index.js, line #165: `if (absPath.startsWith('/')) {`, since `absPath` will always return the paths with `/` (in my case this is `/C:/Users/api`)
- If server OS is windows, then all the occurrences of the NodeJs `path`s methods should be replaced with `path.win32`.

**Comment by theophilusx** [comment]
Thanks for the info. I'm not a windows user at all and all my attempts
to get a reliable sftp server working on windows have failed. If I make
the necessary changes to remote platform detection and OS path, are you
willing to test?

Also, do you know if the windows sftp server is running 'native' or is
this a WSL sftp server? I suspect this might make a difference and could
mean the detection and path handling is more complex.

**Comment by ferlauf** [comment]
Thanks for the reply. Sure, I'm willing to test! 
Yes, it's a native OpenSSH Server installed as an optional feature in Windows.

**Comment by theophilusx** [comment]
OK, I re-installed my windows VM yesterday and this time was able to
successfully setup openSSH server, so I can now test as well.

I've created a new branch and started fixing - quite a few of the tests
are failing, so probably a bit more work needed than just the platform
detection and path fixes. Will let you know when it is progressed
sufficiently to warrant some testing.

**Comment by ferlauf** [comment]
Thank you!

**Comment by theophilusx** [comment]
This issue has been addressed in the current master branch. All tests appear to now be passing. Please try it out and see if your issues have been resolved. 

The previous version path handling was completely wrong. The new version now assumes that win32 based servers comply with the 'nix' path style. This is the case with openSSH on windows as well as other windws sftp servers I was able to access for quick testing. Some commands do behave slightly differently or don't really work because of win32 platform limitations e.g. chmod and group/other permissions, realpath returns a path even if it does not exist (returns empty path on Linux) etc. 

Also made some changes to the event handlers. It seems win32 servers issue an ECONNRESET error event even after correct call to end(). The new management of events works better, but it does mean that if you re-use a SftpClient object for multiple connections, you can run into problems (that is, connecting, calling end and then re-connecting).

**Comment by ferlauf** [comment]
I can confirm that it's working now!

`CLIENT[sftp]: SFTP connection established`
`CLIENT[sftp]: Connected - do stage 2 setup`
`CLIENT[sftp]: absPath = /C:/Users/api`
`CLIENT[sftp]: remote platform win32 like`
`CLIENT[sftp]: Connection and setup completed successfully`

**Comment by theophilusx** [comment]
Thanks for checking. Will release v5.3.0 with the fixes.

**Comment by jayaganeshk** [comment]
@ferlauf 
when am trying to copy to custom windows drive am not able to. For example to F:/documents.
Is it working for you? do you have any examples?
