### ISSUE TITLE
A scheduled Cron Job(connect to SFTP) not working in Firebase.

### ISSUE THREAD

**Issue by devmanateam** [theophilusx/ssh2-sftp-client#258]
Hello, it' s my pleasure to use this module in my project.
that is to currently upload a bunch of files to an SFTP server through Firebase cloud functions.
i made two functions(one is cronjob, other is normal function) to connect to SFTP in cloud functions.
i deployed that to Firebase and the cron job is running every 1 min.
normal function is working on Postman.
only cronjob not working. i got the following error.

https://prnt.sc/u5xo83
Timer.processTimers (timers.js:223:10) code: 'ERR_GENERIC_CLIENT', custom: true }
at Client.emit (events.js:198:13)
 at listOnTimeout (timers.js:263:5) 
 at listOnTimeout (timers.js:263:5) 
at Object.onceWrapper (events.js:286:20)
at ontimeout (timers.js:436:11) 
at Client.connectErrorListener (/workspace/node_modules/ssh2-sftp-client/src/index.js:98:21)
at Timeout._onTimeout (/workspace/node_modules/ssh2/lib/client.js:697:14)
at Object.formatError (/workspace/node_modules/ssh2-sftp-client/src/utils.js:62:18)
catch err: { Error: connect: Timed out while waiting for handshake after 2 attempts
at Client.EventEmitter.emit (domain.js:448:20)

could you help me?

**Comment by theophilusx** [comment]
This error means that the client was unable to connect and authenticate
with the remote server. This typically means you have some sort of
network problem.

You might try using a CLI sftp command (like openSSH sftp command) from your
remote host to the remote server with debug flags turned on to possibly
get more details. Might also be worth checking the remote sftp server
logs if you have access. Could be a missing firewall rule, bad network
connection or any of a number of other network issues.

**Comment by theophilusx** [comment]
Also meant to mention not to overlook the difference between the cronjob
environment and normal login environments. Cronjobs are not a 'normal'
process and do not run inside a normal login environment. If your code
is relying on environment specific variables, it could be a problem as
these variables will not be defined at run time. Might be worth adding
some debug console.log lines to your cronjob script to see that values
are what you think they are (don't forget to add a mailto setting for
the cronjob so that you get sent the output).

**Comment by devmanateam** [comment]
Thanks, theophilusx, i found the solution.
i found the solution in Firebase hosting configuration and functions.
Thanks again.
