### ISSUE TITLE
Does not emit event to disconnected network while processing files in the sftp.get method

### ISSUE THREAD

**Issue by diegomjv** [theophilusx/ssh2-sftp-client#260]
I'm trying to capture a network disconnection event, using the sftp.get method, but I can't.
It has a list of 300 files to make sftp.get and sometimes, when the network fell in the middle of processing one of these files, it gets stuck, doesn’t hold forward and doesn’t even issue an error, I put several "sftp.on" but I was not able to capture the error, nor to deal with it. Can you help me?

`let Client = require('ssh2-sftp-client');
let File = require('./file');
const sftp = new Client();

const config = {
  host: **
  port: **
  username: *
  password: **
};

const processFiles = async (sftp) => {

  console.log('Try Connection SFTP');
  await sftp.connect(config);
  console.log('Connected SFTP OK');
  const remotePath = '/upload/atendimentos';
  const dataList = await sftp.list(remotePath);
  for (let index = 0; index < dataList.length; index++) {
    const file = File.buildFile(dataList[index].name, remotePath);
    file.buffer = await sftp.get(file.path).catch(err => logger.error(`Get File error ${err.message}`));
    console.log(`File ${file.name} downloaded`);
  }
}

const doSftp = async () => {

  try {
    await processFiles(sftp);    
  } catch (err) {
    console.error(err);
  } finally {
    sftp.end().catch(err => console.error(err));
  }
};

doSftp();
`
In this line: file.buffer = `await sftp.get(file.path).catch(err => logger.error(Get File error ${err.message}));`
If the connection goes down here, at the time of executing this line, it cannot proceed and neither emits an error

**Comment by theophilusx** [comment]
What version of node?
what version of ssh2-sftp-client?
what platform is the client on?
what platform is the sftp server running on?
how long are you waiting before deciding the connection has
become stuck?

I need the above info in order to help.

I do notice your mixing promise chains and async/await. While I don't
think this is your issue, I have seen unexpected behaviour when doing
this. Far better to use one or the other, but not mix the two. Rather
than

file.buffer = await sftp.get(file.path).catch(err => logger.error(`Get File error ${err.message}`));

you should do something like

try {
  ...
  file.buffer = await sftp.get(file.path);
  console.log(....);
} catch (err) {
  ....
}

Also, are you doing any post-download processing with the file e.g.
using the data in that 'file' object your creating? If not, you should
use fastGet rather than just get() or if your sftp server does not
support fastGet(), then get with filename as 2nd argument. If you are
using the downloaded data in some post-download processing, streams are
more efficient than buffers. The File.build method could open a stream
and you could pass that in e.g.

await sftp.get(file.path, file.stream);

The remote sftp server uses streams. so when your using buffers, your
adding another layer (stream -> buffer conversion), plus buffers will
result in more memory usage. Buffers are good when you have small files
and you need to do something with the buffer of data and need the input
to what your doing to come from buffers. Otherwise, streams are better
and if all your doing is downloading the data, filenames are best.

You state your adding listeners with the on() method. What events are
you adding listeners to? If your doing something like

sftp.on('error', (err) => {
  console.error(err.message);
}

and that listener is never firing, it means that no error has been
raised by ssh2/ssh2-streams. If this is the case, there is not a lot I
can suggest. I'm surprised that at the very least you don't get some
sort of timeout error eventually. I would try adding some listeners to
some of the other events in case one of those is firing (just as a
check).

You can also try adding a debug function and see what you get. If you
add

{
  username: *****
  password: *****
  debug: (msg) {
    console.error(msg);
  }
}

to the connect object, you will get lots of debug data that might
provide more info to work with. If you want to filter to just debug info
from ssh2-sftp-client, you can do something like

debug: (msg)
  if (msg.startsWith('CLIENT')) {
    console.error(msg);
  }

to filter on debug messages only from ssh2-sftp-client and exclude those
from ssh2/ssh2-streams.

**Comment by theophilusx** [comment]
What is the status of this issue now?

**Comment by theophilusx** [comment]
Closing as stale issue with no further updates.
