### ISSUE TITLE
Question: when listing a directory is there a way to filter the results based on date time?

### ISSUE THREAD

**Issue by aefox** [theophilusx/ssh2-sftp-client#263]
Hello,

I have a directory which will grow indefinitely in terms of files being added to it. I am interested in recurrently getting the latest added files from that directory, lets say beginning of each hour for the past hour. Is there a way to list a directory structure and also filter by date time?

Any ideas into achieving this will be greatly appreciated.

**Comment by theophilusx** [comment]
The list() method will return a list of all the files and directories
within a directory and that information includes the modifyTime and
accessTime for each entry. You could filter the results to extract only
those entries where the modifyTime was after the last time you checked.
The returned value is an array of objects, so this is trivial to do with
an array.filter() or similar.

I can see some problems with your approach (based on past experience
where I tried to do similar). You should check to see if the remote OS
file system has any limits on entries. While less common these days,
some file systems (like Linux ext3) have a limit on the number of inodes
in a directory (ext4 and other more modern file systems don't have this
limit). The other problem is that if the number of entries just keeps
growing, the listing and filtering will become slower and slower.

However, the biggest issue you are likely to have is that modifyTime and
accessTime are notoriously unreliable mechanisms for doing this type of
thing. For example, a file could be copied across to the sftp server
using the -p flag to preserve existing modify times, making it appear to
have been added earlier than it actually was. Sometimes, other programs,
like backup programs might change the values etc.

There are 3 ways I've used in a similar situation which I found works
better than relying on file time stamps.

1. Move the file after download. You could create a directory on the
remote sftp server called 'done' (or whatever) and after downloading the
file, move it to that directory using the rename() method. You then only
need to do a list() call and download all the files listed, moving them
to the done directory once successfully downloaded. Means that your
unlikely to 'miss' files due to a failure part way through. 

2. Add time stamp information to the file name e.g.
my-data-2020-09-16T23:14:00.dat and then use the regexp filter option of list()
to only return files which match a specific regexp and then download
those files. Downside is that if someone adds a file later with an
earlier timestamp in the name, it may be missed because you think it was
done in an earlier run or if you have a network failure part way
through, you need some way of sorting out where you got to before the
failure etc. Of course, you also need access to whatever creates the
remote files or a way to get whomever is responsible to change their
system to add the timestamp info to the file names. 

3. Maintain a checksum for each file as it is downloaded then perform a
checksum on each file as you download it and compare to the stored one
and only save the file if they differ as the different checksums mean
the contents have changed. This is the least efficient method, but works
weill when data might change in a file and you cannot rely on file
timestamps. I used this for an application where all the timestamps on
files were changed, but only a few of them actually had changed data
(basically, the remote application updated data in one directory, then
copied all the files across to the sftp server, including files which
had not been modified. Because it was a copy, all the modify times
changed regardless of whether the data had changed). Downside is that
your downloading all the files every time, which may be inefficient or
slow depending on the file sizes. Things can be improved with a
combination of approaches i.e. generous filtering based on modify time
and then more specific filtering based on checksum of the smaller group.

For your situation, I would consider 1 or 2, but if neither are
possible, then see if using a filter on modifyTime works for you and use
that. If it doesn't, then look at the checksum approach.

Depending on level of access and application, sometimes you can simplify
things by changing the remote logic of the system creating the files in
the remote sftp server. For example, having a remote script which
removes/cleans up old files on the remote server after a certain amount
of time etc.
