### ISSUE TITLE
support forwardOut

### ISSUE THREAD

**Issue by keller35** [theophilusx/ssh2-sftp-client#264]
I'd like to post a pr about `forwardOut` supported by ssh2. It's useful when a jump server is needed to access the target machine.
And The code is something like this:
```js
  /**
   * @async
   *
   * forwardOut supported by ssh2
   * https://github.com/mscdex/ssh2#connection-hopping
   *
   * @param {string} srcIP - source ip
   * @param {integer} srcPort - source port
   * @param {string} dstIP - destination ip
   * @param {integer} dstPort - destination port
   *
   * @return {Promise} which will resolve to an sftp client object
   *
   */
  forwardOut(...params) {
    this.debugMsg(`forwardOut`);
    return new Promise((resolve, reject) => {
      this.client.forwardOut(...params, (err, stream) => {
        if (err) return reject(err);
        resolve(stream);
      });
    });
  }
```
If this feature is added, the unit test needs to add test code about the hopper, including the hopper's IP and port.
Please reply to let me know if this will make a difference.

**Comment by theophilusx** [comment]
While I can understand the objective, I'm not convinced ssh2-sftp-client
is the right place to put this functionality and if it is, whether your
proposed API is sufficient. It could be that this is functionality
better suited to a separate module that perhaps depends on ssh2-sftp-client?

The design needs to be very careful when you start mixing promises and
event models and the API has to be very clear about who is responsible
for created objects and managing events etc. If you look at all the
existing methods provided by ssh2-sftp-client, most of the time the code
using the module never has to worry about managing event handlers and
streams are all ones created and managed by the client code etc. In the
pseudo example you provide, it isn't clear who is responsible for
managing events on the stream or who is responsible for managing that
stream object returned. It also isn't clear exactly how forwardOut will
interact with the rest of ssh2-sftp-client i.e. how do you actually
manage a put(), get(), fastPut(), fastGet(), append(), dirUpload() etc
in conjunction with forwardOut()? How do you actually use that stream
which forwardOut() returns? Would it be better if forwardOut returns a
new object which provides the same API as ssh2-sftp-client so that code
can be the same? If so, should this actually be some sort of separate
utility module and if so, how do we structure things to minimise code
duplication and ensure on-going maintenance does not become an issue?

Is even forwardOut() a good idea? Might a better approach be to look at
extending the connect() method to allow specification of a jump server
and have that method do all the necessary setup, returning an object
with the same API as ssh2-sftp-client? (and modifying end() to cleanup
correctly etc). What impact does all of this have on error handling? 

I think the proposed functionality could be a good addition. However,
this is a non-trivial addition and I would need to be convinced it is an
addition which does not add more complexity to the module than the
benefits it provides and won't make maintenance too much harder. The
implementation needs a lot more fleshing out.

I'm happy to try and work with you to implement this and will consider
any PR, but we need to maintain API consistency. Changes to the API will
be considered, but need good justification. Any PR needs to come with
full set of tests and documentation (note that the README.org file is
the master README and documentation file - the README.md file is
generated from the README.org file, so don't edit README.md). 

Other things which need to be considered -

- Platform support: Right now, ssh2-sftp-client can be run on Linux, Mac
  or windows and can interact with servers on Linux, Mac  or Windows.
  Adding a jump server can multiply this complexity as the jump server
  could be any of the 3 supported platforms and does not need to be the
  same as either the client or server.

- Error handling: There is now a new failure point. Handling errors,
  especially event errors, inside a Promise based API is very difficult.
  Consider a get request going through the jump server. How is the
  promise rejected when an error occurs at that point and how do we
  ensure the reported error makes it clear where the failure occurred?
  What happens when there is a failure in the jump server which occurs
  in-between other calls (Promises)? Who/how is that error handled and
  how is it reported back to the client?

- Testing: I'm a little concerned regarding testing. It has been hard
  enough to get good test environments with just single end points. I
  guess we could do something with virtual machines, but again I'm a
  little concerned regarding the additional complexity and potential
  impact this could have for on-going maintenance.

Sorry if all of this sounds too discouraging. However, I think it is
important to recognise this is not a trivial addition and correct
implementation might take significant effort. If your still keen to work
on it, please do and let me know how you go. Happy to look at anything
you do and assist when I can.

**Comment by keller35** [comment]
@theophilusx Thank you for your response.

After your tip, I found that forwardOut is really not suitable to be added to ssh2-sftp-client. using ssh2 and ssh2-sftp-client in combination, it will work well.

I have some thoughts on what you said about unit testing. The current unit testing relies on real machines, which can make it difficult to ensure a consistent environment. So, the virtual machine you mentioned is a solution. However, ssh2 itself supports ssh server and you can create ssh server by ssh2 to simulate the environment.

Do you think this is feasible?I can try to implement this.

**Comment by theophilusx** [comment]
I have actually started work on an sftp server using ssh2/ssh2-streams.
While setting up a basic sftp environment is pretty straight-forward for
basic sftp (especially openSSH server), the biggest challenge when it
comes to testing is being able to generate the specific error you want
from the server in order to verify the client handles it correctly.
Having a sftp server in JS would allow easy addition of server level
responses to generate the exact errors etc you want to test against.
Having such a 'customizable' server for testing would also allow
implementation of CI type testing, which would be a good step forward.

However, implementing a compliant sftp server using ssh2/ssh2-streams is
actually a fair bit of work. Even with the support provided by ssh2, the
amount of work required is non-trivial. Easy to do something
'specialised', but fully compliant sftp server (which is what you would
need for testing), is non-trivial.

So, good idea, but fair bit of work. I've been too busy to get back to
my version.
