### ISSUE TITLE
how to pass start position in bytes from where download should begin using get method?

### ISSUE THREAD

**Issue by azamsolix** [theophilusx/ssh2-sftp-client#269]
Hi sir,
        Does this npm provides option to pass start position in bytes from where download should begin.
So,It would be useful to resume download from it fails
Thanks 
Azam

**Comment by theophilusx** [comment]
No, there is no facility to resume downloads or commence downloads from
a specific byte offset.

**Comment by azamsolix** [comment]
Okay.Is there anyway i can implement this as i need this feature.Could you please help me with this?

**Comment by theophilusx** [comment]
This would be a non-trivial piece of work. I'm not sure if you would be
better off implementing this just using ssh2/ssh2-streams directly or
ssh2-sftp-client.

The get() and put() methods do allow passing in an optional object
containing properties which will be applied to the remote
readStream/writeStream object. Theoretically, you should be able to pass
in a byte offset which will determine the offset at which to start
reading. You would probably have to ensure the encoding is not utf-8 i.e
is binary. You would also need some way to record/track where
download/upload got to before stopping in order to know where to set the
offset to and you would need to implement some mechanism to re-assemble
the 'parts', plus you may need to add additional checking to verify the
file has not been modified between attempts e.g. some sort of checksum
check.

At this time, I do not have the resources available to assist with this
work, sorry. I would be happy to consider any pull requests, but they
must also include documentation and full test suits.

**Comment by azamsolix** [comment]
Hi,
Thank you so much sir for your reply.
you said"i should be able to pass
in a byte offset which will determine the offset at which to start
reading."So, could you please help me with sample code to pass byte offset.
I have already implemented logic to get byte offset.
I am only having problem where to pass in get method.
So,please sir help me with sample code.
Waiting for your reply sir.
Thank you
Azam

**Comment by theophilusx** [comment]
The get() and put() methods both support an optional 'options' object.
This options object is passed to the underlying call to createReadStream
(for get()) and createWiteStream() for put(). See the documentation for
sftpStreams at

https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md

So, at a very high level, something like


const sftp = new SftpClient();
await sftp.connect(...);
...
await sftp.get('/some/path', dst, {start: 2347});

may start downloading file /some/path to dst starting from byte 2347.
However, I have never tried this and there are likely to be a number of
additional complications you will need to deal with. You may need to go
through the get()/put() source code as well as the code and
documentation for the sftpstreams module (link above)i to understand how
this all works and the complex interactions within a mix of promise and
event based APIs.

While I suspect getting the basic mechanics to work won't be too hard,
there is considerable hidden complexity in what your trying to do and
implementing it in a robust manner is going to be non-trivial.
