### ISSUE TITLE
I get following error 'e.isDirectory is not a function\n at SftpClient.uploadDir'

### ISSUE THREAD

**Issue by MuhammedParlak** [theophilusx/ssh2-sftp-client#271]
When i give a remote path if not exists, that will be create and all files from the local path is read correctly. 
After debug i saw that in the for loop the `e.isDirectory()` is undefined and this execute the error.
Can someone help me why this is undefined.

**Comment by theophilusx** [comment]
Almost impossible to provide advice if you don't provide any example
code. However, 99% of the time when I've seen people report this error
it is because they are not using promises or async/await correctly and
are trying to query the value before it is returned by the call.

If you want more specific assistance, you need to provide a minimal code
example which reproduces the error you are seeing.

**Comment by MuhammedParlak** [comment]
I found the error. The Error was that my node was not updated. this led to readdirSync returning string instead of object. 
e was therefore a string array and not Dirent array.
