### ISSUE TITLE
Connect hangs on second call when sftp server isn't available

### ISSUE THREAD

**Issue by fkoehler42** [theophilusx/ssh2-sftp-client#273]
**ssh2 version:** 5.3.0-1
**Node version:** 12.14.x (through electron v9.3.2)

I recently upgraded the module from v5.1.2 to v5.3.1 and I'm facing an issue since then. My use case is as follow:

I wanna upload a directory and retry indefinitely until either it succeeds or the user clicks on a button to stop. To do so, I call the following function, wait for its completion then execute it again if the upload failed and the user hasn't clicked on the stop button.
 
```
const sftpConfig = {
    host: '192.168.x.x',
    port: 22,
    username: 'foo',
    password: 'bar',
    retries: 0,
    debug: (msg) => fsPromises.appendFile('./sftp-debug.log', `${msg}\n`, 'utf-8'),
}

export const uploadDir = (srcDir, destDir) => {
    fsPromises.appendFile('./sftp-debug.log', 'New attempt\n', 'utf-8'); // DEBUG
    return sftp.connect(sftpConfig)
        .then(() => sftp.uploadDir(srcDir, destDir))
        .finally(() => {
            fsPromises.appendFile('./sftp-debug.log', 'Finally\n', 'utf-8'); // DEBUG
            return sftp.end();
        });
};
```

Calling this function in a loop while the sftp server is down produces the following logs on v5.1.x or v5.2.x:

```
New attempt
Debugging turned on
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Connection attempt 1 failed. Trying again.
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Exhausted all connection attempts. Giving up
Finally
CLIENT[sftp]: Removing listener from error
New attempt
Debugging turned on
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Connection attempt 1 failed. Trying again.
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Exhausted all connection attempts. Giving up
Finally
CLIENT[sftp]: Removing listener from error
New attempt
Debugging turned on
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Connection attempt 1 failed. Trying again.
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Exhausted all connection attempts. Giving up
Finally
CLIENT[sftp]: Removing listener from error
...
...
```

While this happens on v5.3.x:

```
New attempt
CLIENT[sftp]: Debugging turned on
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Connection attempt 1 failed. Trying again.
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: Exhausted all connection attempts. Giving up
CLIENT[sftp]: Connection failed - reject
Finally
CLIENT[sftp]: Adding enderrorListener
CLIENT[sftp]: No connection - skipping call to end()
New attempt
CLIENT[sftp]: Debugging turned on
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 192.168.x.x on port 22 ...
CLIENT[sftp]: endErrorListener called with connect EHOSTDOWN 192.168.x.x:22 - Local (192.168.x.x:x) and code EHOSTDOWN
CLIENT[sftp]: Exhausted all connection attempts. Giving up
CLIENT[sftp]: Connection failed - reject
// Here it never returns
```

As you can see on the second output there's a different error msg `endErrorListener called with connect EHOSTDOWN`, maybe it's related to the issue 🤔 

BTW it's off-topic here but you'll notice that even if I set the retries number to 0 it always retry on the first call no matter what version I'm using.

**Comment by theophilusx** [comment]
It looks like your use case is being impacted by changes in 5.3.1 that
were introduced to allow ssh2-sftp-client to better handle the situation
where a sftp connection is lost part way through the session. I will
need to have a look at it to see if there is a way to handle both cases.
Note that the README does warn against using the same sftp object (i.e.
from call to new SftpClient) for multiple connections. The problem is
with respect to adding and removing listeners and the danger of getting
a 'hang' if an error occurs in-between the removal of listeners and
adding them back for the next connection. This is one of the
disadvantages of trying to mix an event based model with a Promises
based API. 

I do think your use case is a bit unusual. You would probably be far
better off setting the retries count to something high and not have your
loop at all. What you are doing is replicating the functionality in the
retries facility, but without the addition of the 'step back' facility
which it offers. It is extremely rare for a connection to fail many
times and then suddenly start working. With your approach, the system
will continue indefinitely - until the user stops it. Instead, you could
set retries to something like 100 (or 1000 or ...) and get the benefit
of increasing time between connections, reducing load

I would also consider a slight change to your code. You probably
shouldn't call sftp.end() from inside the finally block as that block
will be called even if the initial connection fails (and there is no
connection to end), plus you really should have a catch there to catch
errors which occur (such as lost connection part-way through upload of
directory). In fact, I would separate the two things - getting a
connection and uploading the directory, as you can get different errors
for each which need to be handled in different ways. For example, it
might make sense to try reconnecting multiple times in order to get the
connection, but if the server is returning some error, such as a
permission failure or disk full failure when trying to upload the
directory, it makes no sense to retry indefinitely until the user stops
the process. 

Yes, I was aware of the issue with retries occurring at least twice. It
is a small issue with the retry package I need to fix, but doing so
requires significant refactoring and it isn't critical enough to warrant
that work at this time.

Flavien Koehler <notifications@github.com> writes:

> **ssh2 version:** 5.3.0-1
> **Node version:** 12.14.x (through electron v9.3.2)
>
> I recently upgraded the module from v5.1.2 to v5.3.1 and I'm facing an issue since then. My use case is as follow:
>
> I wanna upload a directory and retry indefinitely until either it succeeds or the user clicks on a button to stop. To do so, I call the following function, wait for its completion then execute it again if the upload failed and the user hasn't clicked on the stop button.
>  
> ```
> const sftpConfig = {
>     host: '192.168.x.x',
>     port: 22,
>     username: 'foo',
>     password: 'bar',
>     retries: 0,
>     debug: (msg) => fsPromises.appendFile('./sftp-debug.log', `${msg}\n`, 'utf-8'),
> }
>
> export const uploadDir = (srcDir, destDir) => {
>     fsPromises.appendFile('./sftp-debug.log', 'New attempt\n', 'utf-8'); // DEBUG
>     return sftp.connect(sftpConfig)
>         .then(() => sftp.uploadDir(srcDir, destDir))
>         .finally(() => {
>             fsPromises.appendFile('./sftp-debug.log', 'Finally\n', 'utf-8'); // DEBUG
>             return sftp.end();
>         });
> };
> ```
>
> Calling this function in a loop while the sftp server is down produces the following logs on v5.1.x or v5.2.x:
>
> ```
> New attempt
> Debugging turned on
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Connection attempt 1 failed. Trying again.
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Exhausted all connection attempts. Giving up
> Finally
> CLIENT[sftp]: Removing listener from error
> New attempt
> Debugging turned on
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Connection attempt 1 failed. Trying again.
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Exhausted all connection attempts. Giving up
> Finally
> CLIENT[sftp]: Removing listener from error
> New attempt
> Debugging turned on
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Connection attempt 1 failed. Trying again.
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Exhausted all connection attempts. Giving up
> Finally
> CLIENT[sftp]: Removing listener from error
> ...
> ...
> ```
>
> While this happens on v5.3.x:
>
> ```
> New attempt
> CLIENT[sftp]: Debugging turned on
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Connection attempt 1 failed. Trying again.
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: Exhausted all connection attempts. Giving up
> CLIENT[sftp]: Connection failed - reject
> Finally
> CLIENT[sftp]: Adding enderrorListener
> CLIENT[sftp]: No connection - skipping call to end()
> New attempt
> CLIENT[sftp]: Debugging turned on
> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
> DEBUG: Client: Trying 192.168.x.x on port 22 ...
> CLIENT[sftp]: endErrorListener called with connect EHOSTDOWN 192.168.x.x:22 - Local (192.168.x.x:x) and code EHOSTDOWN
> CLIENT[sftp]: Exhausted all connection attempts. Giving up
> CLIENT[sftp]: Connection failed - reject
> // Here it never returns
> ```
>
> As you can see on the second output there's a different error msg `endErrorListener called with connect EHOSTDOWN`, maybe it's related to the issue 🤔 
>
> BTW it's off-topic here but you'll notice that even if I set the retries number to 0 it always retry on the first call no matter what version I'm using.


-- 
Tim Cross

**Comment by fkoehler42** [comment]
@theophilusx Thank you for the prompt answer!

> Note that the README does warn against using the same sftp object (i.e.
from call to new SftpClient) for multiple connections.
>
I didn't see this, my bad.

My use case is quite unusual indeed. The reason why I'm not using the retry feature is because I wanna keep the control between each retry to look at a React component state in order to see if the user has clicked the stop button. Is there a way to interact with the sftp instance to stop the connection attempts?

> You probably
shouldn't call sftp.end() from inside the finally block as that block
will be called even if the initial connection fails (and there is no
connection to end), plus you really should have a catch there to catch
errors which occur
>
Thanks for the advice regarding the `end` call! I do have a catch block which is inside my React component that calls `uploadDir`

**Comment by theophilusx** [comment]
Flavien Koehler <notifications@github.com> writes:

>
> My use case is quite unusual indeed. The reason why I'm not using the retry feature is because I wanna keep the control between each retry to look at a React component state in order to see if the user has clicked the stop button. Is there a way to interact with the sftp instance to stop the connection attempts?
>

No. This is something which is a current limitation with Promises -
there is no clean way to cancel a promise. There are some proposals and
I think there is some experimental functionality in current development
branch for node to add this type of functionality, but at present,
nothing exists. The problem is that promises are executed in a separate
context from your main execution loop and there is no link between them.
All you can do is add a 'then' block which could update your 'state' or
use async and wait for the promise to end and then update your state
(but that will mean your main loop is blocked during the await).

This is one reason it is often better to break things up into separate
functions. Have one function which establishes the connection and then
another function which uploads the directory. Reality is that if no
conection has been established for 10 retries, it is unlikely to occur
after 100 or more - it is a 'hard' failure.

Where you may sometimes need a cancel option is when your uploading very
large data sets. If for example, the directory you ware uploading is
many gigabytes of data, you may want to have a mecahnism to allow the
user to cancel the upload (anything less is unlikely to be useful as
uploads tend to be pretty fast and the data will be uploaded before the
user can stop it). If this is the case, you are better off rolling your
own uploadDir function where each file is uploaded as a separate promise
and you can check for a change in state between uploading each file. 

When it comes to promises, if you want to be able to interrupt the
process, you really need to keep the promises as small as possible.
Forget about trying to find ways to interrupt longer running promises -
for all intents and purposes, consider a promise a completely separate
program. Once fired off, all you can do is wait for them to complete or fail.

The other thing to consider is whether having the ability for the user
to cancel the upload is justified. This is functionality which really
only makes sense if your uploading really large data sets. Smaller data
sets upload pretty fast and your often better off just verifying that
the user really does want to upload and then once confirmed, just doing
the upload and only stopping if there is an error.

**Comment by theophilusx** [comment]
The code in version-6 branch has been re-factored to provide better handling of close and end events. The code in that version has also been updated to use a better retry mechanism. 

Unfortunately, there is still no clean way to provide the ability to cancel/interrupt a promise before it is resolved. This requires node support which isn't yet available. 

Feel free to try out the code in branch version-6. I will probably release a new version soon (assuming no new bugs are discovered in final testing).
