### ISSUE TITLE
Add rename method for directory

### ISSUE THREAD

**Issue by MuhammedParlak** [theophilusx/ssh2-sftp-client#278]
I want to change the name of the remote directory.

**Comment by theophilusx** [comment]
This is a bit server dependent. Some servers will allow you to rename a
directory in the same way you rename a file with the rename() function,
but others will not. The problem is that sftp servers have a variety of
back-end storage solutions, some will allow renaming/moving of a
directory and others will not. There is no easy way to know if the
server supports it or not - you have to just try it and if it work
great, otherwise you have to do something manually.

the rename() command in ssh2-sftp-client makes no assumption about the
remote objects and will work with directories if the server supports
renaming of directories. If it doesn't, it will generate an error.
