### ISSUE TITLE
Error: Bad path on put()

### ISSUE THREAD

**Issue by eduardobalbo** [theophilusx/ssh2-sftp-client#279]
Node -v = v12.18.2
ssh2-sftp-client: "^5.3.1"

I'm having an issue with my path, wich throws me an error if i add one more subpath.

_path = server/env/static/nuxt/archives/555/_ > This works perfectly.

_path = server/env/static/nuxt/archives/555/332/_ > This throws this error:

` 2020-11-05T16:38:22: put->put: Bad path: /www/server/env/static/nuxt/archives/555/ parent not exist
`

As you can see on the error there is no reference to the subfolder '332'.

On the code, file.directoryName references my 'path' where the method is being called like this.

`uploadArchive = new uploadArchive (directory, fileName, fileContent)`

The Uploader code:

```
    const _RAIZ_ = '/www/'

    uploadFiles() {
        const sftpClient = new sftp();

        return new Promise((resolve, reject) => {
            sftpClient.connect(sftpConfig)
            .then(() => {
                return Promise.all(this.files.map(file => {
                    sftpClient.mkdir(_RAIZ_ + file.directoryName, false)                                        
                    .then(() => {
                        let a = ''
                    })
                    .catch((err) => {
                        console.log(err);
                    })   
                    return sftpClient.put(file.fileContent, _RAIZ_ + file.getFullPath())                  
                }))
                
            })
            .then(() => {
                sftpClient.end()
            })
            .then(() => {
                resolve('files uploaded')
            })
            .catch((err) => {                
                console.log(err.message)
                reject(err);
            });
        })        
    }
```

I tried changing the recursive option to _true_ , it creates the folder and the subfolder, but dosnt create the file.
Any help would be apreciated.

**Comment by theophilusx** [comment]
Unfortunately, there are a lot of errors in your code which will need to
be fixed. I'll go through some of them below.

That error often indicates that you don't have the right permissions to
create the directory. First thing I would do is use something like
openSSH's sftp CLI and verify you are able to create the new directory.
However, I suspect the main issue is that the call to put() is happening
before the call to mkdir() has completed (see comments below).

The major problem with your code is the design. The basic sftp protocol
and therefore ssh2-sftp-client, does not support concurrent operations
over an ssh2-sftp-client connection. This rules out using Promise.all()
in the manner you have. You need to ensure that each call to sftpclient
has completed before attempting the next one. There are also problems in
your promise chain. When using a promise chain, you need to be very
explicit about what you return from each then() block. Failure to do
this will result in the block exiting before any promise you have called
in that block has resolved/rejected i.e. the next then() block will fire
before the previous one has completed. You also don't need the outer
wrapper Promise. It could all be just a single promise chain.

I have placed some comments inside your code to highlight specific
problems.

>
> ```
>     const _RAIZ_ = '/www/'
>
>     uploadFiles() {
>         const sftpClient = new sftp();
>
          // You don't need to wrap this inside a new Promise. You can
          // just start with 'return sftpClient.connect().then()....
>         return new Promise((resolve, reject) => {
               // should have an explicit return so that the call to
               // connect completes before the next then() block fires
>             sftpClient.connect(sftpConfig)
>             .then(() => {
                   // Cannot use Promise.all() like this because it will
                   // to execute multiple mkdir() calls concurrently
                   // over the same connection.
>                 return Promise.all(this.files.map(file => {
                      // even if this was to work, you need to have a
                      // return here, plus the structure is all wrong.
                      // you don't want to catch an error here and the
                      // call to put() can fire before the call to
                      // mkdir() has resolved.
>                     sftpClient.mkdir(_RAIZ_ + file.directoryName, false)
>                     .then(() => {
>                         let a = ''
>                     })
                      // this will hide any errors/reject
>                     .catch((err) => {
>                         console.log(err);
>                     })
                      // the call to put() will run before the call to
                      // mkdir() has resolved
>                     return sftpClient.put(file.fileContent, _RAIZ_ + file.getFullPath())
>                 }))
>
>             })
              // if you were able to use Promise.all in this manner, you
              would also want to check the array returned by Promise.all
              to verify the status (resolved or rejected) of each
              promise.
>             .then(() => {
                  // should have an explicit return
>                 sftpClient.end()
>             })
>             .then(() => {
                  // should have explicit return
>                 resolve('files uploaded')
>             })
>             .catch((err) => {
>                 console.log(err.message)
>                 reject(err);
>             });
>         })
>     }
> ```
>

There are other issues with your code as well, but I think I've marked
the key ones. If what you want to do is upload a directory of files,
note that there is a uploadDir() method which can do this. Also, if you
want to upload files (rather than buffers or data from file streams),
you are better off using fastPut() instead of put().

You might find async/await easier to work with than Promise chains.
Check out some of the examples in the example directory within the
github repository.

**Comment by eduardobalbo** [comment]
Thank you for the response Theo! I'll start fixing the code today.
But what is confusing for me is that i can create the directory, and the file, if i give the path a certain number of subfolders.

`server/env/static/nuxt/archives/555/` > With this path, i can create the folder, them the file without any issues.
But when the path has one more folder in it like this `server/env/static/nuxt/archives/555/332/` , it gives me the error on the previous message.

I'm using this uploader in other cases in my software, with multiple files being uploaded and so on, and it allways worked with the actual design, so i really don't know why in this specific case of having one more folder to the file to be put in, the code breaks. This is also the first use case where i have one more folder to the 'path'.

Any ideas why it works fine with the path having one less folder, if the promise chain is wrong?

**Comment by theophilusx** [comment]
I suspect it is simply a timing issue.

The longer the path, the more calls are made to verify the path is valid
and if you are using the recursive option to create missing directories
in the path, there is even more calls to mkdir().

See what happens when you fix the code. I suspect once you have a design
without the issues I outlined before, the depth of the paths will not
matter.

**Comment by eduardobalbo** [comment]
I refactored the function now i'ts working fine with all my use cases for sending files.
This is how the code is now:

```
    async uploadFiles() {
        try {
            const sftpClient = new sftp()
            await sftpClient.connect(sftpConfig)

            for (const file of this.files) {
                const filePath = _RAIZ_ + file.directoryName
                const filePathComplete = _RAIZ_ + file.getFullPath()
                const isExists = await sftpClient.exists(filePath)
                const fileContent = file.fileContent

                if (!isExists) {
                    await sftpClient.mkdir(filePath, true)
                }
                await sftpClient.put(fileContent, filePathComplete)
            }
            await sftpClient.end()

        } catch (error) {
            console.log(error);
        }
    }
```

I know that there must be better way of doing this, but for now it looks fine. 
What do you think? And thank you for the help.

**Comment by theophilusx** [comment]
That looks pretty good now. The only thing I can see which might
increase speed is that if your only reading in the file contents just
for the upload process, you could bypass that step by just passing in
the local path rather than the file contents stream. This would let you
use fastPut instead of just put, which would be faster.

**Comment by eduardobalbo** [comment]
I see! Going to try that on the monday. 
I think you can close the issue now.
Thank you so much for the help, fast responses and knowledge.
