### ISSUE TITLE
Attempt Count Doesn't Increment

### ISSUE THREAD

**Issue by VandalSausage** [theophilusx/ssh2-sftp-client#282]
Heya, love this library, just encountered a very small bug with retry logging (all the actual functionality is totally fine it's just the debug logs and the error message that get the count wrong.

my set up: 
```javascript
const sftpConfig = {
      host: encryptionDetails.sftpUri,
      // private key is read from id_rsa and converted to openSSH format when config blob is created
      privateKey: encryptionDetails.sftpPrivateKey,
      username: encryptionDetails.hostUsername,
      port: encryptionDetails.port,
      readyTimeout: 20000, // integer How long (in ms) to wait for the SSH handshake
      strictVendor: true, // boolean - Performs a strict server vendor check
      debug: verbose && logger.logPlain,
      retries: 3, // integer. Number of times to retry connecting
      retry_factor: 2, // integer. Time factor used to calculate time between retries
      retry_minTimeout: 4000,
    }
    const sftp = new Client()
    try {
      await sftp.connect(sftpConfig)
      logger.logInfo("connection established", "pre-checks")
      await validateSFTPFiles(
        logger,
        sftp,
        sftpList,
        encryptionDetails,
        failures,
      )
      if (!failures.length) {
        logger.logInfo("getting sftp files...", "pre-checks")
        await getSFTPFiles(sftp, sftpList, encryptionDetails)
      }
      await sftp.end()
      logger.logInfo("sftp connection closed.", "pre-checks")
    } catch (e) {
      failures.push(`error during sftp connection (error: ${e.message})`)
    }
  }
```

[Debug logs](https://github.com/theophilusx/ssh2-sftp-client/files/5561380/failure-logs.txt) don't increment the count (lines 65 and 112) and the final error message is:

"connect: Timed out while waiting for handshake after 1 attempt"

despite there being two attempts.

Also side note: is there any reason why I could be successfully connecting to a remote server then running the same script again and getting the errors in the log? mostly front-end dev a bit out of depth here

**Comment by theophilusx** [comment]
Yes, there is a bug in the count of connection retries.

I've never been very happy with the code in that section. It is somewhat
'in-elegant'.

As the upstream ssh2 module is being completely re-written, I have to do
a big re-write of this module to work with the new API. My plan is to
cleanup this code and resolve that minor bug at that time.


> Also side note: is there any reason why I could be successfully
> connecting to a remote server then running the same script again and
> getting the errors in the log? mostly front-end dev a bit out of depth
> here

Not sure what the issue could be. I have seen this occur if your making
many (10 or so) connections within a very short time (seconds or less).
Most sftp servers have some rate limiting software whereby if they see
too many connections too quickly from a specific IP, they will begin to
drop them and eventually refuse connections.

People forget that when you disconnect a TCP connection, there is a
TIME_WAIT interval (up to 2 minutes on some OSs) where the connection is
still there. So, sometimes, people run into this error when testing
their scripts because they run the tests too quickly.

**Comment by VandalSausage** [comment]
Thanks for the reply! Turned out that was exactly the issue - cheers for the explanation!
