### ISSUE TITLE
"Connection ended unexpectedly by remote server" while uploading file using sftp.put method (code: 'ERR_NOT_CONNECTED')

### ISSUE THREAD

**Issue by wahajahmed** [theophilusx/ssh2-sftp-client#286]
I am getting this error while uploading file to a SFTP server using sftp.put method.

**UploadFileToSFTPServer error my-sftp-client: Connection ended unexpectedly by remote server
{ Error: my-sftp-client: Connection ended unexpectedly by remote server
at Object.formatError (............../node_modules/ssh2-sftp-client/src/utils.js:57:18)
at Client.self.client.on.on.on (............../node_modules/ssh2-sftp-client/src/index.js:1038:21)
at Client.emit (events.js:182:13)
at Socket.<anonymous> (............../node_modules/ssh2/lib/client.js:312:10)
at Socket.emit (events.js:187:15)
at endReadableNT (_stream_readable.js:1094:12)
at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ERR_NOT_CONNECTED' }**

Below is the code we are using (extracted from multiple modules)

`retryPendingFilesForExport().catch(ex => console.error('old files sync retry Error:', ex));`

```
export const retryPendingFilesExport = async () => {
  const localWorkPath = `${DIRECTORY_PATH.LOCAL_IN_WORK}`;
  const remoteWorkPath = `${DIRECTORY_PATH.REMOTE_IN_WORK}`;
  const localArchievePath = `${DIRECTORY_PATH.LOCAL_IN_ARCHIVE}`;

  try {
    // this get all available files from  'current working' folder
    const pendingFiles = await getNotSynedFiles(localWorkPath);

    pendingFiles.forEach(async (pendingFile) => {
      const pendingFilePath = pendingFile.filePath;
      const remoteFilePath = pendingFilePath.replace(localWorkPath, remoteWorkPath);
      const archievePathForFile = pendingFilePath.replace(localWorkPath, localArchievePath);

      await UploadFileToSFTPServer(pendingFilePath, remoteFilePath);
      // This 'moveFile' method moves files from 'current working' folder to an 'archive folder' after upload
      await moveFile(pendingFilePath, archievePathForFile);
    });
  } catch (ex) {
    throw ex;
  }
};
```

```
function UploadFileToSFTPServer(localFilePath, remoteFilePath) {

  const sftp = new SFTPClient('my-sftp-client');
  return sftp.connect(SFTP_CREDENTIALS)
    .then(() => {
      return sftp.put(localFilePath, remoteFilePath);
    })
    .then(() => {
      return sftp.end();
    })
    .catch((err) => {
      console.error('UploadFileToSFTPServer error', err.message);
      throw err;
    });
}
```

We are using "^4.3.0" version of the "ssh2-sftp-client". Its a live application from Aug 2020. Things were working fine before but we started getting this error from Oct 2020. SFTP server is managed by a third party. We are not sure its a loop hole in our application or something (Connection policies/etc) has changed on SFTP server end.

We upload the pending files in loop and we get same error for every file upload sometimes. Can you help us here?

Thanks.

**Comment by theophilusx** [comment]
The error you are seeing is a sign that the remote server is
deliberately terminating the connections. My first guess would be that
you are making too many connections over too short a period and the
server things it is some sort of Dos attack or it simply triggers some
sort of resource limiting facility to prevent the server from being
overwhelmed by some mis-configured client.

You are opening a new connection for every file you upload. Unless these
files are very large, this can result in a rapid number of connections
over a very short period. Exactly the sort of pattern which is likely to
trip some rate limiter or firewall rule.

With sftp, making connections is a very expensive operation because it
involves a complex handshake, exchange of keys and negotiation of
ciphers. You really want to limit this. For example, rather than opening
a new connection inside the upload file function, pass in the sftp
client object as an additional argument along with the source and
destination file data. Make the connection before starting the file
upload loop and then end it after completion. This way, you will only
make one connection and use that for all the files being uploaded in
that batch.

I also notice you are using the array forEach method. This is a
dangerous method to use in conjunction with async/await. It is highly
likely it is not working the way you think it is. Look at the manual for
array methods and you will likely find a warning about using
async/await. In general, what you need to do is collect the return
values from calling the async method to upload the files into an array,
pass that array to Promise.all and to an await on that rather than each
individual call. A google on await and array.forEach() will likely point
you in the right direction. I've found that by the time you have things
correctly coded to work with async/await, the forEach method is actually
more convoluted and difficult to understand than just using a standard
loop for form. The key problem with .forEach is that they way JS
executes it, the Promise chain is not correctly followed i.e. subsequent
calls can be fired off before the promise in the previous call has
completed.

I would also update to the most recent version. You are using quite an
old version which had known bugs in the handling of connections. It was
released almost 12 months ago and was followed by 4.3.1 not long
afterwards. The 5.x release has significant improvements in error
handling and while it was a major version change, the API only changed
slightly. Make sure you do NOT use version 14.x of node. That version
has known problems with the ssh2 and ssh2-streams modules used by
ssh2-sftp-client. The issue is due to a change in node which has now
bene rolled back in version 15.3.0



--
Tim Cross
