### ISSUE TITLE
upload more than big file get not callback ssh     when use uploadDir function 

### ISSUE THREAD

**Issue by keyus** [theophilusx/ssh2-sftp-client#290]
have more than 100 files

some files is 200kb or big

so 
i use uploadDir function  

When I upload a lot of files, some large files, occasionally there is no callback response, resulting in a stuck.

Then I switched the upload method in uploadDir to this.put to complete the upload successfully.

The writestream used by maybe...

**Comment by theophilusx** [comment]
Sorry, I'm having a little trouble understanding your email.

What version of ssh2-sftp-cleint are you using?

What version of node are you using?

What platform (operating system) are you running ssh2-sftp-client on?

Are you saying that using uploadDir is hanging, but if you change the
method to use put() instead of fastPut(), it works?

**Comment by theophilusx** [comment]
As there has been no feedback or update for over 14 days and because a new version is being released, I'm closing this issue. It can be reopened if more information is available or the issue persists.
