### ISSUE TITLE
How to get file and put in buffer instead of file system

### ISSUE THREAD

**Issue by patrickliechtypersonal** [theophilusx/ssh2-sftp-client#291]
You have an example of how to put a file using a buffer. ( https://github.com/theophilusx/ssh2-sftp-client/blob/master/example/buffer-put.js) Can you do the same thing with a get?  I want to read the file into a buffer and use the contents in memory.  I don't want to write the contents to the file system.

**Comment by theophilusx** [comment]
With get(), the method returns a buffer of data if the destination
argument (2nd arg) is undefined. so ...

get('/remote/path/to/file')

or

get('/remote/path/to/file', undefined, {encoding: 'utf8'})

However, note that using buffers is very inefficient, especially with
large data sources as it will load the whole thing into memory. Most of
the time, you are far better off using a stream and piping the data into
it. There is very little you can do with a buffer you cannot do with a
stream and it will be much faster and use less memory. You don't have to
write the data to the file system just because you use a stream - a
streamWriter is just one type of stream. A stream is really just a
function which takes data as input and processes it in some way,
possibly writing it to the file system, possibly transforming it in some
way and passing it out to be consumed by another stream object as part
of a pipeline or possibly sending it to a database, a network socket,
etc.

Have a look at the stream-handbook module on npmjs.com. It provides a
pretty good explanation of streams and how they can be used. I've used
them to zip/unzip data on the fly, others have used them to provide
throughput throttling, calculate download/upload speeds, parse records
for database insertion etc.

**Comment by patrickliechtypersonal** [comment]
Thanks for the info
