### ISSUE TITLE
Stuck while uploading dir to remote

### ISSUE THREAD

**Issue by suab321321** [theophilusx/ssh2-sftp-client#293]
I m trying to send a large dir (360 GB) to remote. But my copy always gets stuck at 64 GB. I have checked the amount of space left in remote machine and it is sufficient (size 2 TB). To cross check I even tried to manually copy it using `scp` command and that works.

command used = `conn.uploadDir(path1, path2);`

I dont know whats causing the issue. I have event listener for event 'upload',which tells me that it is hanged

`ssh2-sftp-client": "^6.0.0`

**Comment by theophilusx** [comment]
What version of node?

What platform (Linux, Mac, Windows)?

Can you provide a minimal script which reproduces the issue? If I can
reproduce the problem, then I can investigate.

**Comment by theophilusx** [comment]
Oh and try updating to v6.0.1.

**Comment by suab321321** [comment]
hey, sorry for late reply.
My os is ubuntu 14.04
When I tried after updating to v6.0.1 my upload is stuck at 61G.

The script which use is like this:
```
const sftpClient = require('ssh2-sftp-client');
const conn = new sftpClient();
            conn.connect({
                host:host,
                username:process.env.AWS_EC2_USER,
                password:process.env.AWS_EC2_PASSWORD
            }).then(async() => {
                try{
                    if(isUpload)
                        await conn.uploadDir(filePath, filePath);
                    else
                        await conn.downloadDir(filePath, filePath);
                    conn.end();
                    resolve("Remote file transfer started Successfully");
                    console.log("<-------completed copying to remote server------->");
                } catch (err) {
                    console.error("some error happened trying transfer operation "+err.toString('utf8'));
                    conn.end();
                    reject(err);
                }
            }).catch(err => {
                console.error("error connecting for remote copying");
                reject(err);
            })
```

**Comment by sbittmann** [comment]
Same issue here, but with a much smaller folder (only 523 KB)...
I'm trying to send the dir from macOS 11.0.1 with node 14.13 installed to alpine linux instance.
Some files are send to the destination, but at some point it gets no more files are send

**Comment by theophilusx** [comment]
OK. Having the script really helps. You have a bug in your script which
probably explains the issue you are seeing or results in the error not
being shown.

the problem is how you are mixing async and promise chains and the
explicit call to resolve (which shouldn't work given you don't define a
promise, so while Promise.resolve() might work, just resolve() should
throw an error!).

Try something like


const sftpClient = require('ssh2-sftp-client');
const conn = new sftpClient();
conn.connect({
   host:host,
   username:process.env.AWS_EC2_USER,
   password:process.env.AWS_EC2_PASSWORD
}).then(() => {
   if(isUpload) {
     return conn.uploadDir(filePath, filePath);
   } else {
     return conn.downloadDir(filePath, filePath);
   }
}).then(() => {
   return conn.end();
}).catch((err) => {
   console.log(err.message);
});

Note that the returns are important - you want the result of the next
Promise to be returned as part of the Promise chain. Not also you don't
need a catch or calls to reject - if an error is thrown, it will result
in a reject, which will be caught by the catch at the end of the chain.

You didn't say which version of node you are using. Don't use node
v14.x. There is a known issue with v14.x which will cause the
issue you are seeing (see README).

In general, it is a Badi Idea (TM) to use both Promise chains and
async/await together. Either use one or the other. There may still be an
issue, but now the catch clause should reveal what errors are occuring.
With the way your code was structued, the error could be 'lost' because
your promise chain was borken due to not returning each new Promise in
the chain i.e. the outer catch would be executed before the async
promises were resolved.

**Comment by sbittmann** [comment]
Okay, thanks for the Information about node v14. updated to v15 like readme says the problem should not be there and anything works fine. Maybe you should make that a bit more visible in the readme so users of the library see it faster und you have to answer less issues 😅.

I think the problem of @suab321321 is based on node v14 like me.

Greetings an many thanks

**Comment by suab321321** [comment]
@theophilusx actually you said you wanted minimal example so put that the whole function is like
```
function remoteFileTransfer(host, filePath, isUpload) {
    return new Promise((resolve,reject) => {
        console.log("<------started file transfer to/from remote server------>");
        console.log("hostname is :" + host);
        console.log("File Path :" + filePath);
        setTimeout(() =>{
            const conn = new sftpClient();
            conn.connect({
                host:host,
                username:process.env.AWS_EC2_USER,
                password:process.env.AWS_EC2_PASSWORD
            }).then(async() => {
                try{
                    if(isUpload)
                        await conn.uploadDir(filePath, filePath);
                    else
                        await conn.downloadDir(filePath, filePath);
                    conn.end();
                    resolve("Remote file transfer started Successfully");
                    console.log("<-------completed copying to remote server------->");
                } catch (err) {
                    console.error("some error happened trying transfer operation "+err.toString('utf8'));
                    conn.end();
                    reject(err);
                }
            }).catch(err => {
                console.error("error connecting for remote copying");
                reject(err);
            })
        }); //we should bring this closet by trial and testing
    });
}
```

**Comment by theophilusx** [comment]
Please see the README. Node v14.x causes problems with ssh2 due to a
change introduced in the network stack. This change was subsequently
rolled back in node v15.3. Either downgrade to node v13.x or upgrade to
node v15.x, but don't try to use node v14.x

**Comment by theophilusx** [comment]
Same comments hold for actual script (with exception for resolve/reject
comments). There is no need to wrap this in a Promise and there is no need
for the setTimeout. Don't mix Promises and async/await - use one or the
other.

Please confirm your NOT using node v14.x.

**Comment by suab321321** [comment]
yes with node v15.5.1 it is working, and thank you for tip on resolve and aysnc await
