### ISSUE TITLE
fastput Bad path: must be a regular file

### ISSUE THREAD

**Issue by eagress** [theophilusx/ssh2-sftp-client#297]
fastPut has a bad path error, but the remote path looks fine. I've double checked it using FileZilla and we upload files to that server and directory daily with CoreFTP.

I've attached a debug log of the attempt to fastPut the file. Please take a look at it and see if you can spot a problem.
[Log Upload Attempt 20210115.txt](https://github.com/theophilusx/ssh2-sftp-client/files/5822657/Log.Upload.Attempt.20210115.txt)

The routine I'm calling is Node. I've attached it as well.
[sshclient js code.txt](https://github.com/theophilusx/ssh2-sftp-client/files/5822663/sshclient.js.code.txt)

Thank you for any help you can provide.

**Comment by theophilusx** [comment]
The script thinks "/UPLOAD_IMG/MIC.BANKICL.SWCAGING20210114-0954.NCAM"
is a directory and not a file. The stat check is returning that it is a
directory.

What verson of ssh2-sftp-client are you using?

What version of node are you using?

Can you verify that "/UPLOAD_IMG/MIC.BANKICL.SWCAGING20210114-0954.NCAM"
is not a directory and is in fact a file?

**Comment by eagress** [comment]
Node.js v14.3.0
ssh2-sftp-client 5.3.1

/UPLOAD_IMG is the target folder.
MIC.BANKICL.SWCAGING20210114-0954.NCAM is the file name.

And for some reason I don't know they are all caps.

Steve
________________________________

**Comment by theophilusx** [comment]
OK, first of all, don't use node v14.x. There is a problem with the ssh2
library and node v14.x. The change which introduced the issue has been
rolled back in node v15.3. (see ssh2-sftp-client README). The maintainer of ssh2 is
re-writing the library, but until that is done, node 14.x is not
supported.

Please upgrade ssh2-sftp-cleint to version 6.0.1 and re-test. Let me
know if the issue continues in that version.

**Comment by eagress** [comment]
I've updated node to v15.6 and ssh2-sftp-client to v6.0.1.

An error is still happening with fastPut, but now it's different. I've attached the log. The error says:
error: fastPut: Repositioning not supported after read/write data.

The attached log is everything from connect to disconnect with the remote server. Sorry to ask you to wade through all that but hopefully you'll see something worthwhile.

The code is the same as the prior example. The only change on my side is updating node and ssh2-sftp-client.
[Log Attempt 2 20210119.txt](https://github.com/theophilusx/ssh2-sftp-client/files/5838842/Log.Attempt.2.20210119.txt)

**Comment by theophilusx** [comment]
Can you modify your script to use put() rather than fastput()?

Some sftp servers don't work correctly with fastput() because they are
unable to handle the concurrent transfer fastput() uses (this is based
on an earlier communication I had with the ssh2 maintainer). I've not
actually come across a server which doesn't support fastput(), but the
ssh2 maintainer is far more experienced and knowledgeable in this area
than me.

This is almost certainly an ssh2 issue and there is little I can do to
address it. It could still be an issue with incompatibility with more
recent versions of node. I know the specific change which caused the
problems in v14.x was rulled back in 15.3, but there could be other node
changes which cause problems. The bad news is that the ssh2 library is
being re-written, which means it is unlikely there will be a fix in the
0.8.x branch of ssh2. Unfortunately, the new ssh2 re-write, which will
become ssh2 v1.0 is still a long way from being ready for production use
and there is no timeline on when that will be ready (I am regularly
testing against the development and it still has significant issues).

This all means that if you still get errors using put() rather than
fastput(), the only solution I have is to downgrade to node v12.x and
wait for ssh2 v1.0 to be released. Of course, if this is a server
limitation issue wrt fastput(), the issue will still exist.

If you want to confirm it is an ssh2 issue, you can try modifying your
script to use just ssh2 and not ssh2-sftp-client. If you do this and
still find an issue, I would recommend logging it with the ssh2 project
as it could be useful data for the re-write and may help with getting
the new version of ssh2 ready for production use.

**Comment by theophilusx** [comment]
Any update on this? Did put() work?

**Comment by theophilusx** [comment]
No update on this for 2 weeks, closing for now. Can re-open if more info becomes available.
