### ISSUE TITLE
client.list(dirPath) is not executing in the inner recursive async function  

### ISSUE THREAD

**Issue by mukkhtarr** [theophilusx/ssh2-sftp-client#299]
Hello, I am trying to get list of all remote files from the directory and subdirectories. Following is the code that I wrote. It only works for the top level files but not for the inner directories. not sure what I am doing wrong here:

```
const path = require('path')
const SftpClient = require('ssh2-sftp-client');
const config = require('./config')

/* FUNCTIONS  */
const getAllRemoteFiles = async function(dirPath, ftpConn, arrayOfFiles) {
    const files = await ftpConn.list(dirPath);
  
    arrayOfFiles = arrayOfFiles || []
  
    files.forEach(async function(file) {
      if (file.type == 'd') {
        arrayOfFiles = await getAllRemoteFiles(dirPath + "/" + file.name, ftpConn, arrayOfFiles)
      } else {
        //file['name'] = path.join( dirPath, "/", file.name)
        file['name'] = dirPath+"/"+file.name;
        arrayOfFiles.push({name:file.name, size:file.size, modifyTime:file.modifyTime})
      }
    })
  
    return arrayOfFiles;
}


/* ==============END of Functions ================== */

async function getRemoteFiles() {
  const client = new SftpClient();
  const src = '/prd/v5';

  try {
    await client.connect(config.conn);
    
    let data = await getAllRemoteFiles(src, client);
   // process.on('warning', e => console.warn(e.stack));
    return data;


  } finally {
    client.end();
  }
}

getRemoteFiles()
  .then(msg => {
    console.log(msg);
  })
  .catch(err => {
    console.log(`error: ${err.message}`);
  });
```

I get the following warning:
```

(node:2988) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2988) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:2988) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
```

Can anyone please look into this issue? 

Looking forward to your kind prompt response please.

**Comment by theophilusx** [comment]
What version of ssh2-sftp-client?

What version of node?

What platform?

There are a couple of things in your code which I would change. The
first one is the way you are using async calls within a forEach array
function. The array comprehension functions e.g. .map, .forEach etc are
not terribly async safe. While they can be used with async/await, there
are some additional precautions you need to take which in general make
them 'messier' and less clear than just using for...of. Google for
details on using the array methods and async/await for details.

I would also change the way you are using arrayOfFiles. You are changing
this array at multiple levels in multiple paths. Better off having the
function return a fresh array which you can then join to the top level
array (possibly using the spread operator or one of the array methods).
I would also avoid mutating the files array during iteration of that
array - not necessary, just push the result into arrayOfFIles.

I also think it is a bad idea to mix promise chains and async/await. Use
one or the other. There is no need to use both.

**Comment by mukkhtarr** [comment]
Hello Tim,

Many thanks for your kind response. I really appreciate it. I will try the solutions you recommended and get back to you. Please find below information requested.

Version of ssh2-sftp-client: 6.0.1

Version of node: v14.15.1

Platform: Windows 10 Enterprise

**Comment by theophilusx** [comment]
Please note: node v14.x does NOT work reliably with the underlying ssh2
library. This is due to a change in node v14.x which was later rolled
back in node v15.3. There is no fix or work-around for this issue.

The author of the ssh2 library is undertaking a complete re-write of the
ssh2 library, partly to fix the issue introduced in node v14.x and
partly to address some underlying design weaknesses in the ssh2 library
implementation. Unfortunately, this re-write is progressing very slowly
and is not yet ready for production use.

For now, if you want to use either ssh2 or ssh2-sftp-client, my strong
recommendation is to stick with node v12.x. While the change in node
v14.x which caused the problem has apparently been rolled back in node
15.3, which theoretically means you could use node 15.3+, I would be
cautious about doing so. The problematic change did have an overall
performance improvement for a majority of use cases and I suspect that
it may well be re-introduced in some form in the future (possibly once
they feel all client libraries which were broken by the change have been
updated or made obsolete). IMO this uncertainty is sufficient reason to
not use node version greater than 12.x and wait until ssh2 v1.0.0 is
released (at which time, I will release ssh2-sftp-client 7.x).

**Comment by mukkhtarr** [comment]
Thank you so much, Master Tim, I will keep that in mind and will look forward to ssh2-sftp-client 7.x

Also, your advise worked like a charm. You are a life saver, I had been struggling for days.
