### ISSUE TITLE
Not working in Reactjs Application

### ISSUE THREAD

**Issue by KrVijay89** [theophilusx/ssh2-sftp-client#301]
Hi Team,

I trying this package with my reactjs application and facing the issue Error: process.binding is not supported

can any help me here

Thanks

**Comment by theophilusx** [comment]
Is this a browser based application or in something like Electron?

The ssh2-sftp-cleint package depends on the ssh2 library, which in turn
depends on the underlying network library available in node. Browser JS
implementations don't support this functionality. i.e. this library only
works in a node based environment, like Electron, where you also have a
webkit process for your react code.

**Comment by anubhav04** [comment]
Facing same problem with ReactJs on Electron.

**Comment by KrVijay89** [comment]
Hi Tim Cross

Thanks for the quick action.

We are using Reactjs with Electron for desktop application.

**Comment by theophilusx** [comment]
With electron, it is critical to ensure the ssh2-sftp-client code is
executed in the main process and not running in the browser process as
only the main process will have access to the underlying node networking
libraries. Browser processes explicitly ensure that such libraries are
unavailable due to security reasons.

A lot has changed in electron since I last used ssh2-sftp-client in an
electron app. Theoretically it should work, but it is critical to make
sure it is operating in the main process and not the browser/render
process. It could be that Electron has made changes to address some of
the security issues it has experienced which makes getting this to work
more complex and you will need to experiment a bit with various electron
settings to get it to work.

**Comment by theophilusx** [comment]
@vijay make sure the ssh2-sftp-client code is all running within the
context of the main process, not the render process. It may also be
necessary to tweak electron security privileges (a lot has changed in
electron in recent versions, so I'm not 100% sure on what may need to be
done). You will probably have to use the IPC services or similar to
communicate between the render process where your react is running and
the sftp client in the main process.

**Comment by theophilusx** [comment]
Did you make any progress with this? Is there any reason to keep this issue open now?

**Comment by theophilusx** [comment]
Closing issue as there are no further updates.
