### ISSUE TITLE
Express async/await issue S3 -> SFTP Server

### ISSUE THREAD

**Issue by pravMo** [theophilusx/ssh2-sftp-client#311]
Hi, 

I am using express v:4.13.3 and node v:14.16.0 (sometimes v:12) and ssh2-sftp-client v:6.0.1. Essentially in my forEach I am looping through all the S3 keys in my bucket (which are flat files in S3) and then use the data buffer provided for each file from S3 to upload data to an sftp server. The issue I am running into is not all the files/directories are uploaded to the sftp server on the FIRST try. But if I run the function a SECOND time I see all the files are uploaded and all directories are made. 

Am I running into any async/await issues? or is it the data buffer just not being read/transferred properly the first time around? bit new to JS promises also, so any help with the code would be greatly appreciated! thanks.

```
app.get("/data/:param", (req, res) => {
    s3.listObjects({params}, (
      data.Contents.forEach((elements) => {
        downloadObjectsFromS3(elements.Key);
      })
    );

    downloadObjectsFromS3 = (flatFile) => {
      s3.getObject({params}, (
        transferSFTP(getObjectS3BufferData, flatFile)
    )}

    transferSFTP = async (data, file) => {
    let modifyFile = file.substr(0, file.lastIndexOf("/"));
    let sftp = new Client();
    await sftp
      .connect({
        host: host,
        port: port,
        username: username,
        password: password,
      })
      .then(() => {
        return sftp.exists(`/folder/${modifyFile}`);
      })
      .then((data) => {
        if (data === false) {
          return sftp.mkdir(`/folder/${modifyFile}`, true);
        } else if (data === "d") {
          return;
        }
      })
      .then(() => {
        return sftp.put(data.Body, `/folder/${file}`)
      })
      .catch((err) => {
        console.log(err.message);
      });
    };
  });
}
```

**Comment by theophilusx** [comment]
Unfortunately, there are a number of bugs in your code, plus a couple of
other limitations you need to work around. Most of your issues are
centered around your use of JS asynchronous operations, so you may want
to do some more reasearch/experimentation to really understand how they
work. The JS model is significantly different to most other languages
(mainly due to the single thread basis of JS). This can make it a little
challenging to wrap your head around at first. Very important to
understand how Promises work and what their relationship is with
async/await (it is all Promises 'under the hood') and how they relate to
the main JS event loop. 

Firs, don't use node v14. Changes in node v14 network stack causes
problems for the ssh2 module (which ssh2-sftp-client depends on). These
changes were rolled back in node v15.3. (See the ssh2-sftp-client
README).

Second, forEach() is not async/await aware/safe. While you can use forEach,
you need to handle this limitation (you can find details on-line with a
search). In the end, I find it is usually cleaner/clearer to just do a
'for of' loop when using async/await.

Thirdly, it is usually not a good idea to mix async/await and promise
chains. This tends to create confusing code and often leads to various
bugs. Use either promise chains or asynch/await, but not both. Many
people find async/await easier to understand, so I would just use that
with try/catch blocks to catch errors and handle them. Any
promise().then() chain can be expressed as a value = await promise()
call. 

Finally, both async/await and Promises all return promise objects. This
means that a promise object will work its way back up your call stack.
So, transferSFTP will return a promise which you need to wait on for it
to be fulfilled (either rejected or resolved). Likewise, because
downloadObjects calls that function, it will also receive a promise
which needs to wait to be fulfilled.

You probably need to do a fair bit of refactoring before you will get
this code to work. Also good to think about when to create the sftp
connection and when to release it (I don't see an end() call at all).
Connecting is one of the slowest operations, so you only want to do this
when necessary. However, you also don't want to try and keep a
connection open too long without activity as the remote server may just
close it or timeout. You do want to make sure you end and cleanup to
avoid resource leaks.

**Comment by pravMo** [comment]
awesome! thanks for the advice
