### ISSUE TITLE
Ionic

### ISSUE THREAD

**Issue by MicrodeltaSL** [theophilusx/ssh2-sftp-client#312]
Hi Team.

Could I use in Ionic? 

thanks.

**Comment by theophilusx** [comment]
I've never used Ionic and no nothing about it. This module relies on the
network and crypto stacks provided by node (and therefore does not work
in a browser for example). If ionic provides the same network and crypto
APIs, then it will probably work. For example, I have used it within the
main process under electron because the main process is essentially a
node process, but it won't work within the render process because that
is essentially a browser process.
