### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by mzarzour** [theophilusx/ssh2-sftp-client#313]
We're suddenly having issues connecting to our FTP server. Here is some pertinent informations: Thanks for your help in advance. 

node: v14.16.1
ssh2-sftp-client: v6.0.1
auth: username/password

**Code**
            try {
                log.debug(`Connecting to FTP ${user}@${addr}:${port}`);

                const sftp = new Client('example-client');
                creds.debug = msg => {
                    console.error(msg);
                  };
                  
                await sftp.connect(creds);

                log.debug(`Connected to FTP`);

                await Promise.map(relativeFolderPaths, async p => {
                    await this.processType(p, sftp);
                });

                await sftp.end();
            }catch(e){
                await sendError(`Error encountered during SFTP`,e,teamsUrl);
            }

**Debug Output:** 
CLIENT[example-client]: Connect attempt 2
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 3.15.87.123 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_7.4'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:1276,padLen:10,remainLen:1272
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: KEX algorithm: curve25519-sha256@libssh.org
DEBUG: (local) Host key formats: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa
DEBUG: (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
DEBUG: Host key format: ssh-ed25519
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:188,padLen:8,remainLen:184
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:7,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:7,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: password auth failed
CLIENT[example-client]: Handled Error: All configured authentication methods failed undefined
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
CLIENT[example-client]: Removing listener from ready

**Comment by theophilusx** [comment]
I see a couple of possible issues here.

First, ssh2-sftp-client is not supported under node v14.x. This is
because of a problem with a change in the node network stack which
impacts this ssh2 module which ssh2-sftp-client relies on (See README).
This network change was rolled back in node v15.3 and the ssh2 author is
also re-writing ssh2 (but it is not ready yet). Therefore, for now, you
cannot rely on ssh2-sftp-cleint working under node 14.x

It also looks like your using the Bluebird Promises library. As node has
promises built in, I don't recommend using this library. Much better to
just use node's native Promise implementation.

Finally, from the debug output, it looks like all the authentication
methods have failed. My guess is that if this was working and suddenly
stopped, your rmote sftp server has been upgraded to a newer version and
is using either a newer/different key exchange algorithim or cipher. I
would do the following -

- Use openSSH's sftp CLI and try connecting using the same
username/password to verify the remote server is working and not doing
something like prompting for a password change

- Re-run openSSH's sftp command with verbose debugging turned on. It
should print out what key exchange and cipher algorithms it is using.
Compare that to the output from the ssh2-sftp-client log and see if
ssh2-sftp-client is trying the same key exchange/cipher types. Note that
the names can be slightly different, but close enough you will be able
to work it out. If ssh2-sftp-client is not using the successful
combination used by openSSH's sftp client.

Once you have identified the missing key exchange or cipher algorithms,
add them using the appropriate configuration options (See the
ssh2-sftp-client and ssh2 documentation for details). There are also a
number of closed issues logged against the ssh2 project (and a couple
against the ssh2-sftp-client project) with some valuable
information/examples which can help here. 

If you still cannot get it to work, write a minimal example script which
only uses the ssh2 module and which reproduces the same problem. Log
an issue with the ssh2 maintainer, including the minimal script which
reproduces the issue and see if he can help (as author of ssh2, he has
more knowledge regarding key exchange and cipher algorithms).

If, when writing a simple script which only uses ssh2, you are able to
get connected, let me know. This would mean there is an ssh2-sftp-client
issue rather than an ssh2 issue and I will need to investigate more.
This is unlikely as ssh2-sftp-client really just provides a Promise
based API wrapper around ssh2.

**Comment by mzarzour** [comment]
Hi Tim, we ended up getting this working by first realizing:
1.) Our server was using "keyboard-interactive" mode
2.) The event is on the SSH2 package.
3.) Used this code to setup the even

this.sftp.client.on('keyboard-interactive', (name, descr, lang, prompts, finish) => {
    finish([pw]);
}); 

Thanks again.

**Comment by theophilusx** [comment]
Thanks very much for reporting back and providing that valuable bit of
information. This will help others who have similar issues.

Your sftp server has an unusual configuration and is an example of the
type of things which can trip you up. This is the first example of a
server requiring keyboard interaction I've heard about. Typically,
keyboard interaction is just one of the last methods used after all
others have been exhausted.

I wonder if this means your sftp server would not, for example, support
just ssh key authentication?
