### ISSUE TITLE
Is there an API that can copy files or folders?

### ISSUE THREAD

**Issue by ghost** [theophilusx/ssh2-sftp-client#315]
### Is there an API that can copy files or folders?

I didn't find any API about copy operation. Although the copy can be realized by writing linux commands through SSH connection, it would be great if this library supports it.
I think the basic usage can be like fastGet, but the parameters are changed to two local addresses

**Comment by theophilusx** [comment]
Can you clarify. Are you asking for an API to copy files/directories on
the server or between two servers? There is the uploadDir/downloadDir to
copy files/directories between local host and remote server.

-- 
Tim Cross

**Comment by theophilusx** [comment]
OK, I understand your use case.

Unfortunately, the ssh2 module has no 'native' copy command. This means
that to implement remote copy of files and directories, it is necessary
to implement the functionality at a low level using
readStream/writeStream. For directory copy it is even more complicated
(because it may require a recursive decent into sub-directories).

None of this means it isn't possible, but it would require an
enhancement to the existing API. Happy to consider this for future
release, but I cannot give you a date as to when this will be done
(especially as we are waiting on release of a new ssh2 moudle that is a
complete re-write of the existing one).

Happy to consider pull requests should you want to have a go at adding
remote copy functionality. In the meantime, I will mark this issue as an
enhancement request.

**Comment by SteveFlames** [comment]
In the meantime you could use something like this:
```
async function copyFile (srcFilepath, dstFilepath, options) {
  const sftp = await getConnection() // Connect to sftp
  console.log('Copying file in sftp:', srcFilepath, dstFilepath)
  try {
    await new Promise((resolve, reject) => {
      sftp.client.removeAllListeners('error') // Remove the default error handler which throws an unhandled exception
      sftp.client.on('error', reject)

      const readStream = sftp.sftp.createReadStream(srcFilepath, options)
      const writeStream = sftp.sftp.createWriteStream(dstFilepath, options)

      readStream.once('error', reject)
      writeStream.once('error', reject)
      writeStream.once('finish', resolve)

      readStream.pipe(writeStream)
    })
    console.log('Success copying file in sftp:', srcFilepath, dstFilepath)
  } catch (e) {
    console.error('Error copying file', e)
    throw e
  } finally {
    sftp.end()
  }
}
```

I'll gladly open a pull request whenever I find some time, if that's ok.

**Comment by theophilusx** [comment]
A pull request is always welcome. It would be great if it also includes
some test cases (see the test directory in the repository).

I don't like mixing async/await and Promises in the same method as this
has caused some problems in the past. The real challenge is in handling
the events and associated listeners. Have a look at other functions in
the sources to get an idea of how you can do this.

The basic idea in your code looks correct - essentially what I was
thinking. Not sure if we also need to consider handling file
permissions/modes etc or whether we just default to whatever the server
default is.

It is also good to try and provide meaningful error messages. Some of
the ssh2 error messages are less informative than desirable, so some
work may be necessary to create more informative messages.

**Comment by theophilusx** [comment]
Functionality to make a remote file copy has been incorporated. Have not done the same for directories. However, easy enough to create the directory and then just do file copies. May extend further in the future, but for now, rather keep the module smaller and leave such functionality to client code as it is trivial to implement when needed.
