### ISSUE TITLE
Uploaded files are empty

### ISSUE THREAD

**Issue by arsalanERP** [theophilusx/ssh2-sftp-client#316]
I have an application which monitors a folder on my computer every 5 minutes and checks for any new files that have been uploaded there and uploads them to an sftp.

The issue I am having is that the files that get uploaded are empty. I have downgraded to node version 13.14 and the issue still persists.

**Comment by theophilusx** [comment]
Can you provide a small script which reproduces the problem?

The only time I've seen something similar to this problem, it was due to
failing to wait for a promise to be fulfilled or forgetting to
explicitly return a promise in a promise 'then' chain. This can cause
the call to end() or for the script to exit before the data upload
begins.

Also, be wary of the Array.map type functions. These functions are not
async 'aware'. You can use this family of functions, but additional
effort/precaustions are required. I generally find for..of to be
'cleaner' when you are dealing with async functions.

Finally, if you look in the example directory in the github repository,
you will find a number of simple scripts. You might find them useful to
cannibalise to create a simple test script.

**Comment by arsalanERP** [comment]
```javascript
var sftp = new Client();
const config = {
    host: sftpHost,
    user: sftpUser,
    password: sftpPass,
    port: 22
};
var connection = sftp.connect(config).then(() => {
    var checkTime = new Date(Date.now() - 1000 * 60 * 1);
    fs.readdir(folder,(err,files)=>{
        files.forEach(file => {
            var fileExt = path.extname(file);
            if(fileExt == '.xml'){
                fs.stat(path.join(folder, file), function(err, stats){
                    var fileCreated = new Date(stats.birthtimeMs);
                    var fileModified = new Date(stats.mtimeMs);
                    if(fileCreated > checkTime || fileModified > checkTime){
                        return sftp.fastPut(path.join(folder, file), '/root/SFTP_Quotes/' + file);
                    }
                });
            }
        });
    });
    return sftp.cwd();
}).then(p => {
    console.log(`Connection end. CWD is ${p}`);
    return sftp.end();
}).catch(err => {
    console.log(`Error: ${err.message}`);
});
```

**Comment by AndrewLane** [comment]
> ```js
> var sftp = new Client();
> const config = {
>     host: sftpHost,
>     user: sftpUser,
>     password: sftpPass,
>     port: 22
> };
> var connection = sftp.connect(config).then(() => {
>     var checkTime = new Date(Date.now() - 1000 * 60 * 1);
>     fs.readdir(folder,(err,files)=>{
>         files.forEach(file => {
>             var fileExt = path.extname(file);
>             if(fileExt == '.xml'){
>                 fs.stat(path.join(folder, file), function(err, stats){
>                     var fileCreated = new Date(stats.birthtimeMs);
>                     var fileModified = new Date(stats.mtimeMs);
>                     if(fileCreated > checkTime || fileModified > checkTime){
>                         return sftp.fastPut(path.join(folder, file), '/root/SFTP_Quotes/' + file);
>                     }
>                 });
>             }
>         });
>     });
>     return sftp.cwd();
> }).then(p => {
>     console.log(`Connection end. CWD is ${p}`);
>     return sftp.end();
> }).catch(err => {
>     console.log(`Error: ${err.message}`);
> });
> ```

I believe the forEach is the issue, as described here: https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop

**Comment by theophilusx** [comment]
@AndrewLane Yes, I believe your correct. The Array comprehension
functions like forEach, map, filter, reduce etc are not async aware. One
way to think about it is to ask "Where would I put a statement like
console.log('file xxxx has been uploaded to yyyy')?

Essentially the problem is the script is not waiting for the promises
created in the forEach loop to be fulfilled before calling the end()
function. All those fastPut() calls are 'outside' the promise chain.
The promise chain is actually connect() => cwd() => end(). The end()
will be called as soon as the cwd() promise is fulfilled and as that is a fast
call with little data to return, it happens before the first fastPut()
in the forEach loop has been fulfilled.

This is an example of where the Promise.all() method can be useful. You
could do something like the below (untested, so may have syntax errors)

>  var sftp = new Client();
> const config = {
>     host: sftpHost,
>     user: sftpUser,
>     password: sftpPass,
>     port: 22
> };
> var connection = sftp.connect(config).then(() => {
>     let promiseList = [];
>     var checkTime = new Date(Date.now() - 1000 * 60 * 1);
>     fs.readdir(folder,(err,files)=>{
>         files.forEach(file => {
>             var fileExt = path.extname(file);
>             if(fileExt == '.xml'){
>                 fs.stat(path.join(folder, file), function(err, stats){
>                     var fileCreated = new Date(stats.birthtimeMs);
>                     var fileModified = new Date(stats.mtimeMs);
>                     if(fileCreated > checkTime || fileModified > checkTime){
>                          promiseList.push(sftp.fastPut(path.join(folder, file), '/root/SFTP_Quotes/' + file));
>                     }
>                 });
>             }
>         });
>     });
>     return Promise.all(promiseList);
> }).then(results => {
>     // results is an array with each element being the result from
>     // each fastPut() promise
>     console.log`Results: ${JSON.stringify(results, null, ' ')`);
>     return sftp.cwd();
>}).then(p => {
>     console.log(`Connection end. CWD is ${p}`);
>     return sftp.end();
> }).catch(err => {
>     console.log(`Error: ${err.message}`);
> });
>

With the above change, the Promise chain becomes

connect() => Promise.all() => cwd() => end()

The argument to Promise.all is an array of Promises, each one
representing a fastPut() call generated inside the forEach loop.

There are a few things to consider with this approach -

- All the fastPut() calls are occurring in parallel. Most remote SFTP
servers will likely have some form of connection or rate limiting in
place. If there will only be a handful of *.xml files to upload, this
will generally not be a problem. However, if you had a large number of
new *.xml files, there is a risk you will 'swamp' the connection or
exceed resource limits of the remote sftp server. This could result in
either very poor performance or requests being rejected etc.

- What happens if one of your *.xml files is actually being
generated/written to at the same time your script checks for new files?
There is a risk here that you may upload partial files if your script
runs before the process generating the file has completed.

- You might find the fs.FSWatcher functionality useful.

Finally, a warning about node versions. The ssh2 module has problems
with node v14 due to a change in the network module in that version.
This change was rolled back in node v15.3. As most major changes like
this are first introduced in the development versions (odd numbered
versions), it is also likely that node v13.x also has this issue (I
don't know which versions of node v13 it might have been introduced). I
would therefore recommend using either node v12 or node v16. The author
of the ssh2 module is currently doing a re-write of that module to
address the breaking change in node v14, but it is not yet released.
Last time I tested against it, things were looking good, but I don't
know when the new ssh2 version will be released. To be safe, I would
avoid node v13, v14 and v15 versions less than v15.3.

**Comment by arsalanERP** [comment]
Wow thank you for your comments! I will take these into consideration when I fix my code. I am fairly new to Node so detailed explanations like this are much appreciated!

**Comment by arsalanERP** [comment]
Hi @theophilusx I just tried the code you suggested but the results are always empty. Could it be because the promiseList.push is outside the promise chain?

**Comment by arsalanERP** [comment]
```javascript 
var sftp = new Client();
 const config = {
     host: sftpHost,
     user: sftpUser,
     password: sftpPass,
     port: 22
 };
 var connection = sftp.connect(config).then(async () => {
     let promiseList = [];
     var checkTime = new Date(Date.now() - 1000 * 60 * 1);
     await fs.promises.readdir(folder,(err,files)=>{
         files.forEach(file => {
             var fileExt = path.extname(file);
             if(fileExt == '.xml'){
                 fs.stat(path.join(folder, file), function(err, stats){
                     var fileCreated = new Date(stats.birthtimeMs);
                     var fileModified = new Date(stats.mtimeMs);
                     if(fileCreated > checkTime || fileModified > checkTime){
                          promiseList.push(sftp.fastPut(path.join(folder, file), '/root/SFTP_Quotes/' + file));
                     }
                 });
             }
         });
     });
     return Promise.all(promiseList);
 }).then(results => {
     // results is an array with each element being the result from
     // each fastPut() promise
     console.log`Results: ${JSON.stringify(results, null, ' ')`);
     return sftp.cwd();
}).then(p => {
     console.log(`Connection end. CWD is ${p}`);
     return sftp.end();
 }).catch(err => {
     console.log(`Error: ${err.message}`);
 });
```

Got it working with the following code.

Thanks for all the help!
