### ISSUE TITLE
Error: get: Permission denied - in the middle of streaming a zip file?

### ISSUE THREAD

**Issue by williamsdyyz** [theophilusx/ssh2-sftp-client#320]
I'm attempting to stream a zip file and feed it into a pipeline to unzip the contents, decode and write to a db.
The pipeline works fine when the zip is a local fs readable stream but fails when streaming over sftp.

The failure happens mid-stream, after several files in the zip have been successfully processed. What confuses me is that the error is coming from the FTP stream:

`(node:277294) UnhandledPromiseRejectionWarning: Error: get: Permission denied. /RVB2-0_Infrm_USA/Source/Source_20210524_Full.zip
    at fmtError (/home/dave/git/api/node_modules/ssh2-sftp-client/src/utils.js:53:18)
    at ReadStream.<anonymous> (/home/dave/git/api/node_modules/ssh2-sftp-client/src/index.js:399:18)
    at Object.onceWrapper (events.js:421:26)
    at ReadStream.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

The error happens about 70% of the time. The zip file is not encrypted. I don't understand how "Permission denied" can happen _after_ the file has started downloading?

I'm only just wrapping my head around Node streams, so I figure I'm probably doing something wrong, but I'm not sure how to figure this out. Any advice gratefully received

**Comment by theophilusx** [comment]
What version of node?

What version of ssh-sftp-client?

What platform?

Make sure you are creating new streams for each call to get(). The get()
method copies the data using pipe(). The pipe() command automatically
sends an 'end' signal to all the streams involved in the pipe(). I
suspect your trying to use a stream which has been ended and that is
what is generating the permission denied error.

If you can create a basic script which reproduces the error, I can look
at it to see if anything obvious looks wrong. I use this module to do
exactly what your doing in a daily script without issue, so I know it
can work. However, without a reproducible case to test with, there is
little I can do.

**Comment by williamsdyyz** [comment]
Hi. Thanks for the help. This is about as basic as I can make it while keeping the important bits.

This is Node 12.19.1 and ssh2-sftp-client 6.0.1

The code streams a single .zip file which contains several .csv files. The csv data is inserted into a db table with the same name as the file. The file/table name is logged as it begins processing.

If I remove the line that invokes the db query there is no error
`await this.conn.query(query);`

and the whole pipeline runs a lot faster, so I figure I'm doing something wrong either in setting up the pipeline or the DB writer.




```
import csv from "csv-parser";
import { RouteHandlerMethod } from "fastify";
import { Connection } from "mysql2/promise";
import Client from "ssh2-sftp-client";
import { pipeline, Transform, TransformCallback, Writable } from "stream";
import { Entry, Parse, ParseStream } from "unzipper";
import { promisify, TextDecoder } from "util";
import { mysql } from "../../mysql";

const pipelineAsync = promisify(pipeline);

async function ftpTest() {
    const csvOpts = { separator: "|", strict: false, escape: "\b", quote: "\b" };
    const sftp = new Client();

    await sftp.connect({
        host: "ftp-data.host.com",
        port: 22,
        username: "*********",
        password: "*********",
    });

    const conn = await mysql.getConnection();
    try {
        const unzipStream = Parse({ forceStream: true });
        const sftpPromise = sftp.get("/Source_20210524_Full.zip", unzipStream);

        for await (const e of unzipStream) {
            await pipelineAsync(e, new DecoderStream(), csv(csvOpts), new DbWriter(conn, e.path));
        }
        await sftpPromise;
        await conn.commit();
    } catch (err) {
        console.log("ROLLBACK");
        conn.rollback();
        console.log(err);
    } finally {
        conn.release();
    }
}

class DecoderStream extends Transform {
    t = new TextDecoder("utf-16");
    _transform(chunk: any, encoding: BufferEncoding, callback: TransformCallback): void {
        const s = this.t.decode(chunk, { stream: true });
        callback(undefined, s);
    }
}

class DbWriter extends Writable {
    constructor(private conn: Connection, private tableName: string) {
        super({ objectMode: true });
        this.tableName = this.tableName.slice(0, -4).toLowerCase();
        console.log(this.tableName);
    }

    async _write(chunk: any, encoding: BufferEncoding, callback: (error?: Error | null) => void) {
        let err;
        try {
            const columns = Object.keys(chunk);
            const values = [];
            for (const value of Object.values(chunk)) {
                values.push(value === "" ? null : value);
            }

            const query = this.conn.format("INSERT INTO `db`.?? (??) VALUES ?", [this.tableName, columns, [values]]);
            await this.conn.query(query);

        } catch (e) {
            err = e;
        }

        callback(err);
    }
}

```



The console output looks like this:


```channel_grouping
source

(node:291775) UnhandledPromiseRejectionWarning: Error: get: Permission denied. /Source_20210524_Full.zip
    at fmtError (/home/dave/git/api/node_modules/ssh2-sftp-client/src/utils.js:53:18)
    at ReadStream.<anonymous> (/home/dave/git/api/node_modules/ssh2-sftp-client/src/index.js:399:18)
    at Object.onceWrapper (events.js:421:26)
    at ReadStream.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
<node_internals>/internal/process/warning.js:40
(node:291775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
<node_internals>/internal/process/warning.js:40
(node:291775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<node_internals>/internal/process/warning.js:40

source_genre
source_genre_translation
ROLLBACK

Error: get: Permission denied. /Source_20210524_Full.zip
    at fmtError (/home/dave/git/api/node_modules/ssh2-sftp-client/src/utils.js:53:18)
    at ReadStream.<anonymous> (/home/dave/git/api/node_modules/ssh2-sftp-client/src/index.js:399:18)
    at Object.onceWrapper (<node_internals>/events.js:421:26)
    at ReadStream.emit (<node_internals>/events.js:314:20)
    at emitErrorNT (<node_internals>/internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (<node_internals>/internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {code: 3, custom: true, stack: 'Error: get: Permission denied. /Source_202105…tions (internal/process/task_queues.js:84:21)', message: 'get: Permission denied. /Source_20210524_Full.zip'}
(node:291775) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
<node_internals>/internal/process/warning.js:40
```




[example.zip](https://github.com/theophilusx/ssh2-sftp-client/files/6539416/example.zip)

**Comment by theophilusx** [comment]
Based on the info you have supplied, my guess is your problem is with
the DB write stream. The fact it sort of 'works' if you remove that
component from the pipeline would seem to also suggest this.

I'm not sure how all of that is supposed to work (I have not used mysql
with node, only postgres). As far as SshSftpClient is concerned, you are
passing in a stream and the data is piped to that stream. If that target
is not setup correctly or does hot have the correct permissions, there
is little SshSftpCleint can do.

I would try stepping back a layer and get things to work locally without
using SshSftpClient i.e. use a local readStream to read one of the
zipped files, pass it through your transform stream to unzip it and then
pass it to your DB write stream. Once you have that all working, you
should be able to replace the local file readStream with a call to
sftp.get(). My suspicion is that the stream of data being passed into
the DB write stream is not correct.

In fact, I would start by stepping even further back. Work from the end
backwards. Setup a test which just uses the CSV stream and passes that
to the DB stream - once that is working, then work back to add the unzip
stream, then work back to the file stream.

**Comment by williamsdyyz** [comment]
Oh shoot, I forgot to mention in my previous reply that if I replace the sftp stream with a local file readStream it also works - including the db writer.

So, somehow or another SshSftpClient and my DB writer are not getting along.

**Comment by theophilusx** [comment]
Hmm, that is curious.

Just for interest, when it worked with the local readStream, was it a
zip file exactly the same as the ones you are trying to download?

The only thing that SshSftpClient does with the stream is pass it to
readStream.pipe().

There are some minor tweaks in the master branch which I don't think
will have any impact, but it would be worthwhile testing using it just
to be sure. You can reference the git repository in your package.json to
try this out.

Would it be possible to get a copy of one of the zip files? I need a
sample input to test and see if I can find something which might explain
what is going on.

**Comment by williamsdyyz** [comment]
Yes, it's the exact same zip file that works when read locally. Unfortunately I can't send you a copy - it would violate terms of service - not my data, and not free.

I will give the master branch a shot and report back.

Again, really appreciate you taking the time to help.

**Comment by williamsdyyz** [comment]
OK, so I tried the master branch and guess what? No error! I ran through a few tests and never got a permission denied error.

Everything seems fine except that the promise returned from the `sftp.get` call never resolves or rejects.

I can't send you the zip files, but I'd be happy to try out a test version with extra diagnostics/logging if that would help?

**Comment by theophilusx** [comment]
Thats interesting. The change in the master is that instead of waiting
for a 'finish' signal from the destination stream, the get() method now
fulfills the promise based on an 'end' signal from the source reader
stream. According to the stream spec, the 'end' signal is not raised
until all pipe consumers have consumed all the data from the source
stream or an error occurs.

As the promise is not being fulfilled, this would indicate that no 'end'
event is being raised. The source stream only raises the end event once
all the data it sends into the pipe has been consumed. I'm wondering now
if there is an issue with the mysql stream not consuming all the data
being sent.

You mentioned that the source files are zip archives containing multiple
CSV files. If you setup the pipeline to write the contents to a local
file rather than try to pipe it into mysql, do you get multiple files on
the local filesystem? Are the local files the exact same size as files
generated if you just use a CLI sftp program to download the zip archive
and manually unzip it?

The ssh2 author has nearly completed a full re-write of the ssh2 module,
including all the stream handling. He reported recently that he expects
to release the new version 'within days'. It would be interesting to
test against that version as well. I have an updated version which works
against that new ssh2 version in a branch in the repository, but I need
to port across the get() event handler changes before it can be used to
test your use case. Unfortunately, I'm about to lose Internet access for
24 hours due to local network maintenance, so I may not get time to do
this for a couple of days. Once I have, I'll update the branch and send
you details so that you can test against it to see if that makes any
difference. In the meantime, it would be good if you can replace your
mysql stream wiht one that just writes the data to multiple files and
verify everything gets consumed and the get() promise resolves.

**Comment by williamsdyyz** [comment]
That sounds like a plan. I'll come back with the results of writing to files. Enjoy your disconnected time :)

**Comment by williamsdyyz** [comment]
I have some results for you.

The writing to file test worked fine - all the data transferred correctly.

However your comment about the "end" vs "finish" signal got me thinking.

It turns out that the unzip package I was using (unzipper) has some issues with async iterators - in fact, it never seems to emit the end signal if you use them.  So I tried _not_ using async iterators and things worked much better except unzipper was logging internal errors. Both these problems are already logged to the project in github but there doesn't seem to be much activity.

So I switched to "unzip-stream" instead. Now ssh2-sftp-client MASTER works flawlessly whereas 6.0.1 still has the original "Permission denied" problem.

It seems to me that what you're doing in MASTER is more appropriate/correct so I think we can consider the issue solved.

Thanks for helping me figure this out and thanks for creating a really useful sftp package!

When do you thing you will be rolling the master updates into a release?

**Comment by theophilusx** [comment]
Thanks. That was really useful information.

A new version of ssh2 was finally released last weekend. As soon as the
dust settles, I will release a new version of ssh2-sftp-client which
depends on this new version and has the changes in master (there are a
couple of other changes and I need to cleanup the documentation).

I was going to release a new version later this week, but I've just
found out I won't have Internet access next week, so I am a bit
reluctant about publishing a new version where I cannot push fixes
quickly and so may wait until I have full access back again. I will get
the master fully updated this week and ready to push, so HEAD will be a
proper reflection of what the new release will be.

**Comment by williamsdyyz** [comment]
I am in no hurry, so go when you're comfortable doing it
