### ISSUE TITLE
Files not uploaded consistently

### ISSUE THREAD

**Issue by ubi23** [theophilusx/ssh2-sftp-client#323]
I am using this library to upload automatically files to a remote sftp server. I'm always uploading two files each day one after the other in an automatic way. However, there are days when the second file is not uploaded entirely, i.e. instead of uploading `662,338 bytes` it only uploads `66,879 bytes`. First I was using the `fastPut` function to upload and this behaviour was more frequent, but now that I'm using the `put` function it happens from time to time and I don't understand the reason for it.   Are you aware of any issues with this functionality?

**Comment by theophilusx** [comment]
What version of ssh2-sftp-client?

What version of node?

There was an issue impacting node v14.x and ssh2 0.8.9 (used by
ssh2-sftp-client versions < 7.0.0). The issue, triggered by a change in
the node network stack in node v14 was rolled back in node 15.3. Since
then, ssh2 has had a complete re-write so that ssh2 v1.1.0 avoids this
issue for all supported node versions (node >= v10). Version 7.0.0 of
ssh2-sftp-client is based on ssh2 v1.1.0 and there are no known issues
with put or fastPut.

**Comment by ubi23** [comment]
using ssh2-sftp-client version 6.0.1 and node 14.x on an AWS Lambda function. Is it possible that there were also issues with the `stat` function...basically I'm trying to retrieve the file size of the files uploaded to check if they match the size of the local files, what happens is that I get the file size of the first file uploaded correctly but for the second file I get `0`. Not sure if the error is in the function or in the files.
<br>
I'll try the new version and update this issue if I'm still facing the same problems.

**Comment by theophilusx** [comment]
ssh2-sftp-client 6.0.1 (and all versions based on ssh2 0.8.9) do not
work correctly with node version 14.x. If you want to use node v14, you
must use ssh2-sftp-client 7.0.0 (which is based on ssh2 1.1.0).

**Comment by theophilusx** [comment]
It is hard to provide anything specific without some code which
demonstrates the issue. Every similar issue reported has turned out to
be due to errors in client code. The two most common mistakes are not
returning a promise in a promise chain or a missing await in an
async/await based client. Essentially, what happens is that because the
code is not correctly waiting for the promise returned from a call to
the API to be fulfilled, the code runs the end() call before the file
upload has been completed. Often, things will appear to work when you
have smaller files and a fast network and then fails with larger files
or when the network is running a bit slower. Things work when your
'lucky' and the upload has completed before the end() call and fail
otherwise.

To provide anything more specific, I would need

- node version
- platform (linux, windows, mac, wsl etc)
- ssh2-sftp-client version
- Sample code which demonstrates the problem (even if not every time).

**Comment by ubi23** [comment]
so I'm running this as a chron job in AWS lambda:
node: 14.x
ssh2-sftp-client: 7.0.0

code is as follows:
worker.js
```
const logger = require('../utils/logger.js');
const sftpClient = require('../lib/sftp-connection');
const { preprocess } = require('../lib/index');


module.exports.handle = async (event, context) => {

  const date = new Date();

  // connect to the remote SFTP server
  try {
    await sftpClient.connect();

    logger.log.info('connected_successfully_to_sftp_server');
  } catch (err) {
    logger.log.error( {err}, 'error_connecting_to_sftp_server');

    return {
      statusCode: 500,
      message: `Error occurred while connecting to the sftp server: ${err}`
    }
  }
  
  
  // download files
  let downloadedFilesLocalPath;
  try { 
    
    downloadedFilesLocalPath = await sftpClient.download({date, ...areFilesPreprocessed});

    if (false === downloadedFilesLocalPath) {      

      await sftpClient.end();

      logger.log.info('connection_ended');      

      return {
        statusCode: 200, // probably return some other status code        
      }
    }

  } catch (err) {

    await sftpClient.end();
    logger.log.info('connection_ended');

    return {
      statusCode: 500,
      message: `Error occurred while downloading files: ${err}`
    }
  }


  // download complete, time to do preprocessing
  try {

    // preprocess me2me file
    if (downloadedFilesLocalPath.me2me) {
      await preprocess(downloadedFilesLocalPath.me2me);
    }
        
    // preprocess standard file
    if (downloadedFilesLocalPath.standard) {
      await preprocess(downloadedFilesLocalPath.standard);      
    }

  } catch (err) {

    await sftpClient.end();
   
    return {
      statusCode: 500,
      message: `Error occurred while processing the files: ${err}`
    }
  }
  

  
  try {
    
    // upload the preprocessed files
    await sftpClient.upload({date});

    await sftpClient.end();

    // send positive response
    return {
      statusCode: 201,
      message: 'Files uploaded successfully!',
    };

  } catch (err) {

    await sftpClient.end();

    return {
      statusCode: 500,
      message: `Error occurred while uploading the files: ${err}`,
    };
  }
  
};

```

then inside sftp-connection.js the upload function

```
/**
 * Upload files to the SFTP server
 */
 module.exports.upload = async (params) => {

  const { date } = params;  
  const year = date.slice(0, 4);
  const month = date.slice(4, 6);
  const day = date.slice(6, 8);
  

  // set remote and local file paths
  const localPreprocessedMe2MeFile = `/tmp/me2me_payments_${date}_preprocessed.csv`;
  const localPreprocessedStandardFile = `/tmp/standard_payments_${date}_preprocessed.csv`;
  
  const remotePreprocessedMe2MeFile = `/me2me_payments_${year}-${month}-${day}_preprocessed.csv`;
  const remotePreprocessedStandardFile = `/standard_payments_${year}-${month}-${day}_preprocessed.csv`;
  

  // check if the files have been preprocessed and exist locally
  let me2meLocalFileSize;
  let standardLocalFileSize;
  const uploadPromises = [];
  try {

    // check if local standard file exist
    if (fs.existsSync(localPreprocessedStandardFile)) {
      standardLocalFileSize = fs.statSync(localPreprocessedStandardFile);

      logger.log.info( {standardLocalFileSize}, 'standard_preprocessed_file_to_upload');

      let data = fs.createReadStream(localPreprocessedStandardFile);
      uploadPromises.push(sftp.put(data, remotePreprocessedStandardFile));

    } else {
      logger.log.warn( {localPreprocessedStandardFile}, 'standard_file_to_upload_does_not_exist_locally')
    }



    // check if local me2me file exist
    if (fs.existsSync(localPreprocessedMe2MeFile)) {
      me2meLocalFileSize = fs.statSync(localPreprocessedMe2MeFile).size;
      
      logger.log.info( {me2meLocalFileSize}, 'me2me_preprocessed_file_to_upload');

      let data = fs.createReadStream(localPreprocessedMe2MeFile);
      uploadPromises.push(sftp.put(data, remotePreprocessedMe2MeFile));

    } else {
      logger.log.warn( {localPreprocessedMe2MeFile}, 'me2me_file_to_upload_does_not_exist_locally')
    }


  } catch (err) {
    throw err;
  }

  

  // upload the preprocessed files to the sftp server
  const uploads = await Promise.all(uploadPromises);
  
  // all good, log the status of the uploads
  uploads.forEach( value => logger.log.info( {value}, 'successful_upload'));

  
  return;
}
```

**Comment by ubi23** [comment]
the issues is that the first file gets uploaded entirely but the second only few KBytes get uploaded...so there's no trace of errors happening

**Comment by theophilusx** [comment]
The first thing you should do is upgrade ssh2-sftp-client to 7.0.4. The
7.x version is based on a new version of ssh2 (a complete re-write of
ssh2) and therre has already been some important bug fixes since the
release of 7.0.0.

Your code does not show what is in the connect configuration object
passed to client.connect(), but I would add a debug function to generate
low level debug statements to see if that provides some more details.

It is hard to really follow exactly what your code is doing due to the
level of abstraction you have. However, I notice you seem to have
multiple paths which will result in sftpClient.end() being called. This
makes me suspicious your bug may be due to the end() method being called
unexpectedly (i.e. when still waiting on put/get calls to be fulfilled).
I would refactor the code so that there are only 2 (or even 1) places
where end() is called (normal end of processing and when there is an
error).

I would also reconsider your basic design where your
uploading/downloading multiple files in parallel. While the author of
ssh2 has stated this is supported, I've found that reliability seems to
depend on the sftp server. I've also found you don't see much (if any)
performance improvement overall. Doing multiple get/put concurrently
tends to just flood the socket connection and any speed improvement is
lost with context switching. I would consider refactoring your code to
do the upload/download in a serial model and verify that is working and
then consider the best way to add concurrent calls if that is warranted.
My suspicion is you have complicated the code with little actual
improvement in overall performance (this is a guess as it will also
depend on the size of your files, number of files and network speed
etc).

I also think it is good to keep things as simple and straight-forward as
possible when using services like AWS and lambda. These services are not
the same as running just within a 'normal' node environment. There are
differences and optimisations implemented by AWS to improve efficiency
of their environments and use of resources, especially with respect to
networking.

If you are actually only uploading/downloading files rather than buffers
or streams of data, I would also consider using fastGet()/fastPut() as
these tend to be faster and will automatically exploit supported
concurrency based on what the remote sftp server can support. The
put()/get() methods are great when you do need to pass in buffers or
streams of data, but when your just passing in filenames,
fastput/fastget are better.

**Comment by theophilusx** [comment]
I notice you don't seem to check what is in the array returned by
Promise.all(). If any of the promises are rejected, you need to look at
the contents of that array to see why they were rejected.

Every time someone has reported an error like this, it has turned out to
be because the end() method was being called before all promises were
fulfilled. I suspect this is likely the case with your code as well and
would be verifying that end() is never called before all promises have
been fulfilled. For example, you don't want to just call end() when a
promise is rejected if you have multiple promises waiting to be
fulfilled as this will also prevent the other promises from completing
because end() ends the whole connection.

**Comment by ubi23** [comment]
thanks for the detailed response. Regarding the latter point, I believe I am checking what the Promise.all() is returning as follows:

```
// upload the preprocessed files to the sftp server
  const uploads = await Promise.all(uploadPromises);
  
// all good, log the status of the uploads
  uploads.forEach( value => logger.log.info( {value}, 'successful_upload'));
```

And it's always returning a positive message:

```
{
    "level": "info",
    "value": "Uploaded data stream to 210032/preprocessed_payments/standard_payments_2021-09-27_preprocessed.csv",
    "msg": "successful_upload"
}
```

Regarding the other points, yes I'll try to simplify the logic and upload one file at a time and see what happens. In the past I used `fastPut()` in version 6.x of ssh2-sftp-client and it was more unreliable than put is now for me (every other day the file was not entirely uploaded, just few bytes).

**Comment by sheltonsharon** [comment]
Hi @ubihot , was the issue resolved completely by any chance? we are also facing the same issue

**Comment by ubihot** [comment]
@sheltonsharon I've been uploading the files without Promise.all and it's been working fine since

**Comment by ubihot** [comment]
> @sheltonsharon I've been uploading the files without Promise.all and it's been working fine since

for ref, using `ssh2-sftp-client ^9.1.0`

**Comment by theophilusx** [comment]
Upgrade to ssh2-sftp-client 10.0.3

- It depends on ssh2 1.15, which has the fix for the CVE discovered last
year for ssh protocol. There are also likely other improvements and as
it is the 'base' of the whole package, best to stay up-to-date.

- It has a fix for the downloadDir/uploadDir bug which caused failures
when dealing with directories of large number of files.
