### ISSUE TITLE
ERR_BAD_PATH Issue when running

### ISSUE THREAD

**Issue by Klariff** [theophilusx/ssh2-sftp-client#326]
Greetings!

I was using the library with the following implementation:

![image](https://user-images.githubusercontent.com/30582970/123529493-49792480-d6b6-11eb-84b1-fb8d8c92c86a.png)

Where the actual calling of the put() function occurs at line 75. However, I constantly get this error when running:

![image](https://user-images.githubusercontent.com/30582970/123529465-00c16b80-d6b6-11eb-8f3d-c4f4d3ef04e6.png)

I'm currently using NodeJS v16.4.0

Thanks in advance!

**Comment by theophilusx** [comment]
That error is telling you that you have a bad file path in the put()
call. Looking at it, my guess is that the path for the source file to
upload is incorrect. It appears your on a Windows system and that path
does not look correct for windows i.e. you have / where you probably
should have \.

Getting paths correct can be a little challenging, especially when you
are running on windows and uploading to the remote sftp server. Paths
for the sftp server are all made using '/' as the directory separator,
but paths which reference the local system need to be standard platform
specific paths i.e. for windows, the directory separator is '\'. So, for
put(), the first argument should be using '\' because that is a windows
path, but the second arguement (destination for the file) should be '/'
(sftp file separator).

-- 
Tim Cross

**Comment by Klariff** [comment]
Thanks for the quick response!

However I tried to change the orientation of the / and it still doesn't work for me.

**Comment by theophilusx** [comment]
Is it the exact same error message? Can you show me the error message
now you have changed the directory separator?

Can you open a file using just node fs methods using exactly the same
path? For the put() method, the library just uses fs.createReadStream to
access the source file. I would try a simple node script that just
attempts to use that using only standard node functgions (no
ssh2-sftp-client module). This may provide you with more error
information. 


-- 
Tim Cross

**Comment by theophilusx** [comment]
As there has been no response for 3 weeks, closing this issue for now.

**Comment by Klariff** [comment]
Looks like there was a security issue with the sftp file server itself, thanks anyway!
