### ISSUE TITLE
Clarification on the SFTP packet messages

### ISSUE THREAD

**Issue by madushankaf** [theophilusx/ssh2-sftp-client#341]
Hi @theophilusx,

Could you kindly let me know my understanding of the methods and their corresponding SFTP Packet Type is correct?

| Method        | SFTP Packet Type           | 
| ------------- |:-------------:|
| connect()      | SSH_FXP_OPEN                3|
| put()     | SSH_FXP_WRITE               6      |  
| end() | SSH_FXP_CLOSE               4     | 

refer: https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-4.3

Appreciate it if you could confirm this! Thanks in advance.

**Comment by theophilusx** [comment]
I believe your understanding is correct. However, you would need to
verify this with the ssh2 maintainers. All the low level ssh/sftp
communications is handled by the ssh2 package. Note that there
is not always a 1-to-1 mapping between ssh2-sftp-client and ssh2
methods. For exmaple, fastGet/fastPut is 1-to-1 because ssh2 provides
those methods. However, put() is not because ssh2 does not have a put
method. It does provide a createWriteStream() method, which is what
put() uses 'under the hood'. Asking them about put() would therefore not
mean anything to them.

**Comment by madushankaf** [comment]
Thanks for the clarification @theophilusx could you please tell me what ssh2 method maps to the **end()**  method of ssh-sftp-client ?

I specifically want to know of it. Then I can check the respective packet type with them!

Thanks a lot

**Comment by madushankaf** [comment]
Never mind  found it thanks
