### ISSUE TITLE
fs.accessSync has diffrent errno between windows and linux

### ISSUE THREAD

**Issue by suboy** [theophilusx/ssh2-sftp-client#345]
In utils.js  haveLocalAccess

`function haveLocalAccess(filePath, mode = 'r') {
  const accessMode =
    fs.constants.F_OK | (mode === 'w') ? fs.constants.W_OK : fs.constants.R_OK;

  try {
    fs.accessSync(filePath, accessMode);
    const type = localExists(filePath);
    return {
      status: true,
      type: type,
      details: 'access OK',
      code: 0,
    };
  } catch (err) {
    if (err.errno === -2) {   //windows: -4058
      return {
        status: false,
        type: null,
        details: 'not exist',
        code: -2,
      };
    } else if (err.errno === -13) {
      const type = localExists(filePath);
      return {
        status: false,
        type: type,
        details: 'permission denied',
        code: -13,
      };
    } else if (err.errno === -20) {
      return {
        status: false,
        type: null,
        details: 'parent not a directory',
      };
    } else {
      throw err;
    }
  }
}`

**windows:**
> fs.accessSync('./asawerawew')
Uncaught Error: ENOENT: no such file or directory, access './asawerawew'
    at Object.accessSync (fs.js:220:3) {
  errno: -4058,
  syscall: 'access',
  code: 'ENOENT',
  path: './asawerawew'
}

**linux:**
> fs.accessSync('./asdagfa')
Uncaught Error: ENOENT: no such file or directory, access './asdagfa'
    at Object.accessSync (fs.js:220:3) {
  errno: -2,
  syscall: 'access',
  code: 'ENOENT',
  path: './asdagfa'
}

**Comment by theophilusx** [comment]
Are you referring to the different in errorno values? If so, I would
guess that is a platform difference. The hasLocalAccess() function just
returns whatever the platform generates and the platform generates that
value in low level underlying file system code.

What happens if on the windows platform, you call the function with a
windows path rather than a unix path i.e.

hasLocalAccess('.\asawerawew')

instead of

hasLocalAccess('./asawerawew')

While the sftp protocol 'normalises' file paths so that you don't have
to worry about platform differences, when dealing with local resources,
you have to deal with local differences in your client code.

The one change I probably should make is to return an object with status
false and details set to the error message instead of throwing the error
for the 'default' case. However, this won't affect errorno and you could
still see platform differences.

**Comment by suboy** [comment]
In windows, the fastGet() function shrow an error at 'const localCheck = haveLocalCreate(localPath)'
maybe, you could use:
`case -2:
case -4058:
        return {
          status: false,
          type: null,
          details: 'not exist',
          code: -2,
 };`

Error: fastGet: ENOENT: no such file or directory, access 'D:\work\course_svn\egret\ddbe10d112be730e1902769a5db2ab0d\manifest.json'
    at fmtError (D:\work\langlang-cli\node_modules\ssh2-sftp-client\src\utils.js:55:18)
    at SftpClient.fastGet (D:\work\langlang-cli\node_modules\ssh2-sftp-client\src\index.js:600:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async SftpClient.downloadDir (D:\work\langlang-cli\node_modules\ssh2-sftp-client\src\index.js:1178:11) {
  code: 'ENOENT',
  custom: true
}

**Comment by theophilusx** [comment]
What I will do is change the function so that it doesn't throw anything.
Instead, if there is an error, it will just return {state: false,
details: err.message, type: null}. This will avoid having to worry about
different error codes - all we really care about is that state is not
false. I was going to do this anyway, but held back as I usually don't
like catching an 'unknown' error and then not somehow reporting it back.
In this case, it is probably reasonable. To be honest, I didn't want to
add any local checks, but I was just getting too many issues from users
who were reporting errors when in fact, it was just errors in their
client code and/or problems with access to local resources/files. The
idea was to try and provide more meaningful errors - unfortunately, on
some platforms, especially windows, the error information returned is
useless e.g. returning just "Failure" as the error message. 

It is possible there could be other issues running on windows. I don't
use windows at all and only have limited access to a windows system for
testing. I will push up the change either later tonight or tomorrow and
you can try running from the master branch to see if you find any other
issues.

**Comment by theophilusx** [comment]
I've pushed the changes to master. Please try it out and see how it goes for you.

**Comment by suboy** [comment]
It works, thanks.

**Comment by theophilusx** [comment]
OK. I want to hold off on pushing a new version as I think a new version
of ssh2 is about to be released (fixing an issue with packet lengths on
some platforms). I would prefer to wait until that is released rather
than push multiple versions in a short period.

Would a delay of 1 week be too much of a problem for you?

(I will push a new version regardless in 1 week).

**Comment by suboy** [comment]
No problem.

**Comment by theophilusx** [comment]
New version pushed which is based on ssh2 1.4.0.

**Comment by Axent96** [comment]
I have the error in v7.2.2:

Error: exists: No SFTP connection available
    at fmtError (/.../node_modules/ssh2-sftp-client/src/utils.js:55:18)
    at haveConnection (/.../node_modules/ssh2-sftp-client/src/utils.js:319:20

**Comment by theophilusx** [comment]
That error is telling you you don't have an sftp connection. You need to
diagnose why you don't have an sftp connection.
