### ISSUE TITLE
Is there an equivalent of noErrorOK on get calls?

### ISSUE THREAD

**Issue by unclewiggily** [theophilusx/ssh2-sftp-client#350]
We don't want to throw a fatal error if we can't find a file on a `.get()` call. Ideally, we'd use a `noErrorOK` flag like the delete operation has. Based on the documentation, there isn't a `noErrorOK` flag for get calls. 

What is the best way to prevent fatal errors if a file can't be found on the get call?

We could add a `catch()` to the operation, but that would prevent all fatal errors. We don't want to suppress all errors–just file-not-found errors.

Let me know if you have any suggestions!

Thank you,
Uncle Wiggily

**Comment by theophilusx** [comment]
Two possible suggestions spring to mind -

1. You can test for the type of error in the catch() and do nothing if
it is a file not found error, re-throw the error if it is something else

2. Do an exist() check before calling get(). Probably a bit cleaner, but
means there is an additional sftp call for each file retrieved.

**Comment by unclewiggily** [comment]
Hey @theophilusx thanks for the quick response!

Feel free to mark this as resolved–I implemented something similar to your first suggestion.

I am curious about the best way of checking if the error is specifically a "file not found" error?

I logged the error object and I didn't see anything I could rely on to identify this specific error. 

This is what the error I logged looked like: 
```
{
  Error: get: Failure {filename}
  at fmtError (/{filePath}node_modules/ssh2-sftp-client/src/utils.js:55:18)
  at ReadStream.rdr.once (/{filePath}node_modules/ssh2-sftp-client/src/index.js:483:18)
  at Object.onceWrapper (events.js:273:13)
  at ReadStream.emit (events.js:182:13)
  at ReadStream.EventEmitter.emit (domain.js:441:20)
  at sftp.read (/{filePath}node_modules/ssh2/lib/protocol/SFTP.js:3314:12)
  at Object.cb (/{filePath}node_modules/ssh2/lib/protocol/SFTP.js:1810:18)
  at 101 (/{filePath}node_modules/ssh2/lib/protocol/SFTP.js:2475:11)
  at SFTP.push (/{filePath}node_modules/ssh2/lib/protocol/SFTP.js:271:11)
  at CHANNEL_DATA (/{filePath}node_modules/ssh2/lib/client.js:525:23)
  at 94 (/{filePath}node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
  at Protocol.onPayload (/{filePath}node_modules/ssh2/lib/protocol/Protocol.js:2021:10)
  at GenericDecipherNative.decrypt (/{filePath}node_modules/ssh2/lib/protocol/crypto.js:1274:26)
  at Protocol.parsePacket [as _parse] (/{filePath}node_modules/ssh2/lib/protocol/Protocol.js:1990:25)
  at Protocol.parse (/{filePath}node_modules/ssh2/lib/protocol/Protocol.js:292:16)
  at Socket.sock.on (/{filePath}node_modules/ssh2/lib/client.js:712:21),
 code: 4,
 custom: true
}
```

**Comment by theophilusx** [comment]
This is one of the problems associated with using error filtering. There
is no standard for how errors are reported and different servers or
different platforms will report the same error with different error
messages and error codes. In the example you show, the 'Failure' and
error.code of 4 are examples of an error being generated by the ssh2
module when it tries to create the readStream. It is exactly the sort of
error I hate because ti is too generic and could represent various
classes of error. That same error code (in this case 4) and message will
likely be used for different errors.

How you deal with these types of problems really depends on your use
case, preferred programming style and error handling strategy for your
application. My preferred style and strategy is to treat any error as an
exception - something which was not expected to occur. As a file not
being found is something I would expect to occur on occasion, my
preferred approach would usually be to actually do an exist() check
before calling get() and taking some specific action when file does not
exist. I use errors for those unexpected things I did not or could not
plan for or where I want to respond in the same way regardless of the
error (for example, log it and move on or log it and exit or just exit). 

When I do use error filtering, I will tend to prefer to filter on the
error.code property rather than the message. This does tend to be a
little more reliable, but again, as there is no standard here, different
platforms and different servers may return different error.code values
for the same error or the same value for different errors.

Personally, I would re-think your original position of just wanting to
ignore file not found errors. Is that really the right strategy? What
exactly does it mean? For example, if one of the directories in the path
does not exist, is that the same as the target file not existing (both
are 'file not found' errors)? If the file exists, but the login user
does not have read permission, is that treated the same as a file not found? Is
just ignoring an error because the file does not exist actually a good
strategy? Would it be better to do a listing of the parent directory and
then based the get() on the list of files returned from calling list()?
Will the code be clearer (from an intention perspective) if you actually
do an exists() call before calling get() to verify the file exists
first? Would doing a stat() call be even better because we could verify
access permissions or creation/modified date? etc. What would be most
useful to the users of your code? Sometimes, you might decide that after
an error is thrown, you catch it and then interrogate the remote server
to determine the specific cause of the error so that you can report with
sufficient detail to make it easier for the user or client code to take
the most appropriate action.  

This isn't the straight-forward answer you were probably hoping for, but
error handling is too use case specific for anything more concise. It
really depends on your requirements.

**Comment by unclewiggily** [comment]
On error codes, I completely agree with you. There is no good standard. And it's difficult when you're building off of another library especially when it's an event-based error system as you mention in your docs.

On your approach, yup that makes complete sense. The use case I was proposing isn't as simple as I originally thought: a file not found error is still too vague of an error to try to explicitly ignore. As you say, it could be the result of a valid error you'd want to throw like an incorrect path, a typo, etc. 

Thank you for building and maintaining this project and thank you again for having such quick responses in your support.

We really appreciate it!
