### ISSUE TITLE
avoid calling fsetstat

### ISSUE THREAD

**Issue by brianzinn** [theophilusx/ssh2-sftp-client#357]
Great library.  I am trying to upload a file, but not try to set any attributes afterwards.  I have gone through your library and it is handing off to ssh2 here:
https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L703

So, if I look at the calling code here, which will set mode to '0o666' (unless we send a mode in options):
https://github.com/mscdex/ssh2/blob/master/lib/protocol/SFTP.js#L3579
That it turn calls open, which attempts an `fchmod` it looks like:
https://github.com/mscdex/ssh2/blob/master/lib/protocol/SFTP.js#L3675

My shortened debug logs of a PUT operation with a stream and no options looks like this:
```
CLIENT[sftp]: exists -> /Inbound/file-104.txt
CLIENT[sftp]: stat -> /Inbound/file-104.txt
DEBUG[SFTP]: Outgoing: Writing STAT
...
DEBUG[SFTP]: Parser: Response: STATUS
CLIENT[sftp]: stat error Cannot find message [/Inbound/file-104.txt] code: 2
...
CLIENT[sftp]: exists -> /Inbound
CLIENT[sftp]: stat -> /Inbound
DEBUG[SFTP]: Outgoing: Writing STAT
...
DEBUG[SFTP]: Parser: Response: ATTRS
CLIENT[sftp]: stats <-  {
 "mode": 12345, // this is the directory mode
 ...
 CLIENT[sftp]: put remote path info  {
 "path": "/Inbound/file-104.txt",
 "type": false,
 "valid": true
}
CLIENT[sftp]: put -> /Inbound/file-104.txt
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
CLIENT[sftp]: put source is a stream
...
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:4,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: HANDLE
DEBUG[SFTP]: Outgoing: Writing FSETSTAT
...
DEBUG[SFTP]: Parser: Response: STATUS
DEBUG[SFTP]: Outgoing: Writing SETSTAT
...
DEBUG[SFTP]: Parser: Response: STATUS
DEBUG[SFTP]: Outgoing: Writing WRITE
DEBUG[SFTP]: Parser: Response: STATUS
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG[SFTP]: Outgoing: Writing CLOSE
```

I just want to confirm that I cannot set an option on your side to avoid the underlying library to be writing FSETSTAT (fchmod calls fsetstat):
https://github.com/mscdex/ssh2/blob/master/SFTP.md#sftp-events

The error on the server log is this:
`This server does not support operations to modify file attributes. File attributes for [/Inbound/file-104.txt] were not modified.`

My initial feeling is the downstream library needs an opt-out mechanism.  Do you have any advice here or do you feel this is a request better served in ssh2 library?

**Comment by theophilusx** [comment]
I think your analysis is probably correct and it will be necessary to
ask about this with the ssh2 maintainer.

My suggestion is to write a simple example script which just uses ssh2
which demonstrates the issue you are encountering. If you look in the
'validations' directory of the ssh2-sftp-client repo, you will see a
handful of exmaple scripts which just use ssh2. You should be able to
adapt one of these to reproduce the issue you are seeing. Create an
issue and include that script as an example with explanation of the
issue. If you cannot trigger the issue using just ssh2, let me know.
There is a slim possibility that passing in null rather than an empty
object might avoid the problem (looking at the ssh2 code, I don't think
this is the case). 

The possible challenge is that I think the default mode used by node
when creating a write stream is o666. If this is not the default mode of
files on the remote server, then it might be necessary for the ssh2 code
to pass in whatever the right 'default' is, but I'm not sure how ssh2
can determine what that is and it may not help anyway.

One possible, but rather dirty, work-around might be to add an error
handler which ignores the error. Not sure if that would work or not. and
it might be difficult to ensure only the specific error you want is
ignored while others are raised - would be messy and fragile I suspect. 

Something else you might try is to use the fastPut() method. This uses a
different technique to upload the file (and can take advantage of
concurrent processing of the data stream if supported by the remote
server). In addition to often being faster, it might not have the same
problem as using put(). The limitation with using fastGet is that you
cannot pass in a stream, only a filepath. Not a great solution if your
actually processing the data in the source file in some way, but ideal
if all your doing is uploading the files and don't actually need to
process file contents locally.

**Comment by brianzinn** [comment]
yes this can be closed - thanks for reminder.  i'll probably do a PR upstream for opt out behaviour when I get a chance.
