### ISSUE TITLE
(SSH) Channel open failure: open failed

### ISSUE THREAD

**Issue by incubux** [theophilusx/ssh2-sftp-client#36]
(SSH) Channel open failure: open failed
Why is this happening?
thanks for helping

**Comment by jyu213** [comment]
sorry.. 
May be you can search https://github.com/mscdex/ssh2 for help.

**Comment by edencorbin** [comment]
I get this same error. Interestingly, everything works great, and I make many uploads, but then I will get this error out of the blue. I thought it was because I wasn't closing my connections (but I put a manual close in) and still see this issue, again after days and successful uploads.... what could cause this... eventually? Why does a process restart fix it?

My general code format is as follows:

```
            return sftp.connect(sftpconfig).then(() => {
              return sftp.put(localPath, BASIC_URL + file_name).then(() => {
                  return sftp.end().then(() => { //close the connection
                    return res.redirect('/');
                  });
              });
            });
```

**Comment by theophilusx** [comment]
The module has moved on a lot since this issue was logged and the API is quite different. Therefore I'm going to close this issue if there are no objections. If it is still a problem, please add a comment. Some sample code would help in reproducing the issue, plus don't forget to specify module version and node version.
