### ISSUE TITLE
Reuse connection in AWS Lambda?

### ISSUE THREAD

**Issue by QAnders** [theophilusx/ssh2-sftp-client#364]
Thanks for the superb implementation!

A question, just to make sure... From the looks of the logs the it seems all fastPut()'s are done in the same connection but our partner in the other end has complained we open too many connections so wanted to check how the connection and number of connections are handled.

We have files in a AWS S3 Bucket and an AWS Lambda (Node12) that reads the files, writes them to the `/tmp` directory and I then loop through each file and call a function with  `sftp.connect().fastPut()` in it.

I think the connection is kept and there is no new connection (handshake) being done, correct?
How many concurrent "data connections" would be opened?

**Comment by theophilusx** [comment]
If your calling connect each time you call fastPut(), your creating a
new connection for each file upload. You don't want to do this. Instead,
just create one connection and then loop over the list of files, calling
fastPut(). The difference with fastPut over normal put() is that
fastPut() will try to improve the transfer speed by breaking the file up
into parallel upload streams. The number of streams is server dependent.
You can specify the number of concurrent connections in the call to
fastPut(), but this is only a request number - the server can ignore it.

I find async/await much easier and cleaner when you want to loop and
call the fastPut() promise. Alternatively, push the result from each
call into an array and then call Promise.all() to ensure you do wait
until all fastPut() calls have resolved. Be very careful using array
comprehension functions like .forEach() as these are not asynchronous
aware - as a result, the loop will end and the function will terminate
before the fastPut() promises have resolved. I would use a normal for
loop with an await fastPut() call in the body or I would push the
results of each fastPut() call into an array and then use Promise.all()
as the return value for the enclosing function so that you can use it in a Promise
chain.

**Comment by QAnders** [comment]
Thanks for the feedback @theophilusx!

I did have some issues getting the async stuff sorted but I am a friend of `p-iteration` (https://www.npmjs.com/package/p-iteration) which seems to be doing a great job here!

I'll share a bit of my code if someone else stumbles upon this...
We read a bunch of PDF's from a AWS S3 Bucket and copy them over to `/tmp` on an AWS LAmbda function and then put the file names into an array, `fileList`, and call `putSFTPObject()`:
```
const SFTPClient = require('ssh2-sftp-client');
const fs = require('fs').promises;
const { forEach } = require('p-iteration');

async function putSFTPObject(fileList) {
  const path = '/to/some/directory';
  const sftp = new SFTPClient();
  return sftp.connect({
    host: process.env.PRINT_SFTP_HOST,
    port: process.env.PRINT_SFTP_PORT,
    username: process.env.PRINT_SFTP_USER,
    password: process.env.PRINT_SFTP_PASSWORD,
    algorithms: {
      kex: ['diffie-hellman-group14-sha256']
    } // , debug: console.log  // Add detailed debug logging on the connection
  }).then(async () => {
    await forEach(fileList, async (object) => {
      // write it to the Xerox SFTP
      await sftp.fastPut(`/tmp/${object.Key}`, `${path}/${object.Key}`);
      console.log('SFTP File upload DONE!', object.Key);
    });
    sftp.end();
    return true;
  }).catch((err) => {
    console.log('Catch Error: ', err);
    throw new Error(err);
  });
}
```

**Comment by theophilusx** [comment]
Glad you found a solution which works for you. I expect that as node matures further, packages like p-iterate will not be needed as the built-in array and for loop functions will be 'async aware'. Until then, packages like p-iterate are likely to be useful for hiding the messy details.
