### ISSUE TITLE
Local File Upload With put and fastPut 

### ISSUE THREAD

**Issue by deepktp** [theophilusx/ssh2-sftp-client#368]
First of All Thank You Very Much about This great library,

I am on a Project and i have found that uploading LocalFile with **put** method is Pointless if there is already a Great Function **fastPut**,

Issue is if string is provided as firstPram in **put** function it thinks it's a path to a file at local, but this functionality is approx same as **fastPut**,

a small improvement could be done like if firstPram of **put** function is string then is should directly get written in file.

To write a text in file i have to create a writeStream just for to write a string to file, 

and same for **get** function
Sorry for bad English

**Comment by theophilusx** [comment]
If I understand you, perhaps what you really want is to use a buffer to pass the data in rather than having to create a stream. You can easily create a buffer containing your string of data and then use that as the input to put().  the first parameter to the put() function can be a string (which is interpreted as a file path), a stream, which is piped into the destination or a buffer, which is used to extract the content to be written to the remote file. 

We cannot simply modify the put() function so that the first argument is interpreted as data because sometimes, you cannot use fastPut() (not all sftp servers support it) and in that situation, the user needs to be able to specify a file name.
