### ISSUE TITLE
Unexpected socket closed

### ISSUE THREAD

**Issue by torpongOmise** [theophilusx/ssh2-sftp-client#370]
![Screen Shot 2564-12-08 at 17 54 23](https://user-images.githubusercontent.com/89906158/145196609-e5431209-26e5-4f94-90a1-da0d30aa2a99.png)

Why the socket closed itself ? Please help

**Comment by theophilusx** [comment]
I need a lot more information in order to try and help. There are many
reasons the connection could be getting closed, including bugs in your
client code implementation.

What version of ssh2-sftp-client?
What version of node?
What platform is the client on?
What platform is the server on?
Can you provide a small example script which reproduces your issue?
Are you using anything like WSL, docker, virtual host etc?
Can you successfully connect and transfer data using openSSH sftp CLI?

**Comment by torpongOmise** [comment]
ssh2-sft-client version: 7.2.0
node version: 12.13.0
Sorry, I'm not really know much about server, but I run this on local and I have a problem when I'm using privateKey to access only. If I access by username and password, it would cause no problem.

PS. I succeed connect and transfer data using openSSH sftp CLI

```
module.exports.upload = async function (settings, localFile, fileName) {
  const sftp = new Client();
  sftp.on("error", function (error) {
    console.log(error);
  });

  const { host, user, pass, port, remote_path, privateKey } = settings;
  return sftp
    .connect({
      host: host,
      user: user,
      port: port,
      privateKey: privateKey,
      retries: 5,
      retry_minTimeout: 4000
    })
    .then(async function () {
      try {
        await sftp.list(remote_path);
        return true;
      } catch (error) {
        return sftp.mkdir(remote_path, true);
      }
    })
    .then(function () {
      const remote_file = path.join(remote_path, fileName);
      return sftp.put(localFile, remote_file);
    })
    .finally(function (message) {
      return sftp.end();
    })
    .catch(function (err) {
      console.error(err);
    });
};
```

**Comment by theophilusx** [comment]
What value are you passing in as the private key? It needs to be the
actual private key as a buffer or a string, not just the filename of the
private key.

**Comment by torpongOmise** [comment]
It's a string of actual private key. From the log, it look like it can connect but somehow close itself after sending the request to hostkeys-prove-00@openssh.com

**Comment by theophilusx** [comment]
I will try to find time over the weekend to have a closer look.

One thing you might try is doing a basic script which uses just ssh2.
Also, check the issues on the ssh2 project. All that ssh2-sftp-client
really does is provide an async wrapper API over the ssh2 library (which
is event based). If you write an ssh2 only script and still see the
issue, then it is either an issue wiht ssh2 or with the way your
extracting the publlc key data and passing it to ssh2.

One thing I did notice with your script, which is more a style thing
than anything else, but I think you get much cleaner and easier to
maintain code if you use either async/await or promise chains, but not
both. While the two approaches are functionally equivalent, it is better
to use one style/approach rther than mix the two IMO. I've seen people
get rather misleading error messages/exceptions because of mixed models.

for example, this bit of your code is a little problematic

    .then(async function () {
      try {
        await sftp.list(remote_path);
        return true;
      } catch (error) {
        return sftp.mkdir(remote_path, true);
      }
    })

with the above code, sometimes it will return a promise that resolves to
a boolean value and other times it will return a promise which resolves
to another promise (the return value from an async function is always a
promise). This could become a problem if you only wait on the resolution
of the outer promise and don't also wait for the 'inner' promise (in
this case, the promise returned by mkdir()).

I would also be more explicit in what your doing. The list() call
appears to be done just to check to see if the directory exists - if it
fails, you then attempt to create the directory. Would be better to use
the exists() method to verify the directory exists (and is a directory,
not a file) and then call mkdir() if it does not or throw an error e.g.

let dir_exists = await sftp.exists(remote_path);
if (dir_exists !== 'd') {
  await sftp.mkdir(remote_path, true);
}
return true;

**Comment by torpongOmise** [comment]
Wow Thank a lot. I have no idea that I could learn a lot with one reply of your. I will adapt according to your suggestion. Also I want to let you know that I downgrade the lib to version 6.0.1, and It's magically working just fine.

**Comment by theophilusx** [comment]
Note that v6.0.1 is based on the 0.8.9 version of ssh2, which had major
issues wrt compatibility and versions of node from v14. Version 1.x of
ssh2 (what version 7.x of ssh2-sftp-client is based on) fixed these
issues and works with all node versions > v14.

Your running an older version of node (v12) and the current LTS for node
is 16.13.1 while latest version is 17.2.0. Node v12 is currently in
maintenance status and will be unsupported in about 7 months time. You
should consider upgrading to at least node v16.x as there are some
significant performance improvements in node v14 and v16. There are also
a number of bug fixes in ssh2-sftp-client v7 which are not in v6.

**Comment by theophilusx** [comment]
I wrote the following simple test script to verify using ssh keys was working. I cannot reproduce the error you are seeing, so either it is something in your code or something local to your network configuration. 

````js
/*
 * Very simple upload script example which uses an ssh key for authentication
 *
 * This script uses the 'dotenv' library, which reads configuration data from
 * a simple key=value .env configuration file. The library then creates envrionment
 * variables for each key set to the corresponding value e.g.
 * SFTP_SERVER='my-sftp-host.com'
 * SFTP_PORT=22
 * SFTP_USER='fred'
 * SFTP_KEY_FILE='home/fred/.ssh/id_rsa'
 * SFTP_KEY_PASSPHRASE='my secret passphrase'
 *
 * This scirpt also accepts up to 4 command line arguments. These are
 * - path to the local file to upload
 * - path to the rmeote directory where the file should be uploaded to
 * - Name of the file created in the remote directory
 * - debug (optional) turn on basic console debugging
 *
 * The script will check to see if the remote directory exists. If it does, verifies it is
 * a directory (and not something else, like a file). If it does not exist, it will be created
 * The script then uploads the file using the put() method and then does a stat() on the remote
 * file to verify it now exists and reports the size. The script also checks to make sure the remote
 * file does not also exists - if it does, it throws and error and ends.
 *
 * Improvements: LOTS. This is a quick and dirty example. Error checking could be vastly improved
 * and there is unnecessary code duplication.
 */

const path = require('path');
const dotenvPath = path.join(__dirname, '..', '.env');
require('dotenv').config({ path: dotenvPath });
const fs = require('fs');
const Client = require('../src/index');

const sftp = new Client();

async function main() {
  const config = {
    host: process.env.SFTP_SERVER,
    username: process.env.SFTP_USER,
    privateKey: fs.readFileSync(process.env.SFTP_KEY_FILE),
    passphrase: process.env.SFTP_KEY_PASSPHRASE,
    port: process.env.SFTP_PORT || 22,
  };

  let localFile = process.argv[2];
  let remoteDir = process.argv[3];
  let remoteFilename = process.argv[4];
  let debug = process.argv[5];

  if (debug) {
    config.debug = (msg) => {
      console.error(msg);
    };
  }

  try {
    await sftp.connect(config);
    let dirExists = await sftp.exists(remoteDir);
    if (dirExists && dirExists !== 'd') {
      throw new Error(
        `Bad path: ${remoteDir} exists, but is not a directory object`
      );
    }
    if (!dirExists) {
      await sftp.mkdir(remoteDir, true);
    }
    let remotePath = path.join(remoteDir, remoteFilename);
    let fileExists = await sftp.exists(remotePath);
    if (fileExists) {
      throw new Error(`Bad path: ${remotePath} already exists`);
    }
    await sftp.put(localFile, remotePath);
    let fileStat = await sftp.stat(remotePath);
    console.log(`Remote file ${remotePath} size is ${fileStat.size}`);
  } catch (err) {
    console.error(err.message);
  } finally {
    await sftp.end();
  }
}

main();
````
A couple of things to note 

- If your using an ssh key, don't include a password. 
- If your ssh key has a passphrase, you need to also include that by setting the passphrase property of the config object

The script expects to be called with some arguments e.g.

node ./upload-with-keys.js <local file path> <remote upload directory> <remote upload filename> <debug>

the <debug> argument is optional. 

I have added the scirpt to the examples directory of the ssh2-sftp-client repository. You will need to adapt/adjust the script to run it (it uses dotenv for config setup and expects the ssh2-sftp-client code to be in a local relative directory).

**Comment by theophilusx** [comment]
Did the example script help to resolve your issue? If not, my suggestion would be to write a very simple script which only uses ssh2. If that still triggers the issue, report it to the ssh2 project (including your sample script). As I cannot reproduce the issue and as I suspect that if there is an issue, it is at the ssh2 layer level, I think this issue can be closed.

**Comment by theophilusx** [comment]
As there has been no response on this issue and as I'm pushing out a new 7.2.2 version, which is based on an updated ssh2 version (1.6.0), I'm closing this issue.
