### ISSUE TITLE
replacing line endings 

### ISSUE THREAD

**Issue by jonnytest1** [theophilusx/ssh2-sftp-client#375]
im currently on the task of wanting to change line endings to the target system (raspberry pi with linux) from my windows machine

after trying 
`
 const file = await readFile(from, { encoding: "utf-8" })
const linuxFile = file.replace(/\r\n/g, "\n")
const linuxFileBfr = Buffer.from(linuxFile);
return this.client.put(linuxFileBfr, to)
`
it seems to work 

but i think it would be nice to include this funcitonality as an option 
(especially since its probably faster when done with streaming)

**Comment by theophilusx** [comment]
I don't think this is functionality that belongs in ssh2-sftp-client.
The library already supports using streams as input/output for put/get
and so you can therefore easily add a transform stream to perform this
type of conversion. Therefore, I think this is something best done by
client code when it is necessary.

**Comment by jonnytest1** [comment]
🤔 im not sure how to solve this with pipe though - i mean what do i do if the \r is in a different chunk than the \n ?

**Comment by theophilusx** [comment]
THis isn't as hard to solve as it may seem. There are lots of examples
of transform streams which need to manipulate data based on information
from the previous/next chunk (consider transform streams which
compress/decompress data or create a hash from input data etc). For
example, you could just write your transform function so that it keep
strack of the last character from the previous chunk and prepends that
to the next chunk before searching for line endings, convert and write
out. There are various ways to keep track of previous values passed in
(such as a closure to store some local state info). The key point to
note is that in a transform stream, the output does not need to be the
same size or shape as the input. Although it would be extremely
inefficient and not recommended, you could read all the chunks into a
buffer, perform the line ending transformation and then write out the
buffer. Not a good solution because for large files, you would use large
amount of buffers. However, the point is, you can pretty much do
whatever you want - it doesn't have to be chunk in -> chunk out. The
only critical think is to ensure you do read in all supplied chunks to
prevent the stream switching into 'paused' mode. 

Alternatively, there are probably existing modules out there which you
could just use in your pipeline i.e. one which accepts a stream as input
and outputs a new stream with the line endings converted, which you
could just drop into your pipeline.
