### ISSUE TITLE
Some files (PDF's) gets mangled...

### ISSUE THREAD

**Issue by QAnders** [theophilusx/ssh2-sftp-client#379]
I have an implementation which runs in AWS where I add a bunch of PDF's (can be up to 800-1000) in an AWS Bucket. I then trigger a Lambda (node 14) which reads PDF by PDF and copies them to the local `/tmp` disk of the Lambda.

I use `p-map` to iterate the function and run three concurrent connections (the max the server allows) and the code is like:

```
const uploadFile = async (object) => {
      // Read PDF data and place it in /tmp
      const params = {
        Bucket: process.env.SEND_TO_PRINT_BUCKET,
        Key: object.Key
      };
      // Get the PDF data
      const data = await s3.getObject(params).promise();
      // Write the PDF as a /tmp file
      await fs.writeFile(`/tmp/${object.Key}`, data.Body);
      // Now write it to the SFTP Server
      await sftp.fastPut(`/tmp/${object.Key}`, `${path}/${object.Key}`);
      console.log('SFTP File upload DONE!', object.Key);
      // It's uploaded! Delete local file (we only have 256 MB /tmp space in Lambda)
      await fs.unlink(`/tmp/${object.Key}`);
      // Move the S3 object to "processed"
      const options = {
        CopySource: `${process.env.SEND_TO_PRINT_BUCKET}/${object.Key}`,
        Bucket: process.env.SEND_TO_PRINT_BUCKET,
        Key: `processed/${object.Key}.processed`
      };
      await s3.copyObject(options).promise()
        .then(() => s3.deleteObject({
          Bucket: process.env.SEND_TO_PRINT_BUCKET,
          Key: object.Key
        }).promise());
    };

    await pMap(filteredObjects, uploadFile, { concurrency: 3 });

    sftp.end();
    return true;
  }).catch((err) => {
    console.log('Catch Error: ', err);
    throw new Error(err);
  });
}
```

At first I thought it was the Lambda filesystem messing the files up but I added code to copy the PDF's back to a sub-directory in the S3 Bucket to check them and there they are all fine.

The last run of 867 PDF's three were "damaged" in transport.

The "damaged" PDF and the sent (orignal) has the exact same byte size and looks (at a first glance) very, very similar so I wrote a little snippet to compare byte-by-byte and then found that there's a difference starting at position 541.806 in the file and continues with differences for about 120.000 bytes before it again settles down and are identical from there to the end.

![image](https://user-images.githubusercontent.com/12028885/148931843-be15459d-7d8c-4711-b32c-69e2f1ad960e.png)

The error could of course be on the server end when they are writing it to disk but figured to ask here if there's been any reportings/issues when there are many uploads and if there's any way to debug the upload, for example getting the file hasses of the uploaded file to try and pinpoint where it gets ruined...

**Comment by theophilusx** [comment]
You don't specify which version of ssh2-sftp-client you are using or
what version of node?

There have been no reports of this type of data corruption for
ssh2-sftp-client and no reports that I'm aware of for ssh2.

In my testing, I transfer files of multiple different sizes where I
perform checsums on the data before and after and compare between
original and copy. There have been no errors found.

If there is a problem, it would almost certainly be in the ssh2 library
rather than ssh2-sftp-client, which is really only a wrapper around ssh2
to provide a promise based API (ssh2 itself is event based).

My recommendation would be to see if you can replicate the error with
just ssh2 and know ssh2-sftp-client. If you can, you would then be able
to log an issue with the ssh2 project. Being able to demonstrate the
issue occurs with just ssh2 would be fundamental in order to get the
ssh2 project to investigate further.

I would also try an implementation which does not try to transfer
multiple files concurrently and see if the issue can be reproduced. Some
sftp servers are better at concurrent operations than others. I've also
found, depending on the size of the files being processed and the
network involved, concurrent uploads are not always as beneficial wrt
speed as you might expect. The additional overhead involved, combined
with reduced overall throughput can actually result in slower overall
transfer.

**Comment by air2** [comment]
You could try to use the put method instead of the fastPut method.

**Comment by theophilusx** [comment]
As there has been no response regarding node/ssh2-sftp-client versions and given I'm about to push a new version which is also based on an updated ssh2 version, I'm going to close this issue. 

If the issue still persists, we can reopen it. However, I need details on node version, platform and if possible, a minimal script which can reproduce the issue in order to diagnose further.

**Comment by QAnders** [comment]
Sorry for the late come back, @theophilusx... We had to switch back to our old SFTP client (on a server) since there were too many invalid PDF's being sent over (that was corrupted).

I've tried a bunch of different things and updated to v7.2.2 (ssh v1.6.0).
Node is running v12.14.1 (AWS Lambda v12)

My first implementation was using the `fastPut` as in the code sample above:
1) I grab a list of PDF filenames from an AWS S3 bucket and then send that list to the "upload function"
2) I read the PDF from S3 and write it to the Lambda `/tmp`
3) I use the `fastPut` to upload the PDF from `/tmp`
4) I delete the PDF from `/tmp` to free up space

With the above we get about 1 in 25 corrupted PDF's (~4%) with the same pattern as described above, filesize is identical but bytes in the middle of the PDF's are messed up.

Next I added code to copy out the PDF from `/tmp` to another S3 bucket to make sure it was not the writing of the PDF to `/tmp` that corrupted it, it was not... All copies in the S3 "backup" bucket were intact.

Next I tried with `put` instead of `fastPut` where I still wrote the PDF to `/tmp` and then created a `readStream` for the `put`. The result of this was even worse with about 20% corrupted PDF's on the server.

My next attempt was to create the readStream directly from the S3 `getObject` (no writing to `/tmp`) but this was a total disater with about 40% corrupted PDF's.

**The conclusion this far, thus, is that `fastPut` create way fewer corrupted PDF's...**

I also tried running the same code (as it is Serverless) locally on my machine to see if the problem was executing it in AWS but the results are worse when running from my machine than from AWS Lambda.

Next I started testing with adding delays (`setTimeout`) of 100, 200 and 300 milliseconds between each read or write operation.

`fastPut` with a 300ms delay between writing the file to `/tmp` and also after the "sftp'ing" resulted in 2% corrupted PDF's so much better.
The `put` with a stream was also much improved with about 8% (down from 40%).

As delays lead to a better result I tried again with a various "concurrency" of the upload (how many simultaneous "upload functions" I allow to run). The higher I go, the worse it gets and with 10 concurrent "uploads" pretty much 100% of the PDF's are corrupted, but with 1 concurrent upload I had to upload 400 PDF's (which was very slow) before I could find one corrupted...

Final conclusion is that running the uploads one-by-one it works fine but as soon as I start adding more parallel uploads it gets worse (and interestingly, 2 concurrent uploads are way worse than 3, and likewise 4 concurrent uploads gives a higher percentage corrupted files than 5)

**Comment by QAnders** [comment]
The altered code looks like this now and is working (almost) flawlessly (however very slow as concurrency is 1 only):

```
const uploadFile = async (object) => {
      const params = {
        Bucket: process.env.SEND_TO_PRINT_BUCKET,
        Key: object.Key
      };
      // Get the PDF data to a readStream
      const data = await s3.getObject(params).createReadStream();
      // Now write the readStream from S3 directly to the Xerox SFTP
      await sftp.put(data, `${path}/${object.Key}`);
      console.log('SFTP File upload DONE!', object.Key);
      // Move the S3 object to "processed"
      const options = {
        CopySource: `${process.env.SEND_TO_PRINT_BUCKET}/${object.Key}`,
        Bucket: process.env.SEND_TO_PRINT_BUCKET,
        Key: `processed/${object.Key}.processed`
      };
      await s3.copyObject(options).promise()
        .then(() => s3.deleteObject({
          Bucket: process.env.SEND_TO_PRINT_BUCKET,
          Key: object.Key
        }).promise());
    };

    await pMap(filteredObjects, uploadFile, { concurrency: 1 }); // IMPORTANT! The server (or the ssh package) can only handle one at the time

    sftp.end();
    return true;
  }).catch((err) => {
    console.log('Catch Error: ', err);
    throw new Error(err);
  });
}
```

**Comment by theophilusx** [comment]
I suspect the issue may be in the ssh2 module. The next thing to do
would be to replicate your workflow just using ssh2 (or at least try to
replicate the corruption just using ssh2). This will confirm if the
issue is in the low level ssh2 code. If it is, then it will be necessary
to log the issue against the ssh2 project. There are some sample scripts
in the validation directory of the ssh2-sftp-client repository which
demonstrate how to do some basic file transfer operations just using
ssh2 which might be useful.

One reason I suspect the core issue is related to the ssh2 module is
because you get different results based on the concurrency. The
concurrency setting for fastPut is all managed within the ssh2 code. All
the ssh2-sftp-client module really does is wrap the ssh2 API in basic
promises to enable use of async/await.

The ssh2 author did tell me that fastPut is heavily dependent on the
underlying sftp server implementation. Apparently some sftp servers
either don't support concurrent transfers or don't support them
reliably.

It should be noted that ssh2-sftp-client 7.2.2 is based on ssh2 1.6. The
1.x versions of ssh2 are a complete re-write of the previous 0.8.9
version, which had problems with node v14 (specifically with fastPut)
and some other limitations. Given that node v12 will be out of
maintenance and unsupported after April, I would strongly recommend
upgrading to at least node v16 (or at least verify the issue exists with
node v16) as there have also been some significant changes in node's
network layer post node v15.3. There have also been some significant
performance improvements with respect to promises in Node v15+, which
may improve your processing time.

**Comment by QAnders** [comment]
Thanks for getting back to me, @theophilusx! Appreciated!

AWS Lambda only supports v12 and v14 (for now)... By adding the delays and only running one upload at the time it works though.
As AWS S3 supports `createReadStream()` out of the box (well, the SDK) I actually don't lose too much in execution time compared to `fastPut()` as I then had the disk I/O instead (although it is now about 40% slower) but anyone using SFTP 2022 shouldn't have an issue with some latency... eh?

Interestingly I found an old issue in `ssh2` (where you also were involved) which describes my issue to the letter: https://github.com/mscdex/ssh2/issues/739

Anyhow, I'll leave it as is now and when AWS releases node 16 (should be within 2-3 months if rumors are true) I can take a swing at it again...

**Comment by theophilusx** [comment]
Anders Wasen ***@***.***> writes:

> Thanks for getting back to me, @theophilusx! Appreciated!
>
> AWS Lambda only supports v12 and v14 (for now)... By adding the delays and only running one upload at the time it works
> though.
> As AWS S3 supports createReadStream() out of the box (well, the SDK) I actually don't lose too much in execution time compared
> to fastPut() as I then had the disk I/O instead (although it is now about 40% slower) but anyone using SFTP 2022 shouldn't have
> an issue with some latency... eh?

Given node's basic single threaded model, I doubt it will ever perform
as efficiently as clients which have real threading support. However, it
is reasonable to expect data to be transferred without corruption.

>
> Interestingly I found an old issue in ssh2 (where you also were involved) which describes my issue to the letter: mscdex/ssh2#739
>

I didn't mention that issue because both ssh2 and ssh2-sftp-client have
been completely re-written since that issue was originally
identified. While the symptoms may seem the same, I suspect it is not
the same underlying issue (i.e. mismatch between client/server wrt high
water mark and packet sizes).

An alternative cause could be (for example) a data encoding
mismatch. Your error is very similar to ones I remember from the old FTP
days, where you needed to be careful to specify whether your download
was 'binary' or 'text'. Could it be (for example) that some of your
PDF's are 'normal' (basically text) or are they PDF's generated from
images (with embedded binary data)?

Either way, given that ssh2 has been completely re-written, the problem
really needs to be diagnosed from scratch. This would be much easier if
it was possible to generate a reliable, reproducible test case.
