### ISSUE TITLE
downloaded file does not get uploaded via fastPut/put if it is to big

### ISSUE THREAD

**Issue by saringer** [theophilusx/ssh2-sftp-client#382]
I'm using **ssh2-sftp-client v7.2.1** and **node v16.13.1**.

My script fetches a file from our S3, writes it locally and then initiates a sftp-upload via **fastPut**.

`await fsWithPromise.writeFile(vendorId + '.mp4', initialStream)` 
`await sleep(120000)`
`await sftpConnection.fastPut(vendorId + '.mp4','remotePath.mp4')
`

Whenever the file I just downloaded has a size bigger then ~4GB, fastPut just creates an empty file on the remote-sftp but does not upload any data and gets stuck.

<img width="886" alt="Screenshot 2022-01-15 at 10 32 17" src="https://user-images.githubusercontent.com/7473273/149617164-99e4437f-8dc1-405a-9acc-0a660c4c873f.png">

I added sleep for testing if there needs to be some sort of break after writing the file and then reading it with no success. 
When I cancel and rerun my script and the file was already downloaded, **fastPut** worked 100% of the time no matter the size of the file (usually no more then ~10GB). I experienced the same behaviour when using **put** instead of **fastPut**.

Any ideas on what would cause the problem would be much appreciated :)

**Comment by theophilusx** [comment]
My suspicion is that the issue is somehow related to the initial download. In particular, I'm wondering if perhaps the fsWithPromise.writeFile() call has completed/released the downloaded file (for example, what happens if after the call you close initialStream? The fact it works 100% of the time if you exist and try the upload with the already downloaded file and the fact, you report it just hangs initially, makes me think something is holding some lock and the 'hang' is due to waiting for a lock to be released. When you restart, there is no locks and all woks fine. 

I would try some simple experiments - basic file manipulation with downloaded file (no ssh2-sftp-client) and see if you observe similar issues (I suspect you will). This won't necessarily tell you what the problem is, but should narrow down the search space. It is unlikely to be ssh2-sftp-client as it has no knowledge regarding the history of the file - it doesn't know it has just been downloaded. It just knows it is supposed to read a file form the fs. If the fs is tellling it the data isn't ready or is locked or whatever, it will just wait until the OS says all is OK to access.

**Comment by saringer** [comment]
Thanks for the response @theophilusx .

I tried different approaches to ensure that the writing stream is closed properly which unfortunately did not change the issue.

But what seemed to fix the issue was to initialize the entire sftp connection (client -> connect ->put) after the _writeFile()_-process finished. In my first approach I already connected to the sftp-server and then started the download of the file. It seemed like I probably just did a wrong setup of the sftp-client.
