### ISSUE TITLE
How to end the fastPut method or fastGet if the network is unstable for large file transfer

### ISSUE THREAD

**Issue by hsqoo** [theophilusx/ssh2-sftp-client#385]

**Comment by theophilusx** [comment]
This is actually quite difficult to do because the current Promise
implementation does not support asynchronous interruption or cancelling
of a promise. While there are some proposals 'in the works' to support
cancellation of a promise, nothing has yet been implemented (it might
get added to the next major node release, but I've not been monitoring
so unsure where this is at).

What I would try is wrap the fastGet/fastPut promise inside anotgher
promise which implements a timeout. If the inner promise has not
resolved within a specified timeout period, you would then reject the
outer promise. Your code would then wait on that outer promise to be
fulfilled (resolved or rejected. When rejected, your code would call
close on the connection and the transfer should then be cancelled.

Of course, this is just off the top of my head. I've not tried
implementing this. There is no API support for cancelling a
fastPut/fastGet in ssh2, so no way to cleanly do things. However, with
an unstable network, there isn't much you can do cleanly anyway.

The big problem is how to determine what is a reasonable timeout. You
always run the risk of cancelling the transfer mere seconds before it
would have completed. There is also no mecahnism within the ssh2 API
which would allow you to restart a download/upload at the point it was
interrupted. So basically, once you do kill a transfer, if you later
want to try it again, you have to start at the beginning.

**Comment by hsqoo** [comment]
I would like to provide a cancellation method for the user to choose whether to terminate the current transfer, because the file may be large or the current network speed is slow

**Comment by theophilusx** [comment]
I don't think there is anything else required here, so I'm closing this issue.
