### ISSUE TITLE
Download Directory, disable overwrite

### ISSUE THREAD

**Issue by unimatrix27** [theophilusx/ssh2-sftp-client#386]
It would be great to download a directory, but only files that do not yet exists or are newer. I could imagine to create a PR for this, but would like to know if such feature would fit in.

**Comment by theophilusx** [comment]
To be honest, I'm very reluctant to add such a feature. I seem to get
more requests for adding additional features/options to the
download/upload directory support than anything else. This tells me this
type of functionality is wanted, but also that we are unlikely to
identify all the possible options people want.

I want to keep ssh2-sftp-client as simple as possible. The
upload/download directory feature was borderline to begin with as it
begins to cross the line and because implementing your own version which
does exactly what each different developer wants is trivial.

I"m thinking a better approach might be to provide upload/download
functionality where the user provides a filter predicate function which
would determine which files/directories are acted on. Basic concept is
straight-forward, but there are some edge cases needing to be dealt
with.

**Comment by theophilusx** [comment]
I played with a few ideas for this and decided against adding this to the main methods due to the overall impact on performance. 

However, I have re-worked the uploadDir and downloadDir so that now it accepts a filter function. The function is called with two arguments - the full path to the item being uploaded/downloaded and a boolean which is true if the target is a directory. 

If you wanted to prevent download of files/directories which either already exist or some other criteria, you could put this into a filter predicatge. The function just needs to return true to include the item and false to exclude it. The filter function will be called for each item to be downloaded. 

This change will be in version 8.0.0, which should be released in the next week or so. I will close this issue now.
