### ISSUE TITLE
cant connect sftp

### ISSUE THREAD

**Issue by marshelgradana** [theophilusx/ssh2-sftp-client#391]
node version 15, 
"ssh2-sftp-client": "^7.2.2"
nestjs
alicloud

get this error when my project want to connect to sftp, 
 vpn already established, when i try to put manual with same credential, it works.
but when the project want to put always socket error ENOTFOUND,
if i try with ip for host timeout error 

![Untitled](https://user-images.githubusercontent.com/99856345/154401456-3baf7800-0c01-4784-a3bf-87dd0982193e.png)

**Comment by theophilusx** [comment]
That error is telling you that the DNS lookup for the hostname you have
provided is not returning an IP address. The fact you are also getting a
timeout error when using the IP address tells me you have some type of
network problem.

First thing I would suggest is creating a simple ssh2-sftp-client script
which just uploads/downloads a file from your system to a remote sftp
server. Don't use anything other than ssh2-sftp-client and see if you
can reproduce the issue.

I would also make sure your using node >= 15.3. There were some issues
with node versions 14.x - 15.3 relating to network changes. You really
should be using node v16 as node v15 is an old dev versionns (current dev
version is node 17.x).

If you are able to reproduce the issue using just ssh2-sftp-client, I
would then try a simple ssh2 only script. There are some example scripts
in the validation directory of the ssh2-sftp-client repository. This
will tell us if the problem is at the ssh2-sftp-client level or the ssh2
level. If you are able to reproduce the issue just using ssh2, it will
be necessary to log an issue with that project.

If things work with just ssh2, then you need to send me your
ssh2-sftp-client example script and a full debug log. I can then use
your script to try and reproduce the issue on my test servers.

My suspicion is that you have some local network issue. The
ssh2-sftp-client library gets nearly 200k downloads per week and you are
the only one to report this error. I have seen others having problems
when using various containers or VMs, such as docker or WSL. In
particular, WSL seems to have data fragmentation issues which sometimes
requires setting a smaller MTU on the network device and I've seen
reports of people having DNS issues under docker when the container is
not configured correctly.

If you are using some form of container or VM, it might be worthwhile
running a simple ssh2-sftp-script outside the contgainer to see if the
problem exists there as well.

**Comment by marshelgradana** [comment]
case solved,
 yes because local network docker, 
thank you very much for the solution 🙏🏻
