### ISSUE TITLE
dyld[28324]: missing symbol called on Apple M1 Mac

### ISSUE THREAD

**Issue by jeremymefford** [theophilusx/ssh2-sftp-client#398]
**Node:** 17.5.0 - arm
**Computer:** Macbook Pro - M1 Max
**OS:** MacOS 12.2.1

When trying to use the library on my mac, i am getting this error:

```
dyld[28324]: missing symbol called

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

When i change the node version to the x86 version with rosetta, this error goes away.

**Comment by theophilusx** [comment]
This is either a node issue associated with the M1 version of node or it
is an issue in the ssh2 module. There is nothing in sssh2-sftp-client
which does any dynamic library loading etc. I would check with the ssh2
project to find out if there are any issues with ssh2 running on M1
hardware. I suspect that native crypto stuff is either not supported or
you need to add some build options.

There has been some threads recently in the ssh2 project about problems
with node versions installed via homebrew being linked against an older
openssl library. It might be worthwhile verifying your node version is
linked with at least 1.1.1 - those having problems were running a node
version installed via homebrew which was linked against openssl 1.0.0.

I would also update to latest node v17. Support for M1 can still be a
bit flaky, so you want to ensure your running latest. I would also not
use homebrew but instead get official build binaries. I've found the 'n'
package manager works really nicely on both Linux and Mac, especially
once you set things up so that you don't need to use sudo to upgrade or
install global modules. Once setup, moving between different node
versions is pretty much effortless.

**Comment by sambegin** [comment]
@jeremymefford  I end up having the same issue on node 14.18.2. 

I've read this thread: https://github.com/mscdex/ssh2/issues/1146 and ended up `nvm install 17`. 

Then ` node -p process.versions` to see my openssl version installed: `3.0.2+quic` 

I don't get this error anymore with `node v17.8.0` and `openssl: 3.0.2+quic`

**Comment by theophilusx** [comment]
As this is an ssh2 issue and one which has been reported to the ssh2 project, I am closing this issue as there is nothing we can do from this level.
