### ISSUE TITLE
Question: rmdir recursive - is it safe to parallelize?

### ISSUE THREAD

**Issue by CodeMan99** [theophilusx/ssh2-sftp-client#399]
I see that the `rmdir` method can remove recursively. However, I need to remove a very large tree. Because this function does an `await` on every delete, it is painfully slow for my use case.

See https://github.com/theophilusx/ssh2-sftp-client/blob/d6b170aaefaaca21a3f95f84f581410141c222ac/src/index.js#L943-L948

Just wonder if you happen to know if this operation is safe to parallelize? Even if I have to manually implement a limit that be ok.

**Comment by theophilusx** [comment]
No, I don't think you can do this in a safe and reliable manner. The
main issue is with the management of events fired by the underlying ssh2
module while wrapping it all inside a promise based API. 

The current implementation has a very simple model for managing events
which are fired during the execution of a promise. Essentially, each
promise creates temporary listeners which a prepended to the list of
event handlers for each event type. If an error/end/close event occurs
during the execution of the promise, the reject() method associated with
that promise is fired. When the promise is fulfilled, the finally clause
removes the temporary listeners.

The problem is the temporary listeners are tracked in a hash where the
key is the name of the method. Unfortunately, this means that if
multiple promises are created for the same method, they will tread on
each other and either you will end up with a possible memory leak
(because listeners are not removed when they should be) or you will get
unexpected errors because listeners have been removed before they should
have been.

To handle parallel operations, a much more complex structure would be
required. However, that won't necessarily solve the problem. The real
problem is in how to create a clean interface between a promise and an
event driven model. Events exist outside the context of the promise.
They can be raised at any time i.e. between promises, after a promise
has called resolve() or reject() etc. There is also nothing in the event
which will tell you which promise operation caused the event to fire
(sometimes, the event fires because of factors outside the focus of any
promise - for example, loss of network connection). 

Consider the situation where you have multiple promises executing in
parallel. One of the promises causes an error event to be raised. How do
we determine which promise that error should be associated with? We
could just do the 'simple solution and have the error propagated to all
unfulfilled promises, but that might result in promises reporting a
rejected status when in fact they succeeded (this risk already exists,
but is less likely and has a lower impact if realised). We cannot have a
global event management approach because currently there is no mechanism
to interact with a promise from the outside i.e. you cannot cancel a
promise from outside the promise - you can only resolve or reject a
promise from within the promise itself.  

My suggestion would be to implement the tree deletion using just ssh2
and its event driven model. You could wrap the whole thing in a promise
to make it easier to inerop with the rest of your code. This might also
give you a bit of a feel for how much performance improvement you will
get. I find with node, exploiting parallelism often doesn't give the
performance improvement you might expect. Some of this is likely due to
the single threaded nature of node where your not really running in
parallel but rather doing something more akin to time sharing. The
problem with this model is that it is easy for the performance gains to
be lost in context switching. As you cannot remove a directory until all
contents (files, sub-directories) have been removed, the performance
benefit will also be dependent on the shape of the tree being deleted. A
narrow and deep tree will not benefit much while a broad shallow tree
probably will.

Having said all of that, there are some changes I've been considering
which might improve the situation. Unfortunately, it will be a couple of
weeks before I have time to work on this.

**Comment by CodeMan99** [comment]
Thanks for the response. Very helpful.

Feel free to close or edit this issue as you see fit.

**Comment by theophilusx** [comment]
I have made some changes to the rmdir method which might help your use case. Two main tings I have done are 

- Re-worked the tracking of event listeners to eliminate the previous problem where recursive and parallel calls would tread on each other. 
- Modified the rmdir method so that now it uses Promise.all() to run all delete file methods asynchronously. This should improve performance when directories have large numbers of files which need to be removed before the directory can be removed. 

The actual removal of directories is still synchronous because the recursive nature makes it too easy to blow out when there is a deep tree and many recursive calls. 

I would be great if you could try this out and see if it helps your use case or not. The updated code is in the github repository under the branch called 'rmdir-performance'.  Be great to have it tested on a large directory tree.

**Comment by theophilusx** [comment]
Just fixed a couple of minor issue and further improved concurrency support.

**Comment by CodeMan99** [comment]
Was just able to test your changes. It blazing fast! Our use case is a shallow, wide tree.

I was able to delete roughly 700 files during a short conversation. Sorry, forgot to time it, but it certainly was less than 2 minutes, probably less than 1 minute.

That same task before this conversation probably would have taken 12 minutes.

**Comment by theophilusx** [comment]
Just about to push v8.0.0, so closing this issue now.

**Comment by CodeMan99** [comment]
Many thanks!
