### ISSUE TITLE
"list" returns owner & group IDs, not names

### ISSUE THREAD

**Issue by nick-george** [theophilusx/ssh2-sftp-client#409]
Hi there, 

This is more a feature request as opposed to a bug 

I've noticed that this code returns returns only IDs for list operations. The openssh sftp client returns usernames & group names. Is there any way that this client could be extended to return the names of the owner & group as well as  the IDs? 

Many thanks, 
Nick

**Comment by nick-george** [comment]
I just had a read of the code and it looks like you just rely on the upstream SSH2 module for getting the info. Shall I close this and chase that project instead?

**Comment by theophilusx** [comment]
You are correct, this module depends on the output from ssh2 and is limited to what it returns. You can ask at the ssh2 project, but I suspect you will be out of luck. The issue is likely to be that getting that information is going to be non-trivial and very sftp server dependent. Problem is you have to handle different file systems with different concepts regarding users/groups and because the names for users and groups are not part of the filesystem, so they have to be looked up somewhere else (like /etc/passwd or /etc/groups. With some sftp server configurations (such as a chroot style setup), those mapping files won't even be accessible. I suspect the ssh2 author will see this as a fair bit of work which adds a lot of code that will mainly be handling compatibility/workarounds for little benefit. However, no harm in asking.

**Comment by nick-george** [comment]
Thanks @theophilusx. 

I'm possibly preaching to the converted here, but it seems odd that the openssh client/server combination will list the owner & group names, whereas the nodejs<->openssh-server doesn't. 

The user ID to name lookup **has** to occur server-side because of obvious reasons (how could a client be expected to interpret /etc/passwd, even if it had access). I also just confirmed this through logging all requests on SSHd, the client never requests /etc/passwd. 

So, as far as I can tell, this information has to be sent back by the openssh-server to the client. I'm guessing it's up to the client to decide what to do with the information. 

Given your experience in this space, do you know how I could see the content of the data that's sent back to ssh2 module so I can see what is included? 

Many thanks, 
Nick

**Comment by theophilusx** [comment]
You might be working under a misunderstanding regarding ssh2. The ssh2 module is a fairly low level library which implements the core parts of the ssh2 protocol. It isn't an openssh implementation. It also isn't a server, though you can use it to develop a server. OpenSSH has also added a number of extensions to the ssh2 protocol. Most of these are not supported by ssh2. I've not checked, but suspect mapping uid/gid to names is likely an openssh extension.

**Comment by nick-george** [comment]
Hi @theophilusx. 
@mscdex at ssh2 suggested that: 
`
However, the longname typically contains an ls -l-style listing for the file 
`
Is it possible for you to provide the longname in the output from this module as well? I can see you're using it already. 

Cheers! 
Nick

**Comment by theophilusx** [comment]
Yes, that would be possible. However, it does change the interface and I have some other changes which may also result in interface changes, so it will likely have to wait so that I can bundle them all together before a new version is pushed out to npmjs.com. I'll add a longname attribute to the master branch tomorrow, which will enable you to test/develop from the github repo until a release is made. Your code will need to parse that attribute to extract the info you need. It will likely be somewhat fragile (which is why I don't use it) as the format can vary slightly depending on platform and sftp server (the first 'field' tends to be fairly constant, but after that it can vary  a bit).

**Comment by theophilusx** [comment]
Have added longname property to object descriptors returned from list() call in master branch.

**Comment by nick-george** [comment]
Many thanks for this Tim. I'll test it out now. 

Cheers, 
Nick
