### ISSUE TITLE
get(filePath) no longer returning a buffer

### ISSUE THREAD

**Issue by rt-rkk** [theophilusx/ssh2-sftp-client#415]
**EDIT: This has been resolved in [this commit](https://github.com/theophilusx/ssh2-sftp-client/commit/8c7d6969ee96e58e753689ac426d6dfacde9fda1)**. Leaving open until 9.0.1 is live.

Windows 10
Node 16.14.0
ssh2-sftp-client 9.0.0 (working in 8.1.0)

Running ssh2-sftp-client 9.0.0 and attempting a simple get() call in hopes of receiving a buffer.

`let buf = await sftp.get(filePath);
console.log('Buffer: ' + Buffer.isBuffer(buf )); // true in 8.1, false 9.0`

**Comment by theophilusx** [comment]
Good catch!

Problem was a timing issue between calls to resolve(). The call to
resolve which returns the writer object was firing before the call to
resolve which returns the concat-stream buffer object. So the buffer of
data you were after was being returned, but inside of a concat-stream
object instead of just the buffer itself. 

Have pushed a fix to master. Would be good if you could try it out and
see if it addresses your issue. If it does, I will push out 9.0.1

**Comment by rt-rkk** [comment]
Thanks for the writeup - much more obvious after a second-look.

I am happy to confirm my issue has been resolved, thank you!

**Comment by kasperpihl** [comment]
I also ran into this and look forward to the 9.0.1. Great update otherwise! 🙌

**Comment by rt-rkk** [comment]
Reopening until 9.0.1 is released for better visibility to others in the same boat.

**Comment by theophilusx** [comment]
v9.0.1 pushed
