### ISSUE TITLE
put stream not resolve as expect

### ISSUE THREAD

**Issue by alanhg** [theophilusx/ssh2-sftp-client#417]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/9245110/175764399-84722258-1585-47e9-a1f0-a8e67dfd181f.png">

It doesn't go to the then part and no any error.

**Comment by theophilusx** [comment]
at a guess, I would say it is an issue with your web socket. This is
something you will need to diagnose as I cannot do it without a lot more
information. For example, what platform are you running on? What version
of node are you running? You failed to even say what version of
ssh2-sftp-client your attempting to use.

Just looking at that small bit of code, it looks to me as if you have
your streams around the wrong way - don't you want the data streamed
into the throttle and then that streamed to ssh2-sftp-client? It looks
like what you are doing is

throttle -> stream -> put

when what you probably want is

stream -> throttle -> put

Have you tried without the throttle? Have you confirmed you need the
throttle?

At any rate, if no data is actually getting sent to
put(), then that would explain why your not getting any error and your
not getting a resolved promise - nothing is happening because no data is
lowing through the streams. 

Have you tgried just streaming the data from the web socket into a local
file to verify that bit is working as expected? You can create a local
write stream and test using that. If the data gets from your web socket
into that local file, half the battle is won and you know the streams
are working. You can then try opeing a stream on that file and passing
it to ssh2-sftp-client's put to verify that other half works. Once that
is done, then connecting the two should be fairly tgrivial. 

Note that socket streams are typically bidirectional streams. You
probably need to do additional actions in order to get the data flowing
over the socket. This is one reason I suggest you get tings working so
that the data from the web socket is written to a local file. This will
ensure you have the process basically working. The local file stgream
will be a write stream, which is what ssh2-sftp-client put() is
expecting, so getting it to work with a file write stgream is a good
first step.
