### ISSUE TITLE
Error using filter function with list()

### ISSUE THREAD

**Issue by juanddiaz13** [theophilusx/ssh2-sftp-client#424]
When I try to filter with a function that always returns true (as it shows below):
![image](https://user-images.githubusercontent.com/20101153/181592772-72bcfb59-3345-4890-9716-493d6fe8082c.png)

**I also tried adding a parameter, just in case, but didn't work**

When I try that the following error is produced:

**Error: list: pattern.replace is not a function**

I know passing a function that always returns true is the same as not passing a function at all, but I'm thinking of implementing a function that actually does some relevant filtering in the near future, but since I can't make this simple one work I won't further the complexity of the code.

Am I doing something wrong or is there an issue with the filter function?

**Comment by AndrewLane** [comment]
@juanddiaz13 I believe it's failing here because it's expecting pattern to be a regex and not a function.  https://github.com/theophilusx/ssh2-sftp-client/blob/4d6e4ae0811cfe97cbbb966bdcf1ad6c6d3a52f0/src/index.js#L143

**Comment by juanddiaz13** [comment]
I see my mistake now. I read the documentation for v9.0 and it says 
![image](https://user-images.githubusercontent.com/20101153/181600753-3b5ed6cf-cd80-48a1-8cea-e5910024cea8.png)

I just checked and I have a lower version so I guess I'm supposed to use a regular expression. 

Thanks a lot @AndrewLane !

**Comment by AndrewLane** [comment]
@juanddiaz13 I'm confused, are you saying you're running something older than v9.0?  I'm looking at the README and I see this, which I can't actually find in the code for some reason.  I'm confused how the readme works in this repo, but I'm sure @theophilusx will straighten me out.

![image](https://user-images.githubusercontent.com/479232/181601277-97259d3c-8b34-4494-8668-fb48a95086fe.png)

**Comment by AndrewLane** [comment]
@juanddiaz13 Excuse my silly mistake, I was looking at a really out-of-date fork locally so I was confusing myself :-).

**Comment by theophilusx** [comment]
That is correct. The list() method took a regexp in versions previous to
9.x. Changing list() to take a function instead was in fact one of the
breaking API changes that resulted in the change of versions from 8.x to
9.x.

I do try to use semantic versioning. In general, changes in major
release numbers i.e. X.0.0, does indicate there has been breaking API
changes. Changing in minor version numbers i.e. 0.X.0, indicate new
functionality has been added that has not broken existing API and
changes in patch level i.e. 0.0.X indicate bug fixes which should not
have changed the API at all.

Note that I do try to create a tag for every release. So if your running
an older version, you can get the documentation for that version by
selecting that tag in the github interface. However, in general, I would
recommend always running the latest version. This is particularly true
for versions 8.x and 9.x as they are based on ssh2 1.x, which is a
rewrite of the previous ssh2 0.8.x version. There were changes in node
v14 which caused problems for ssh2 0.8.x that have been fixed in the
ssh2 1.x rewrite.
