### ISSUE TITLE
Large direcotry 

### ISSUE THREAD

**Issue by eurohost** [theophilusx/ssh2-sftp-client#433]
Trying to list a folder with 80K files in it, I just want the files which were modified for example last month. 

Like would you do in console ls /dir/dir/star 2022-09  star

Any ideas 

Thnaks

**Comment by theophilusx** [comment]
If your looking for a way to limit the number of entries returned from
the server to reduce bandwidth usage, I think your out of luck. The ssh2
API does not provide anything which would allow filtering at the remote
(server) end.

The list() method doe sallow you to pass in a filter predicate which you
can use to filter out only those items from the directory listing which
match your filter predicate. All that it does is pass the filter
predicate function you pass in to a Array.filter() method on the list of
entry items returned by list (or you could just do the same to the
returned list in your code). However, you will be filtering the full
list locally i.e. all 80k entries will be returned. You would probably
use the item.modifyTime property for your filter. I would avoid using
the longname property for the filter as the date format it uses can be
platform dependent and changes for dates older than 12 months. From
memory, the value in modifyTime is milliseconds since epoch (Jan 1st 1970). I
think the ssh2 library returns it as seconds since epoch, but
ssh2-sftp-client converts that to milliseconds to make it easier to
create new Date objects. 

If you have the right access, I would probably be looking to modify
whatever creates/stores the files in the remote sftp server and have it
break things up into smaller directories. Having 80k files per directory
is always going to cause issues. For one thing, some file systems either
have limits on the total number of entries allowed or will have
significant performance issues once you get too large (very much depends
on the filesystgem in use).

**Comment by theophilusx** [comment]
Don't think there is anything else to be added to this question, so closing it. for now.
