### ISSUE TITLE
Unable to get progress with get method

### ISSUE THREAD

**Issue by CPLepage** [theophilusx/ssh2-sftp-client#434]
I am trying to display the download progress while using a `get`. I tried the example from [README](https://github.com/theophilusx/ssh2-sftp-client#how-can-i-limit-uploaddownload-speed) but did not work.

I think it has something to do with how we `pipe` the streams.

❌ doesnt work
```js
  it('get pass through middleware pipe', async function(){
    const localPath = makeLocalPath(config.localUrl, 'get-large.txt');
    const remotePath = config.sftpUrl + '/get-large.txt';
    let dataLength = 0
    const middleware = through(function(chunk, enc, next) {
      dataLength += chunk.length;
      next(null, chunk);
    });
    const out = fs.createWriteStream(localPath, {
      flags: 'w',
      encoding: null,
    });
    await sftp.get(remotePath, middleware.pipe(out));
    const localStats = fs.statSync(localPath);
    return expect(dataLength).to.equal(localStats.size);
  });

// src/index.js : line 558
// is equivalent to
rdr.pipe(middleware.pipe(out), opts.pipeOptions);
``` 

✅ Works
```js
  it('get pass through middleware pipe', async function(){
    const localPath = makeLocalPath(config.localUrl, 'get-large.txt');
    const remotePath = config.sftpUrl + '/get-large.txt';
    let dataLength = 0
    const middleware = through(function(chunk, enc, next) {
      dataLength += chunk.length;
      next(null, chunk);
    });
    const out = fs.createWriteStream(localPath, {
      flags: 'w',
      encoding: null,
    });
    // await sftp.get(remotePath, middleware.pipe(out));
    await new Promise(resolve => {
      let readStream = sftp.sftp.createReadStream(remotePath, { autoClose: true });
      readStream.once('end', () => {
        resolve();
      });
      // this is how src/index.js : line 558 should look like
      // ...I think
      readStream.pipe(middleware).pipe(out);
    });
    const localStats = fs.statSync(localPath);
    return expect(dataLength).to.equal(localStats.size);
  });
```

Since the remote `ReadStream` only resolve after read or write is finished/ended, I cannot add extra piped stream to it. 

I'm not an expert at streams, so please let me know if I'm just missing something. 
Else, please guide me towards a solution and I'll PR.

**Comment by theophilusx** [comment]
From memory, yes, there is a problem with trying to add a throughput
listener using the get method.  IIRC this is related to both the
autoClose setting on the stream and the 'end' setting on the pipe (which
controls whether an end event is emitted when the pipe finishes). Sorry,
it is a while ago and I cannot remember the full details (it is probably
in the closed issues for the project though).

I recently changed the way get/put worked and removed the ability to
modify some of the settings on streams/pipes as that was causing more
issues for the general case and was only useful in a very narrow range
of other use cases. This is also why I added the createReadStream() and
createWriteStream() methods - they provide the low level access
necessary when you want to add this type of functionality and let the
client code have complete low level control. The downside is the client
then becomes 100% responsible for managing the stream resource. 

> Since the remote ReadStream only resolve after read or write is finished/ended, I cannot add extra piped stream to it.

I'm not clear on exactly what the issue is here. You have complete
control over when your promise is resolved or rejected. For example, you
don't have to resolve the promise based on the end event from the write
or read stream. You could, for example, resolve the promise based on the
finish signal from the readStream or the middleware stream or .... It
really depends on what your requirements are and your underlying
design. I suspect you just need to determine what listener to
create/attach to flag your promise as resolved.

If your looking for a very generic solution which would allow you to add
arbitrary numbers/types of additional middleware, it will likely be
challenging to define the generic model your after and have an API which
isn't overly complex or has problematic edge cases you need to
handle. One reason I removed the ability to support arbitrary
combinations of middleware on the get/put methods is because it was
difficult to provide the level of flexibility required without also
creating a complex and difficult to use correctly API.

The design objective for the ssh2-sftp-client module is to provide a
very simple API for the common case (get/put, fastGet/fastPut) and low
level access via createReadStream/createWriteStream which client code
can use for those use cases not supported by get/put or fastGet/fastPut. 

This stuff can be complicated because it involves mixing two different
processing models - the event model associated with ssh2 and streams and
the promise async/await model. Getting these to cooperate reliably can
be challenging (and one reason why ssh2-sftp-client uses lots of
temporary listeners). Sometimes, depending on your use case, you can get
cleaner and easier to maintain code just using ssh2 and not
ssh2-sftp-client, using just an event model and traditional callbacks.

You might also find the npm package stream-handbook useful. It provides
a basic overview and examples for using node streams. While there are
some weeks deep in the streams model, you typically don't need to wonder
into that level of detail. The underlying model is actually quite
straight-forward once you get use to it. 

In my view, the type of functionality you appear to be interested in
seems to be something which belongs in a higher level module which
perhaps uses ssh2-sftp-client or possibly just ssh2. I'm not sure it
fits with the general aim of ssh2-sftp-client, which is to provide a
very simple promise based API for basic sftp operations. However, I'm
happy to consider any PR, but want to flag how important it is that any
enhancement maintains a very simple and consistent API. Unfortunately,
previous attempts added complexity which had too many edge cases that
simply did not work. Even some of the existing API is almost out of
scope (i.e. I don't particularly like the retry mechanism for
connections or the uploadDir/downloadDir functionality, which probably
should be in a higher level module).

**Comment by CPLepage** [comment]
Thanks for the answer. Indeed I don't want to overcomplicate stuff and that's why I didn't start any PR before asking about it.

I guess updating the docs would be the best approach to avoid the confusion.  Let me play around with it a bit more and as soon as I'm confident about it, I'll come back with a clear solution on how to display the progress.

Great job with this package, super useful!

**Comment by theophilusx** [comment]
If you do come up with a working solution which uses
createReadStream/createWriteStream, I would love to add it to the docs
and replace the existing example. Also happy to add a script to the
examples directory in the repo.

If you check the closed issues, you should find a thread from the
original implementation discussion. This will likely give you the clues
necessary wrt where to setup listeners and what signals to monitor for
resolving your promise. From memory, one of the issues for a generic
solution was that the correct listener depends on the middleware being
added.
