### ISSUE TITLE
put method ignores options

### ISSUE THREAD

**Issue by FallenBG** [theophilusx/ssh2-sftp-client#437]
Version 9.0.0 introduces a defect in **put** method. Options passed to it are now overwritten in **_put** and the end result is always just **{autoClose: true}**.

Offending code: https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L700

Proposed solution:
```
opts = {
        readStreamOptions: { ...opts.readStreamOptions, autoClose: true },
        writeStreamOptions: { ...opts.writeStreamOptions, autoClose: true },
        pipeOptions: { ...opts.pipeOptions, end: true },
      };
```

**Comment by theophilusx** [comment]
This is deliberate and covered in the changes section of the README.

If you need to change options at this level, you need to use the
createReadStream/createWriteStream methods, which will give you full
control.

The reason this feature was removed was because it resulted in too many
edge cases that didn't work correctly when these options were set. Given
setting them was only required in far less frequent use cases, they were
removed and the createReadStream/createWriteStream methods added for
when this level of control was necessary.

**Comment by FallenBG** [comment]
Understood. Thanks and sorry for missing that out.
