### ISSUE TITLE
Error when running mkdir on Window based SFTP server

### ISSUE THREAD

**Issue by tungaqhd** [theophilusx/ssh2-sftp-client#438]
We are using version 9.0.4 of ssh2-sftp-client and everything works fine on the Linux-based sftp server. However when we switch to a Windows-based SFTP server (Windows 10 64 bits) with OpenSSH, all commands seem to stop working.

When we run `mkdir` command, these error messages appear in the debug console:

![image](https://user-images.githubusercontent.com/25401332/190943551-6876df0a-5390-405a-aa6f-efc372367c0e.png)

When we use the command line to connect to the server and then execute the `mkdir` command, it works just fine.

We tried to change the path following this instruction but it still doesn't work: https://www.npmjs.com/package/ssh2-sftp-client#sec-4-1

What should we do to have these commands working on Windows?
Thank you.

**Comment by theophilusx** [comment]
First thing I notice is your path has an element called 'repertories' -
is this correct as it looks like a possible spelling/typo error. The
error message indicates the path you are trying to access does not
exist, so please check.

Can you provide  minimal script which reproduces the issue you are
seeing so I can try to reproduce it on my test servers?

**Comment by tungaqhd** [comment]
Thank you for your response,
Here is my script, the `repertories` is a typo but it does exist on my system. The `C:/app/SFTPRoot/projects` has been initialized already
```
const sftp = require("ssh2-sftp-client");
(async () => {
  const sftpClient = new sftp();
  await sftpClient.connect({
    host: "127.0.0.1",
    port: 22,
    username: "ftp",
    password: "ftp",
  });

  try {
    await sftpClient.mkdir("C:/app/SFTPRoot/projects/ok");
  } catch (error) {
    console.log(error.message);
  }
  try {
    await sftpClient.mkdir("/C:/app/SFTPRoot/projects/ok");
  } catch (error) {
    console.log(error.message);
  }
  try {
    await sftpClient.mkdir("C:\\app\\SFTPRoot\\projects\\ok");
  } catch (error) {
    console.log(error.message);
  }
})();
```

I tried with 3 paths and here is the error messages
![image](https://user-images.githubusercontent.com/25401332/190947462-13d33a09-43b2-4425-8b45-e10372d9597d.png)

**Comment by theophilusx** [comment]
I will try to see if I can reproduce the issue, but that won't be for a
few days.

One thing you could try is just doing a few queries to see what paths
the sftp server is serving. For example, you could try a sftp.stat('.')
and an sftp.list('.') and see what is returned.

There is a good chance there is a mismatch between what you think the
path is and what the sftp server actually has as its path.

The other thing you could try is a very simple scirpt which just uses
ssh2 and not ssh2-sftp-client. If that also fails, then we know either
you are trying to use a non-existent path or there is a problem in ssh2
(which would need to be reported to that project). If it works with just
ssh2, then we know the problem is with ssh2-sftp-client, which is quite
possible as I don't use windows and testing on that platform is not as
extensive as it is on Linux.

**Comment by tungaqhd** [comment]
Thank you so much, I will test it on my server and update the result to you here.

**Comment by tungaqhd** [comment]
It turns out that the problem is the path. I used relative path and it work, as `C://app/SFTPRoot` is the default path for the user so I ran `mkdir` with `./projects` instead of `C://app/SFTPRoot/projects`. But I am still curious about what should I use for absolute path?

**Comment by tungaqhd** [comment]
So the problem was I set `ChrootDirectory` in `sshd_config` to `C://app/SFTPRoot`, I commented that line and absolute path worked
