### ISSUE TITLE
Nullish coalescing operator (??)

### ISSUE THREAD

**Issue by saso-petrov** [theophilusx/ssh2-sftp-client#448]
Anyone had same error?

Nov 14 21:13:00 stage node[1474102]: /var/www/sites/api.domain.com/node_modules/ssh2-sftp-client/src/index.js:216
Nov 14 21:13:00 stage node[1474102]:         retries: config.retries ?? 1,
Nov 14 21:13:00 stage node[1474102]:                                  ^
Nov 14 21:13:00 stage node[1474102]: SyntaxError: Unexpected token '?'

It is strange it works from localhost

both has nodejs v16.16.0
and package.json is the same.

**Comment by theophilusx** [comment]
are you using typescript or any other type of trans compiler for JS?
I've seen this error when you have a compliant version of node (which
supports the nullish coalescing operator) but also have an older tool in
your build chain which does not.  Have also seen similar error with
outdated lint tools etc.

**Comment by saso-petrov** [comment]
Tx for fast answer and hints.
I will check all the tools you mention and i will be back here to report what i found.

**Comment by theophilusx** [comment]
Were you able to resolve this one? Would like to close this issue if possible.

**Comment by vste23** [comment]
In the same situation, when running the application under PM2 I get this error.
At the same time this package is working when running .js script with 'node'.

**Comment by theophilusx** [comment]
Sounds like it must be related to something PM2 is doing. The Nullish
operator has been part of standard node versions for quite some time
now. I would verify your pm2 versions is current and perhaps check the
pm2 project site to check this isn't a known issue. It has been some
years since I used pm2, but from memory, doesn't it maintain some state
information? Perhaps there is some stale cached data which is a problem
or it is using an older node interpreter? (I have seen similar problems
when the scheduling tool was using node in /usr/bin, but
development/testing was using node in /usr/local/bin and the /usr/bin
version was a much older version installed as part of the OS)

**Comment by devtonhere** [comment]
I've the same issue with node v12.20.2

With nodejs v16.16.0 it works fine
