### ISSUE TITLE
using the module to load file

### ISSUE THREAD

**Issue by itzikorfa** [theophilusx/ssh2-sftp-client#452]
Hi,
I need the server that receives a string in the request and puts. sends it (using SFTP) 
to a file on a remote machine.
the issue is that I use a serverless function that doesn't let me save files on the function.

is there a way that the put method receives a string and sends a file?

thank you 
Yizhak

**Comment by theophilusx** [comment]
I'm not sure exactly what your asking.

The put() method does not 'receive' anything. It sends data to the
remote server. The data can be a buffer, a stream or a string which
represents a path to a local file to upload.

If I understand your question, I guess you want to call put() passing in
either a buffer (for smaller data amounts) or a readStream (for larger
data amounts). Note that the drawback with a buffer is that it will use
as much memory as the data you want to send, which is why it is only
suitable for small amounts of data. A readStream allows much greater
data upload sizes without using lots of memory.

**Comment by theophilusx** [comment]
As there has been no further activity on this issue since I responded, I'm closing it.
