### ISSUE TITLE
Getting error "Channel 0 (Remote ID:0) closed with open file:SSH FTP error."

### ISSUE THREAD

**Issue by wahajahmed** [theophilusx/ssh2-sftp-client#454]
Hi there,

We are using version 7.2.1 in our application where we a uploading CSV files to an EDI provider's SFTP server. CSV files are being uploaded successfully from our end can be read/consumed by the EDI provider application, but the EDI provider sent this message.

> Your application is generating an excessive number of errors (_and each error create a ticket in our customer support application_) during the EDI communication handshake by not sending an ssh_fxp_close command at the end of our strings. We are pasting the details of their report below. Is this something you would be able to fix? Or is this a 3rd party git library?
> 
> Below is the email we received from our support team for **Channel 0 (Remote ID:0) closed with open file:SSH FTP error.**
>  
> For each SSH_FXP_OPEN command for a file, SSH_FXP_CLOSE also needs to be issued. So for each file you receive you should receive both (SSH_FXP_OPEN & SSH_FXP_CLOSE).
>  If you do not get an SSH_FXP_CLOSE then you will get a close with open file.
>  There are instances where the trading partner will send both an SSH_FXP_CLOSE and a quit at the same millisecond.
>  SSH is a command response protocol so, if we receive the quit prior to SSH_FXP_CLOSE, the connection would be terminated and closed with open file would occur.

Below is the code we are using to upload the file.

```
function UploadFileToSFTPServer(localFilePath, remoteFilePath) {
  console.log('UploadFileToSFTPServer >> localFilePath', localFilePath);
  console.log('UploadFileToSFTPServer >> remoteFilePath', remoteFilePath);
  const sftp = new SFTPClient('client');
  return sftp.connect(SFTP_CREDENTIALS)
    .then(() => {
      let options = {
        writeStreamOptions: {
          flags: 'w',  // w - write and a - append
          encoding: null, // use null for binary files
          mode: 0o200, // mode to use for created file (rwx)
      },
      readStreamOptions: {
        flags: 'r',
        encoding: null,
        handle: null,
        mode: 0o200,
        autoClose: true
      },
      pipeOptions: {
        end: true
      }
    };
      return sftp.put(localFilePath, remoteFilePath, options);
    })
    .then(() => {
      return sftp.end();
    })
    .catch((err) => {
      console.error('UploadFileToSFTPServer error', err.message);
    });
}
```

How this can be fixed? What we are doing wrong here?

Thanks.

**Comment by theophilusx** [comment]
The first thing you need to do is upgrade to the current version.

If the error still exists, it is likely an error with the ssh2 module
which this module depends on. If this is the case, it will be necessary
to demonstrate that the ssh2 module is the culprit by creating a simple
example which uses just ssh2 (for your use case, this will be quite
straight-forward and I can probably help with that, though I won't have
time until after the new year).

There has been some significant changes in the ssh2 module since the
version bundled with ssh2-sftp-client v7.x and a good chance this issue
has been resolved in the current version.

Note that the current version does have some API changes, so you will
need to slightly modify your script to work with the current
version. However, based on  the code you provided, this should also be
straight-forward.

**Comment by theophilusx** [comment]
Does this issue need to remain open or can it be closed?
