### ISSUE TITLE
Error from JS Client but works from CLI and GUI Apps

### ISSUE THREAD

**Issue by dalisoft** [theophilusx/ssh2-sftp-client#459]
Error message: `connect: getConnection: All configured authentication methods failed`

Config defined
- host
- username
- privateKey
- port

Maybe these fix this bug:
- https://github.com/mscdex/ssh2/pull/1200

Maybe related issue:
- https://github.com/mscdex/ssh2/issues/989
- https://github.com/beekeeper-studio/beekeeper-studio/issues/1240

One more resource
- https://www.reddit.com/r/linuxquestions/comments/qgmnnh/ssh_key_no_mutual_signature_algorithm/

**Comment by theophilusx** [comment]
This error typically occurs because the remote sftp server you are
trying to connect to does not support any of the default key exchange or
cipher algorithms being used. There are a number of additional key
exchange algorithms and ciphers which can be enabled using the
algorithms property of the connect method. See the ssh2 documentation
for details.

One method I find useful is to use openssh' CLI sftp program, add -vvv
to turn up debugging information and try connecting to the remote
server, The debug information will show you what key exchange algorithm
is being used and which cipher ends up being agreed upon. Once you have
this information, you just need to find out what the ssh2 program calls
those key exchange algorithms and/or ciphers and set them in the
algorithms propety in the connect call.

**Comment by dalisoft** [comment]
I sure it will fix this bug https://github.com/mscdex/ssh2/pull/1200

For now, on server changing as mentioned [here](https://github.com/mscdex/ssh2/issues/989#issuecomment-1060395050) works, but without this **Cyberduck macOS** and **sftp cli** works fine

**Comment by theophilusx** [comment]
Well as this is an ssh2 issue, there is nothing I can do as this module uses ssh2. So, until ssh2 is updated, your only option if you want to use this library is to use a different key signing algorithm, such as ssh-ed25519 (this is what I do) or find a different library.
