### ISSUE TITLE
Error: Permission denied

### ISSUE THREAD

**Issue by ferrygun** [theophilusx/ssh2-sftp-client#460]
I am getting Permission Denied in the middle of streaming.

This is my code:

```
const Client = require('ssh2-sftp-client');
const os = require('os');
const client = new Client();
const fs = require('fs');

const connSettings = {
    host: '',
    port: '22',
    username: '',
    password: ''
};

fs.readFile('test.txt', 'utf8', (err, data) => {
    if (err) {
        console.error(err);
        return;
    }

    const buffer = Buffer.from(data);


    var content = buffer

    let numProcesses = 2;//os.cpus().length;

    const chunkSize = Math.ceil(content.length / numProcesses);
    const chunks = [];



    // Divide the content into chunks
    for (let i = 0; i < numProcesses; i++) {
      const start = i * chunkSize;
      const end = start + chunkSize;
      console.log(start + ":" + end)
      chunks.push(content.slice(start, end));
    }

    // Connect to the SFTP server
    client.connect(connSettings)
    .then(() => {
      // Create an array of promises for uploading the chunks
      const uploadPromises = chunks.map((chunk, index) => {
        return client.put(Buffer.from(chunk), 'in/kyriba.txt');
      });

      // Wait for all the chunks to be uploaded
      return Promise.all(uploadPromises);
    
    }).then(() => {
      console.log('Content successfully uploaded!');
      client.end();
    }).catch(err => {
      console.log(err);
      client.end();
    });
});
```

> Error: Permission denied
>     at SFTPStream._transform (/Users/node_modules/ssh2-sftp-client-fast/node_modules/ssh2-streams/lib/sftp.js:410:27)

**Comment by theophilusx** [comment]
Is there a reason you need to use buffers rather than just using a
stream? Just looking at your code, I suspect there is likely some
unexpected interaction between all the different promises and I suspect
the model you are using will very likely result in file corruption.

If you just get a read stream from the local file and pass that in
rather than the buffer, it will likely be faster and more reliable.

Another alternative, if your sftp server supports it, is to try
fastPut(). This will transfer the file in concurrent chunks for you and
you don't need to worry about breaking the data up into chunks or
ensuring the chunks are all sequenced correctly. The one downside with
fastPut() is that not all sftp servers support concurrent data transfers.

I think you need to re-think your algorithm. Breaking up the data into
chunks and then making separate calls in an array of promises is
unlikely to work reliably and will almost certainly have poor
performance.  Either use fastPut() or just use a read stream (buffers
are really only good for small amounts of data and/or when you have a
process generating data in small amounts. The other problem with buffers
is that you need the same amount of memory as the size of your
file. Streams are much better as they don't need as much memory and are
far more efficient.

**Comment by ferrygun** [comment]
Thanks for your response. Can I use the fastPut method with the input parameter in string (not file path), which part I need to modify? The reason is I need to integrate this lib with low code no code platform which only accept the string as an input param.

**Comment by theophilusx** [comment]
The two big limitations with fastPut(0 are that 

1. It only allos specification of a file path as input
2. Not all servers support fastPut's use of parallel processing of the data.

So, to your question, I guess the answer would be no. 

My suggestion would be to modify your code and don't try to process multiple put requests on the same file concurrently. I am pretty certain the error you are getting is because one put promise is trying to access the remote file when it is still locked and being used by one of the other processes. Just upload your file in one call to put(). You could have multiple calls to put() provided they are to different remote files. However, I suspect  you won't get the speedup you would expect as the more parallel put command running, the smaller the throughput for any individual file.
