### ISSUE TITLE
Question - Unable to provide Host Keys for connection (for using password and key authentication)

### ISSUE THREAD

**Issue by liester** [theophilusx/ssh2-sftp-client#467]
Hello,  I've been using the library to connect to my SFTP server and it has been working great.  I've run into a problem where the SFTP server has been updated to require both a password and a private key.  This was a security preference by my team.

I see in the `ssh2` client that `ssh2-sftp-client` wraps there is a `hostKeys` value.  However, I'm not seeing a way to do that with this library.  I was wondering if maybe I had missed something and if there was a way to do authentication with username, password, and private key.

I tried providing 
```JS
const client = new SftpClient();
await client.connect({
  username: 'xx',
  password: 'xx',
  host: 'xx',
  privateKey: 'xx'
});
```

but it didn't appear to work.  Error: `All configured authentication methods failed`

This is the line in the source that I think the hostKeys could be provided
https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L20
```JS
class SftpClient {
  constructor(clientName) {
    this.version = '9.0.4';
    this.client = new Client();
    this.sftp = undefined;
    this.clientName = clientName ? clientName : 'sftp';
    this.endCalled = false;
    this.errorHandled = false;
    this.closeHandled = false;
    this.endHandled = false;
    this.remotePathSep = '/';
    this.remotePlatform = 'unix';
    this.debug = undefined;
```

If it isn't possible, that is okay.  I will have to find an alternative.

Cheers

**Comment by theophilusx** [comment]
I think the decision to require both a password and a key is quite
misguided. What risk is this supposed to mitigate and how likely is it
to occur? By far, the most common cause of security failures is not
being 'hacked' by cracking passwords and ssh keys, but rather by system
administration errors due to overly complex policies and
configurations. Far better off just having a key with a strong
passphrase and good policies and procedures to manage those keys
IMO. Requiring both a password and a key indicates poor confidence in
key management and a mistaken belief that adding another layer will
mitigate that risk. Reality is, if your key management processes are
that poor, the password management processes are likely just as
poor. Having additgional poorly managed processes doesn't improve
security - in fact, will likely make it worse. 

I think the ssh2 library does permit custom authentication
handlers. You will need to look at the ssh2 documentation to work out if
you can satisfy this requirement. This module just uses the facilities
provided by the ssh2 library it depends on for all authentication
support, so if it is supported by ssh2, it will work with
ssh2-sftp-client. If it doesn't, I cannot do anything to address it.

**Comment by liester** [comment]
These are fair criticisms of my approach.  I think it is fair to say that there is little to no difference between requiring 
1. username/password/private key 
2. and your suggested approach of username/private key/passphrase.

Since both the password and passphrase will be stored as environment variables provided by the system I'm in for changing my approach.

For what it's worth, I did briefly look into using the underlying ssh2 module.  I think the convenience of the ssh2-sftp-client library would outweigh the benefits of doing it "my way" with the implementation I plan to use.

Thank you for your quick response.

Cheers,
   Levi
