### ISSUE TITLE
handshake timeout on version ^9.0.4

### ISSUE THREAD

**Issue by ryd0rz** [theophilusx/ssh2-sftp-client#472]
Attempting to connect and getting handshake timeout... here's the log:

```
CLIENT[sftp]: connect: Connect attempt 2
Custom crypto binding available
Local ident: 'SSH-2.0-ssh2js1.11.0'
Client: Trying xxx.yyy.com on port 22 ...
Socket connected
Remote ident: 'SSH-2.0-7.9.0.0_openssh Globalscape'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) C->S cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr
Handshake: C->S Cipher: aes128-ctr
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) S->C cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr
Handshake: S->C cipher: aes128-ctr
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-96
Handshake: C->S MAC: hmac-sha2-256
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-96
Handshake: S->C MAC: hmac-sha2-256
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: zlib,none
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: zlib,none
Handshake: S->C compression: none
Outbound: Sending KEXDH_GEX_REQUEST
Received DH GEX Group
Outbound: Sending KEXDH_GEX_INIT
CLIENT[sftp]: connect errorListener - ignoring handled error
CLIENT[sftp]: Global: Ignoring handled error: Timed out while waiting for handshake
CLIENT[sftp]: connect: getConnection: Timed out while waiting for handshake (ERR_GENERIC_CLIENT)
```

Using default settings, and only supplying the username, host, password, and debug.

**Comment by theophilusx** [comment]
There are two common causes of this issue

1. The remote server is slow to respond and/or it takes time to
perform key exchagne and cipher negotiation.

2. The algorithm selected is one of the very slow algirthims and
timeouts are occurring because of the time it takes to encrypt/decrypt
data.

Two common solutions are

1. Increase the ready timeout value as part of the connection config
object (see the ssh2 documentation)

2. Force the selection of a faster algorithm. This can be done by
setting properties in the algorithms property of the config object
passed in when calling connect. You do need to ensure your selecting
algorithms which are supported by both ends).

My recommendation would be to start by increasing the ready timeout
value and see if that helps. If it doesn't, then look into forcing a
connection wich uses specific algorithms for ciphers and key exchange.

You might also find some useful information looking at the open and
closed issues in the ssh2 repository. as I recall this has been
discussed on a number of occasions (there was one issue, which I cannot
find right now, which talks about which algorithms are notoriously slow
and often result in timeout errors).  

It can also be very helpful to use the openssh client to connect to your
remote server adding the -vvv flag to turn up debugging. THis will show
you which algorithms openssh has begotiated and wlll verify your remote
sftp server is working (people often report ssh2-sftp-client issues that
turn out to be remote server or firewall issues). 

Finally, this issue is a low level issue associated with the ssh2 module
which this library uses. If the issue persists, you will need to log an
issue with that project. You will need to be able to demonstrate the
issue exists using just ssh2.

**Comment by ryd0rz** [comment]
Updating with some steps I took to fix in case anyone else needs...

Determined the issue was happening only on node:14.16.1-alpine image... however, the steps to solve could be the same even if your not using docker, alpine, or the same versions of node/linux...

I determined my issue was ssh2 related as most of these will be.

I then ran the following node script on the docker which had issues:

[code]
const { Client } = require('ssh2');

const conn = new Client();
conn.on('ready', () => {
  console.log('Client :: ready');
  conn.sftp((err, sftp) => {
    if (err) throw err;
    sftp.readdir('foo', (err, list) => {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
}).connect({
  host: 'mycoolhost.coolwebsite.com',
  port: 22,
  username: '1234',
  password: 'asdf',
  debug: console.log,
});
[/code]

Someone said in the ssh2 repo's issues on github that it could be a slow algorithm. In the debug of the above code, it was telling me which algorithms were supported by the server... so I tried each of them until one of them worked. If you look at the logs, you will see server algorithms. 

Here is the config that ended up working:

[code]
{
  host: 'mycoolhost.coolwebsite.com',
  port: 22,
  username: '1234',
  password: 'asdf',
  debug: console.log,
  algorithms: {
    kex: [
      'diffie-hellman-group16-sha512',
    ],
  },
}
[/code]

The issue could vary per environment, and not everyone gets lucky with a working algorithm. In the case you don't find a working algorithm, you would need to look at changing your linux version, or in my case it would have been the docker image. You could also look at downgrading to a version of ssh2-sftp-client that uses older version of ssh2 which for some reason would be faster in the sha256 algorithm (not sold on the downgrading option, but some reported it worked)  (v7 i saw some had success).

Anyways, happy hunting.
