### ISSUE TITLE
can not import ssh2-sftp-client in Node.js v16.14.0.

### ISSUE THREAD

**Issue by g4nd4lf** [theophilusx/ssh2-sftp-client#473]
I can not import ssh2-sftp-client in VUE3 under Node.js v16.14.0.

✘ [ERROR] No loader is configured for ".node" files: node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node

    node_modules/ssh2/lib/protocol/crypto.js:30:20:
      30 │   binding = require('./crypto/build/Release/sshcrypto.node');
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".node" files: node_modules/cpu-features/build/Release/cpufeatures.node

    node_modules/cpu-features/lib/index.js:3:24:
      3 │ const binding = require('../build/Release/cpufeatures.node');
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is my App.vue:

```
<template>
	<div>
	  <h2>List of files:</h2>
	  	{{ end }}
	</div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';
  import Client from 'ssh2-sftp-client';
  const end=ref("loading data...")

  </script>  
```

**Comment by theophilusx** [comment]
That error is usually seen when your trying to load ssh2-sftp-client
into a browser environment, not a node environment. The browser JS
environment doe snot incldue the required crypto libraries.

My guess is that your using some sort of build tool or packager which is
trying to load the module into a browser environment. This is definitely
an issue in your local environment.

**Comment by g4nd4lf** [comment]
Thanks for your help, 
If I import the library in a basic node.js web as:
`const Client = require('ssh2-sftp-client');
`
it works well, but if i try to import in my VUE3 project as:
`import { Client } from 'ssh2-sftp-client';
 ` it fails. 
I am testing the project using: 
```
npm install
npm run dev

```

**Comment by theophilusx** [comment]
what exactly does 'dev' execute when you do 'npm run dev'? I've
typically seen it call various build chain tools like babel, parcel,
webpack etc. I've seen all of these cause problems due to
misconfiguration where the system is assuming everything is browser
compatible. That error you are seeing is typical when something is
trying to load the package into a web browser environment. 

It is possible that when you use require(), your build tool recognises
this means it must be node (non-browser) code and loads it correctly,
but when you use ES import, it thinks it is a browser module and tries
to load it into a browser environment (just guessing here). 

As the ssh2-sftp-client module is a node module and CommonJS is the
default module format for node, I always use require with node modules
and only use import with general JS modules and modules designed for the
browser. I have encountered lots of issues with node's ES module
implementation and so stay away from it (admittedly, I've not used it
since about node 14). 

VUE is a web front end framework isn't it (like angular and react?). How are you
expecting to use ssh2-sftp-client in that scenario given it doesn't work
in web browsers? I'm assuming you are doing something at the back-end
using express or similar. IN which case, it is all node and you can just
use require.  I suspect you probably need to add configuration to your
build tool chain to ensure it only tries to load the module in a node
environment and it isn't trying to package it up or run it through babel
or some other transpiler etc. 

I would just use require and not import and not worry about it.

**Comment by theophilusx** [comment]
I believe this is a client configuration error (based on info in first post re <script>....</scirpt> setting. You cannot use this module inside a browser JS environment. It works only inside node and you should use require() not import as it is a commonJS moudle.

**Comment by theophilusx** [comment]
FYI if you REALLLY want to use ES Module format rather than Node's default commonJS moudle syntax, you can do so. However, you need to tell node you are using ES6 modules, either by calling your script with an extension of *.mjs instead of *.js or by adding the "type": "moudle" to the toplevel in the package.json file. As an example, the following works with Node v18

````js
import path from 'path';
const dotenvPath = path.join('.', '.env');
import dotenv from 'dotenv';
dotenv.config({
  path: dotenvPath
});
import ssh2SftpClient from 'ssh2-sftp-client';

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22
};

const sftp = new ssh2SftpClient();

let remotePath = process.argv[2];

async function main() {
  await sftp.connect(config);
  let fileList = await sftp.list(remotePath);
  console.log(fileList);
  await sftp.end();
}

main().catch((e) => {
  console.error(e.message);
});
````

Note that it can sometimes be tricky to identify exactly the right format for import lines when referencing Node modules and I have encountered issues with some node modules. At this time, I think it is still better to use commonJS module style in node and use ES modules in the browser.
