### ISSUE TITLE
method fastGet() doesn't support spaces in file name

### ISSUE THREAD

**Issue by Med-El-Mobarik** [theophilusx/ssh2-sftp-client#476]
I'm trying to download a file that contains spaces in its name from an sftp server using the method `fastGet()`.
the methode throws an error `No such file`, I removed the spaces from the name and it worked fine.

I'm not sure if this a feature or a bug.

Ps: with the method `get()` it works fine.

**Comment by theophilusx** [comment]
This is either an issue with ssh2 (module used by this module) or more
likely, a 'feature' of the sftp server you are using.

Note that fastGet/fastPut are not standard facilities supported by all
sftp servers. How they are implemented vary considerably. When the
server has implemented solid support, they work well. However, I have
found many servers do not support it reliably and sometimes, you are
just far better off using get/put instead.

In general, filenames with spaces can be problematic because not all
file systems and associated utilities handle them consistently. While
most modern file systems are pretty good, there are still many out there
which require escaping of spaces. You could try various things like
putting a '\' before the space or enclosing the filename in single "'"
characters.

As there is nothing this module does differently between get/put and
fastGet/fastPut with respect to filenames, I don't think this is an
ssh2-sftp-client issue or anything which can be handled at the
ssh2-sftp-client level. You could ask the ssh2 project for their
opinion.
