### ISSUE TITLE
How can I limit upload speed？

### ISSUE THREAD

**Issue by alanhg** [theophilusx/ssh2-sftp-client#482]
In the example in the README, it demonstrates how to throttle the download speed. But could you provide an example of how to limit the upload progress? I'm not quite sure how to write it. Also, regarding the example of throttling the download speed, does the bandwidth limitation essentially restrict the speed from the target SSH machine to the SSH client server here, or does it not affect the bandwidth of the target machine and instead restrict the throughput within the memory area of the client?

https://github.com/theophilusx/ssh2-sftp-client#how-can-i-limit-uploaddownload-speed

the following is right?

```js

const readStream = createReadStream(localPath);

// pipe streams together
readStream.pipe(throttleStream).pipe(progressStream)

try {
  // set autoClose to false
  await client.put(remotePath, throttleStream, { autoClose: false });
} catch (e) {
  console.log('sftp error', e);
} finally {
  await client.end();
}
```

**Comment by theophilusx** [comment]
First, I'm afraid I've not got time to work out and write up an example
for limiting upload speeds. You will need to work this out for yourself.

The provided examples were contributed by users who needed this
functionality. I've never needed or found such throttling useful.

IMO this sort of rate limiting is difficult to implement in a reliable
manner. What you are actually doing is essentially putting in code to
make the system 'sleep' for a short period to slow down either how fast
it sends data to the socket or reads it from the socket. As throughput
depends on many variables you don't have control over, how effective
this is or how accurate it is is nearly impossible to monitor and
calculate (e.g. you have no control over available bandwidth and no
really reliable way of calculating it without going into low level OS
network stack calls or doing 'samples', which are unreliable if small
and self-defeating if large).

In most use cases I've been involved in, the concept of rate limiting is
actually misguided and more often than not, when there is a problem,
makes things worse. For example, you limit the rate to half available
bandwidth, supposedly to allow other things to have bandwidth
available. What actually happens is you get poor performance from
everything for twice as long. If on the other hand, you do nothing, you
have poor performance for half as long and then normal performance
thereafter. The only time I've seen rate limiting of any real benefit
has been when the download involves extremely large files and is going
to completely saturate the link for hours. In such cases, you are better
off managing the rate limiting at the network/router layer or via QoS
network facilities etc. When you have such large files, you are usually
better off using a more sophisticated transport facility that will allow
interrupted transfers to be resumed (like rsync). If on the other hand,
your dealing with lots of small files, then your better off just putting
a pause between each file to reduce bandwidth usage and allow other
processes some bandwidth. 

The question I would ask is why do you feel you need rate limiting? What
problem are you trying to solve? Is this an actual problem you have
encountered or more a 'theoretical' one?

**Comment by alanhg** [comment]
Since my server has to handle a large number of SSH and SFTP connections simultaneously most of the time, bandwidth and resources are limited, so it is necessary to consider speed limits for uploads and downloads.

**Comment by theophilusx** [comment]
If you haven't actually encountered any issues yet, you could be in danger of premature optimisation. Keep in mind that if you limit bandwidth, you will almost certainly increase the number of simultaneous connections as now clients will be connected for longer. This will also consume resources. With modern network speeds, the number of connections rather than the traffic throughput is often more of a bottle neck. Besides, if you have a really large number of connections, your unlikely to reach your bandwidth limits anyway.  Far better off letting the network stack sort this sort of stuff out and if you have to, just limit the number of connections your server will accept at any one time. For bandwidth to be the issue, you must either have a very very small pipe (i.e. less than 10Mbps,) or be dealing with connections in the thousands, in which case server memory is likely going to be the bottle neck before bandwidth is. 

You really need to benchmark this and get some real figures before you consider any form of traffic shaping.
