### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by roberthills** [theophilusx/ssh2-sftp-client#485]
When attempting to upload a 20MB Gzip file using the `put` method in an AWS Lambda function, the Lambda fails with the error message `The process cannot access the file because it is being used by another process`. Even though the Lambda fails, the upload process continues in the background and the file successfully uploads to the target destination. However, it becomes challenging to track or provide feedback on the upload completion status due to the Lambda failure. Any pointers would be appreciated.

**Comment by theophilusx** [comment]
I would need to see a sample script which reproduces the error before I
can provide any meantingful suggestions. I can say that I have had only
one person report a similar error in the past and that turned out to be
a logic bug in their script (they were trying to do the upload before
the gzipped process had completed). The error you are seeing occurs when
you try to manipulate/read a file which is already locked by some other
process (such as a write process).

Are you gzipping the file and then using put() to upload it or are you
gzipping the stream 'on the fly' and passing that to put() or are the
files already gzipped and your just calling put()?

If you can put together a minimal script that is able to reproduce the
error, post it and I'll have a look. However, please ensure you run the
exact same script and verify it creates the error before posting it
(I've lost count of the number of times people have posted a sample
script and I've spent hours tyring to reproduce their error only to find
out the problem was in the bit of code they cut out of their example).

**Comment by roberthills** [comment]
Thanks for the quick response. I've managed to resolve this now. I'm using the `nest-sftp `package, which is a NestJS service that utilises this library under the hood. I discovered that it was an outdated version (8.0.1). By adding a dependency resolution for the latest version of `ssh2-sftp-client,` I was able to resolve the issue I was experiencing.

For some context, I had tried gzipping the stream on the fly and attempting to put a local gzip. However, this is no longer an issue as the latest version has fixed the problem. Thanks again.
