### ISSUE TITLE
Issue with disconnect in middle of fastGet / Get from a sftp server

### ISSUE THREAD

**Issue by Skipperia** [theophilusx/ssh2-sftp-client#486]
Hi,

I had issues with simulating bad connections of a client from in our internal network. We are physically disconnecting the PC while downloading from a sftp server.  I have noticed that it does not consistently throw an exception of a timeout and just hangs. I have tried editing the readyTimeout value but does not seem to change the issue.

Would love some tips how to handle such event since it doesn't seem that the Client object go to the error, end or close event listener callbacks I have created. Am I missing something?

Thanks.

**Comment by theophilusx** [comment]
What version of ssh2-sftp-client?

What version of node?

What platform (Windows, Linux, macOS, etc)?

Can you provide a minimal example script which replicates the issue?
This would help a lot.

In most use cases, you should not need to add any listeners at all. All
errors should be caught and handled by the module. The readyTimeout
won't help as that only applies to the initial 'ready' signal used in
the initial connection setup.

Note that if your not running the 9.1.0 version, you need to upgrade as
bugs in ssh2-sftp-client have been addressed and it uses the most recent
version of ssh2.

**Comment by Skipperia** [comment]
Hey, 

Sorry for the delay, we were using an older version of ssh2-sftp-client but upgraded recently to 9.1.0.

We are forced to use NodeJS14, would that be an issue? Linux CentOS 7

As this code is developed and executed on a standalone network I cannot import it here.
We run a generator for promises of sftp downloads. Each promise gets a SFTPClient instance that is used multiple times (We do not recreate the instance unless it has an issue and does not respond to a simple .list('/') execute that we check before every getInstance call.) Incase the SFTPClient does not respond before initiating the get/fastGet calls, we try recreating the connection by closing the SFTPClient instance and creating a new one.

The maximum amount of parallel promises is currently 3, for which we simply promise.all() them before calling the generator again for the next 3.

Just clarifying, we do not call for .end and the .connect again for the same instance. We make sure to create a new SFTP object before trying again.

We are trying to emulate many fail scenarios, bad network or just slow connections, so creating a sudden physical ethernet cable disconnection is not a rare occurrence that we want to make sure to handle properly.

Thanks in advance for your help, I will try to expand on anything if I wasn't clear.

**Comment by theophilusx** [comment]
One of the bigs fixed in 9.1.0 was related to the handling of network
failures. Prior to 9.1.0, some network failures (depending on the type
of error and exactly where it occured) were not caught and
handled/reported correctly. This would result in the process exception
rising up and cause the process to exit with an uncaught exception
error.

I *think* it should still work in node v14, but you are right on the
edge of support. From memory, a couple of the unit tests use node
features not available in v14, but the code does not. So while it will
likely fail unit testing, it should still work OK.

I guess all you can do is try it out and see. I'm not sure what the
support is wrt node versions and the underlying ssh2 module. If I get a
chance in the next few days, I'll see if I can run the unit tests using
node v14. Anyh version before v9.1.0 0f ssh2-sftp-client is likely to be
unreliable for a small set of network errors.

Note that depending on how old the version is you have been using, there
may be some API compatibility issues. In particular, the itnerface
relating to various filters for get/put and dirUpload/Download, option
setting for put/get and dirUpload/dirDownload have changed.

**Comment by Skipperia** [comment]
Thank you for your input, we will try to push for an update of nodejs on those standalone clients and see if we reproduce the issue.
