### ISSUE TITLE
Handshake failed: no matching C->S cipher

### ISSUE THREAD

**Issue by memetscc** [theophilusx/ssh2-sftp-client#494]
Using normal ssh while in tabby i am able to connect to the server. However using when i use the connection profile it failed to connect with the error:
Handshake failed: no matching C->S cipher

Please help. Thanks.

**Comment by theophilusx** [comment]
I am travelling at the moment and won’t be back in reliable internet service areas until October, so cannot provide much direct assistance. However, this issue is documented in both the ssh2-soft-pedalling-client README, ssh20sftp-client past issues and ssh2 issues. Essentially, it just means your ssh server does not support any of the default SSH ciphers, so you need to set a non-default cipher as part of the connection parameters.Sent from my iPadOn 31 Jul 2023, at 1:15 pm, memetscc ***@***.***> wrote:﻿
Using normal ssh while in tabby i am able to connect to the server. However using when i use the connection profile it failed to connect with the error:
Handshake failed: no matching C->S cipher
Please help. Thanks.
