### ISSUE TITLE
How to download multiple files ? or files from a directory?

### ISSUE THREAD

**Issue by vpkreddi** [theophilusx/ssh2-sftp-client#50]
Hi,
please provide some sample code for downloading multiple files or all files from a directory?

**Comment by kyushiro** [comment]
Any updates on this? i am trying to do the following within an async function:

`    ---

    let main = async () => {
        await sftp.connect(config.sftp);
        let data = await sftp.list(config.remote_dir);
        if (data.length) data.map(x => {
            await sftp.fastGet(`${config.remote_dir}/${x.name}`, config.base_path + x.name);
        });
    }
`

Result? the first file is successfully downloaded, and then the app crashes with 

> Error: Failed to get sandbox/demo2.txt: The requested operation cannot be performed because
there is a file transfer in progress.

I figured this seems to mean the promise is resolving before the first file tansfer is completed, but since it is actually correctly donloaded means the app did not completely crash...? i could try working around with a try catch but seems hacky as hell. Anyone managed to find a robust way of doing this?

**Comment by kyushiro** [comment]
I figured out, since the issue was concurrent download attempts on one client connection, i could try to manage it with one client per file download. I ended up with the following recursive function.

```
let getFromFtp = async (arr) => {
    if (arr.length == 0) return (processFiles());
    let x = arr.shift();
    conns.push(new Client());
    let idx = conns.length - 1;
    await conns[idx].connect(config.sftp.auth);
    await conns[idx]
      .fastGet(`${config.sftp.remote_dir}/${x.name}`, `${config.dl_dir}${x.name}`);
    await connections[idx].end();
    getFromFtp(arr);
};
```

Notes about this function:

- The array parameter is a list of files to download, presumably fetched using list() beforehand

- conns was declared as an empty array and is used to contain our clients.

- using array.prototype.shift(), to gradually deplete the array as we go through the file list

- the processFiles() method is fired once all the files were downloaded.

- this is just the POC version. of course we need to add the error management to that.

**Comment by theophilusx** [comment]
There has been significant changes to the module since the original issue was logged, so not sure it is still relevant. However, I have been using the module to download multiple files using 1 client fine for some moths now. I am closing this issue as I suspect the changes made earlier this year have either fixed whatever issue may have existed or the issue will have changed sufficiently to warrant a new issue being logged.
