### ISSUE TITLE
Error: get: No response from server

### ISSUE THREAD

**Issue by blaasvaer** [theophilusx/ssh2-sftp-client#520]
I cannot simply get a file from the remote server. The file is there alright (can get it trough the Terminal using sftp). And if I pass the wrong path I get the correct (file not found) error:

```
Error: get: No such file. <filename>
```

But if the path is correct I get:

```
Error: get: No response from server <filename>
```

I'm using this:

```
let file_destination = fs.createWriteStream('./local/path/' + filename);
sftp.get( '/remote/path/' + filename, file_destination );

```

What is it about this package that I'm completely missing?

**Comment by theophilusx** [comment]
What version of node?
What version of ssh2-sftp-client?
What platform (Windows, Linux, Mac)?

Calls to get() (and other methods) return a Promise. You need to either
use async/await or a promise().then() chain.

However, not sure that is actually your issue (certainly no indication
of either in your example). 

I would try after setting a debug function in the config options object
and see if that provides more details.

**Comment by blaasvaer** [comment]
ALL I'm trying to achieve is this, and it has turned into a complete nightmare:

```
import fs from 'fs';
import Client from 'ssh2-sftp-client';

const sftp = new Client();

const config = { … }; // Left empty on purpose

sftp
.connect(config)
.then(() => {
	return sftp.list('/tkg');
})
.then( async ( files ) => {
	files.forEach( async ( file ) => {
		let remotePath = '/tkg/' + file.name;
		let localPath = fs.createWriteStream( './backup/new/' + file.name );
		
		await sftp.get( remotePath, localPath );
	});
})
.then(() => {
	sftp.end();
})
.catch(err => {
	console.error(err.message);
});
```

**Comment by theophilusx** [comment]
Just a very quick response as it is late here and I have to go....


Upgrade to latest ssh2-sftp-client (10.0.3).

If you want all files from a directory, you could look at using the
downloadDir() method. If not, your approach is sort of correct, but with
a couple of issues.

- Don't mix promise().then() chains and async/await. It is very error
prone and things tend not to work as you might think. In your case, your
then() block with the loop in it is not returning a promise and will
return immediately, casuing the final then() block to run and close the
connection.

- Don't use array comprehension mehtods with promises i.e. .forEach,
  .filter etc. They are not promise safe and won't work correctly with
  async/await unless you take additional steps which make them less
  convenient and which also clutter the code. Much better and cleaner to
  just use a normal for loop. However, you will still need to do
  additional work as you want that then() block to return a promise
  which will only be fulfilled once the files are downloaded.

In your use case, I would probably just write the whole thing as an
async/awit verison rather than use promise chains. i.e.

try {
  await sftp.connect.....
  let files = await sftp.list....
  for (let f of files) {
      await sftp.get......
  }
  await sftp.end....
} catch ....

FInally, don't forget that you probably need to verify what is returned
by sftp.list are all just files (i.e. not directory, sym link, other
file devices etc).

**Comment by blaasvaer** [comment]
OK, finally figured it out. I think my assumptions about the package were WAY OFF. I'd (probably wrongly) 'expect' that a package would make things 'easier', as in pass in the remotePath and the localPath and have the package do the 'heavy' lifting ... well, the heavy part turned out to be not that heavy after all. But my wrong assumption had me banging my head against for wall for way too long ... please, add the following to your examples, if you think it might help someone else:

```
const sftp = new Client( 'optional-name' );

let config = { … };

sftp
	.connect(config)
	.then(() => {
		return sftp.list('/tkg');
	})
	.then( ( files ) => {
		let promises = [];

		files.forEach( ( file ) => {
			let remotePath = '/tkg/' + file.name;
			let localPath = fs.createWriteStream( './backup/new/' + file.name );

			promises.push( sftp.get( remotePath, localPath ) );
		});

		return Promise.all( promises );
	})
	.then(() => {
		sftp.end();
	})
	.catch(err => {
		console.error(err.message);
	});
```

**Comment by theophilusx** [comment]
If you think this package doesn't do the heavyh lifting, you should try
implementing your solution using just ssh2!

Note that your example does have a potential problem. Depending on
available resources, such as memory, CPU speed and number of files in
the source directory, you can get errors due to too many promises being
created at once. Also, there are situations where too many concurrent
promises will degrade performance rather than increase it.

Have a look at the sources for the donwloadDir() method in v10.0.3 to see how it
handles these issues. The solution is simple.

1. Create an array of [source, destination] pairs.
2. Partition the arry into groups of N pairs where N is the maximum
number of concurrent promises you want active at a time
3. For each group, do the promise.all() call, waiting until each is
complete before doing the next.

**Comment by blaasvaer** [comment]
Thanks for clearing that out.

In this case I'm not too concerned about performance (I know, this would have nothing to do with this package, I just needed a quick and dirty way of getting a few files from a server). I'm only monitoring three dirs on a remote server; one dir once a year for one file, another dir once a day, and a third once a minute. I'll only be getting one single file on each request if it's there, and if it's there I'll delete it ... I only check the dirs in the case that there would land more than one file, which should not happen ... just to be sure.

And one weakness (or strength?) using Promises.all() is that if one fails the whole thing fails ...

I'll check the downloadDir() …
