### ISSUE TITLE
Does this library supports mututal auth?

### ISSUE THREAD

**Issue by brsanthu** [theophilusx/ssh2-sftp-client#551]
As title says, I couldn't find any documentation if this library supports mutual auth. Can you uplease confirm?

**Comment by theophilusx** [comment]
If by 'mutual authentication' you mean some form of two way
authentication where the remote servber also authenticates the client,
the answer is no. This library implements the sftp protocol, which has
no support for mutual authentication as the (S)FTP protocol pre-dates
any concept of mutual authentication by some decades.

However, having said that, this library could possibly be part of a
mututal auth solution, either via standard auth mechanisms or via the
ssh2 modules support for custom authentication handlers.

All really depends on the remote SFTP server and how it
supports/implementes mutual auth. I'm not aware of any SFTP servers
which support mutual auth, but theoretically, it would be possible to
wrap this library in an auth layer which deals with this and just use
the lib to handle the ssh and ftp layers.

Personally, I think mutual auth is only warranted in very specialised
situations with known domain specific threats. In the
more general SFTP context, more often than not, it is adding little
additonal security and can easily increase risks due to the added
complexity it brings to administration and associated business
processes. My experience has been that simple and understood authentication
and authorisation always trumps complex and misunderstood processes.

**Comment by brsanthu** [comment]
@theophilusx thank you for the response. I did find a reference to privateKey in the doc, which is what I was looking for. Will explore fruther and update here.

**Comment by theophilusx** [comment]
BTW just in case you actually mean public key authentication rather than real mutual auth (where both sides verify their authenticity), this library supports all the authentication options of its dependency ssh2 lib, which includes public key authentication. Check out the ssh2 documentation for details (link in README).

**Comment by brsanthu** [comment]
@theophilusx Thank you, yes sorry I pharsed it wrong. I was looking for public key auth. I just tried that approach and it worked fine.

**Comment by theophilusx** [comment]
Santhosh ***@***.***> writes:

> @theophilusx thank you for the response. I did find a reference to privateKey in the doc, which is what I was looking for. Will
> explore fruther and update here.
>

OK, so what you actually want is public key authentication, which is not
mutual authentication as the only thing being authenticated with public
key auth is the client. People get confused and call this mutual auth
because the client's public key is held by the remote server and they
mistakenly think that means it is a mutual auth situation. Problem is,
the public key, by definition, is public and can be held by anyone (in
fact, public keys are often uploaded to public key servers). To be true
mutual auth, there needs to be a separate authentication check done on
the server. This sort of happens in the sense that after the first
connection, the client will record the ssh sig of the server and if it
changes in future connects, an error or warning (depending on config)
will be triggered. However, unless additional steps are taken, there is
no authentication of the server performed in the 1st connection.

One final warning. The current ssh version dropped support for some RSA
based key formats. Also, some encryption algorithms are slow. This means
that there are combinations of key formats and algorithms which can
either fail or which can result in frequent timeouts. The good news is
most of this is configurable, but the documentation is on the ssh2 site,
so make sure you check the docs for ssh2 linked in the ssh2-sftp-client
README.
