### ISSUE TITLE
Cannot get homedir file, even if it's true for the `exists()`

### ISSUE THREAD

**Issue by cangSDARM** [theophilusx/ssh2-sftp-client#557]
```ts
function sftp(ip, remote, format, target) {
  const targetPath = path.format({ dir: target.path, base: target.filename, ext: format });
  
  console.log(ip, remote, format, target);
  
  const dest = fs.createWriteStream(targetPath);
  const sftp = new SftpClient();
  await sftp.connect({
        host: ip,
        username: "root",
        password: "toor",
  });
  if (!sftp.exists(remote.path)) {
     return { message: "file don't exists!" };
  }
  
  const zipper = zlib.createGunzip();
  zipper.pipe(dest);
  sftp.get(remote.path, zipper);
  
  return await new Promise(res => {
     dest.on("end", res);
  });
}

sftp(
    ip,
    remote: { path: "~/test.txt" },
    format: "zip",
    target: {
      path: "C:\\Users\\Administrator\\Downloads",
      filename: "DownTest",
    },
);
```

it will throw an error:
![image](https://github.com/user-attachments/assets/483edf67-f597-4743-bb97-c887575fe03a)

**Comment by theophilusx** [comment]
This is most likely a bug in your code. What you are trying to do is a
very standard operation and if there was an issue there would be many
bug reports. Sorry, but I don't have time to debug your code. 

Start simple. Have your script just download the file without any on the
fly unzpping. Make sure that works first. BTW from the error message,
your test file does not look like a zipped file anywsay?

Also, that promise your adding is unnecessary and likely one source of
problem.

Note also, you probably should check the value returned by exists to
make sure it actually is a file and not something else, like a
directory.

You might find the example scripts in the examples directory of the repo
useful.

**Comment by cangSDARM** [comment]
Sorry, I'm not too familiar with linux and underlaying implementation.
I think it is caused by the different processing of file paths between ssh and sftp?
in ssh, ~/test.txt === /home/root/test, but in sftp ~/test.txt === /home/root/~/test.txt

![image](https://github.com/user-attachments/assets/0d311d53-843d-4197-bad3-fec2a60e977c)
If there is any misunderstanding, you can safely close this issue :)

**Comment by theophilusx** [comment]
It isn't really a Linux issue but rather more a misunderstanding
regarding the relationship between ssh and ftp. It can be a little
confusing because ftp is actually a very old protocol, which predates
ssh. The point to note is that sftp is in fact an ssh wrapper around the much
older ftp protocol. As such, how file paths work and how they relate to
the 'real' file system the sftp server is running on are defined by the
ftp protocol. You may find it instructive to read through an overview of
the ftp protocol, just so that your familiar with some of its quirks. 

To further confuse matters, 'modern' sftp really has two types of modes

1. Traditional ftp mode. In this mode, the sftp process is actually run
in a 'chroot' environment to make it more secure. When you log into the
server, you are not logging into the main server's file system, but
instead a chroot'd file system i.e. small, isolated 'fake' file system,
bit like a separate container. (originally, the main use for ftp was for
'anonymous' ftp and to provide a convenient way for people to upload
files to a server - everyone would upload the files into the same place,
but you could only see/get the files you uploaded)

2. ssh sftp mode where you are able to use the basic ftp protocol
operations i.e. get, put, ls, etc, but relative to a specific user's
login account. This is more common these days, but isn't strictly
speaking a real 'secure file transfer protocol (sftp) server.

So, WRT your question about paths, it all depends on the remote server
you are connecting to. If it is a dedicated sftp server, setup using the
sftp subsystem of ssh and it has been configured to use a separate
chroot filesystem, then all paths will be relative to whatever the
defined 'root' is. Even if it isn't using a chroot filesystem, it might
still use a root file path distinct from any specific user's login
directory i.e. /var/sftp or it might just be a server which allows sftp
access to normal ssh login accounts and the files will be relativbe to
/home/<user> (or whatever the 'default' path is for the OS).

In reality, you cannot assume what the root of the file path is. This is
partially why you have the 'realpath()' method.
