### ISSUE TITLE
File gets uploaded to sftp with status 552 

### ISSUE THREAD

**Issue by ajay-st** [theophilusx/ssh2-sftp-client#558]
Hi theophilusx,

We are uploading files to SFMC SFTP using below piece of code, (app is deployed in heroku).
Files are getting uploaded to sftp completely but with status of 552 (these status code were logged in salesforce sftp) due to this filedrop automations don't get triggered.

const Sftp_Client = require('ssh2-sftp-client')
      const sftp = new Sftp_Client()
      sftp.connect({  
        host: mcConnection.host,
        port: mcConnection.port,
        username: mcConnection.username,
        password: mcConnection.password,
        readyTimeout: 300000
      }).then(() => {
        console.time('sftpUpload')
        return sftp.put(data, remoteFileName,{
          readyTimeout: 300000
        })
      }).then(() => {
        console.timeEnd('sftpUpload')
        console.log(chalk.cyanBright("File uploaded to remote ftps successfully in" + remoteFileName))
        sftp.end()
        resolve()
      }).catch(err => {
        reject(err)
      })

on our side we are not getting any error, and the promise gets resolved successfully 

Versions
node: 12.22.12
npm: 6.14.16
ssh2-sftp-client: ^6.0.1

Note: We connected with the salesforce team and they responded as that the error is not due to the storage issues (which 552 error actually means) instead there is some issue related to how we were uploading files.

Thanks
Ajay

**Comment by theophilusx** [comment]
> Versions
> node: 12.22.12
> npm: 6.14.16
> ssh2-sftp-client: ^6.0.1
>

The above versions indicate your running an unsupported EOL version of
node and a very old unsupported version of ssh2-sftp-client. In fact,
the version you are running is using the pre v1 version of ssh2, which
has been completely re-written since that version.

Obviously your free to use outdated and unsupported versions, but I
cannot help with any issue diagnosis. Essentially, your on your own and
will have to resolve this issue yourself.

> Note: We connected with the salesforce team and they responded as that the error is not due to the storage issues (which 552
> error actually means) instead there is some issue related to how we were uploading files.
>

The ssh2-sftp-client module doe snot add any error codes with this value
and from memory, neither does ssh2. This code is what is being reported
by the remote sftp server. Basically, I think the salesforce team are
either wrong or are not giving you the whole story. Bottom line, it is
their server which is responding with that code, so they need to provide
more explanation as to why *their* software is not happy.

Having said that, there is a number of reasons that author of ssh2 did a
complete re-write and perhaps ssh2 isn't doing something exactly as the
salesforce software expects, but salesfoce would need to work with
you. Just sating it is an issue with your software is laziness on their
part. As the problem only occurs when using their sftp server, they
should work with you to get it resolved.
