### ISSUE TITLE
Seeing unhandled error and nodejs crash

### ISSUE THREAD

**Issue by devgk882** [theophilusx/ssh2-sftp-client#562]
Hi, I am using the latest ssh2-sftp-client library

And this is what I am trying to do
```
const Client = require('ssh2-sftp-client');

function connectServer(config) {
    return new Promise((resolve, reject) => {
        const sftp = new Client();
        sftp.on('error', (err) => {
            console.error('SFTP connection error:', err.message);
            reject(err);
        });

        sftp.connect(
            config
        )
        .then(() => resolve(sftp))
        .catch((error) => reject(error));
    });
}

// Usage Example

    const config = {
        host: 'example.com',
        port: 22,
        username: 'yourUsername',
        password: 'yourPassword',
    };

    try {
        const sftpConnection = await connectServer(config);
        console.log('Connected successfully');

        // Perform operations with the SFTP connection
       await sftpConnection.get('/remote/path', '/local/path');

        // Close the connection
        await sftpConnection.end();
        console.log('Connection closed');
    } catch (error) {
        console.error('Error during SFTP connection:', error.message);
    }
```

I got uncaught error handler err with error` readtimeout` with `CONNRESET` message `no response from server` i saw the log  SFTP connection error: which is from the `.on `event listener and Error during SFTP connection: from catch part and it crashed the nodejs application itself not sure what I should do here

And also before the code was like this:
```
const Client = require('ssh2-sftp-client');

function connectServer(config) {
    return new Promise((resolve, reject) => {
        const sftp = new Client();
      

        sftp.connect(
            config
        )
        .then(() => resolve(sftp))
        .catch((error) => reject(error));
    });
}

// Usage Example

    const config = {
        host: 'example.com',
        port: 22,
        username: 'yourUsername',
        password: 'yourPassword',
    };

    try {
        const sftpConnection = await connectServer(config);
        console.log('Connected successfully');

        // Perform operations with the SFTP connection
       await sftpConnection.get('/remote/path', '/local/path');

        // Close the connection
        await sftpConnection.end();
        console.log('Connection closed');
    } catch (error) {
        console.error('Error during SFTP connection:', error.message);
    }
```
and the ssh2-sftp-client version 9.x.x and during the connection reset i didnt saw crash and it just logged properly the error

**Comment by theophilusx** [comment]
Get rid of the promise and just use the API directly. There is no need
to use the promise or add an error listener, it is all taken care of
within the library itself. Just wrap the calls to the library within a
try/catch and call await sftp.connect() and await sftp.get() or await
sftp.put() or whatever you need and then await sftp.end(). Also look at
the README for the lib as this outlines how error events are handled and
what you need to do if the default setup does not meet your
requirements and the limitations wrt handling errors. Main thing is get rid of the call to new Promise as it is
unnecessary and is just causing unnecesary additional complexity.

FYI the reason you have and uncaught exception is because your error
handler runs outside the try/catch block. This is one of the major
challenges associated with wanting to wrap and event based API inside an
async promise based API. There use to be a section about the problems
with usinmg try/catch and event emitters in the node documentation - not
sure if it is still there as I've not checked the most recent docs.

**Comment by devgk882** [comment]
Thanks for the help

**Comment by devgk882** [comment]
I have another doubt @theophilusx it looks like for this below code 
```
const Client = require('ssh2-sftp-client');

function connectServer(config) {
    return new Promise((resolve, reject) => {
        const sftp = new Client();
      

        sftp.connect(
            config
        )
        .then(() => resolve(sftp))
        .catch((error) => reject(error));
    });
}

// Usage Example

    const config = {
        host: 'example.com',
        port: 22,
        username: 'yourUsername',
        password: 'yourPassword',
    };

    try {
        const sftpConnection = await connectServer(config);
        console.log('Connected successfully');

        // Perform operations with the SFTP connection
       await sftpConnection.get('/remote/path', '/local/path');

        // Close the connection
        await sftpConnection.end();
        console.log('Connection closed');
    } catch (error) {
        console.error('Error during SFTP connection:', error.message);
    }
```

I am still seeing the hanging issue which causes the partial file download issue is that issue expected because i am using the connect in promise? but this happens randomly.

**Comment by devgk882** [comment]
Also I tried your sample code 
https://github.com/theophilusx/ssh2-sftp-client/blob/master/examples/stream-get.js

If you add  keepaliveInterval: 20000, to the config it just throws the unhandled err node:events:495
      throw er; // Unhandled 'error' event Error: No response from server Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.20.4

**Comment by devgk882** [comment]
@theophilusx I tried your example code 

```
async function main() {
  let sftp = new Client();

  try {
   
   
    await sftp.connect(config);
    const ws = createWriteStream('./large-file.txt');
    ws.on('error', (err) => {
      console.error(`ws error: ${err.message}`);
    });
    ws.on('close', () => {
      console.log('ws close event raiswed');
    });
    ws.on('end', () => {
      console.log('ws end event raised');
    });
    await sftp.get('/upload/large-file.txt', ws);
    console.log('File downloaded');
  } catch (err) {
    console.error(`main: Error ${err.message}`);
  } finally {
    await sftp.end();
  }
}

main();
```
This also throws Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

when the file doesnt exist in server it just crash the node process

**Comment by devgk882** [comment]
I tried to switch from v11.0.0 to 9.1.0 and looks like unhandled error is gone now

**Comment by theophilusx** [comment]
devgk882 ***@***.***> writes:

> Also I tried your sample code
> https://github.com/theophilusx/ssh2-sftp-client/blob/master/examples/stream-get.js
>
> If you add keepaliveInterval: 20000, to the config it just throws the unhandled err node:events:495
> throw er; // Unhandled 'error' event Error: No response from server Emitted 'error' event on ReadStream instance at:
> at emitErrorNT (node:internal/streams/destroy:151:8)
> at emitErrorCloseNT (node:internal/streams/destroy:116:3)
> at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
>
> Node.js v18.20.4
>

Why are you setting such a huge keep alive interval? In fact, what issue
are you trying to fix by setting that interval so high? (In all the
times I've used the client, I've never needed that setting. I suspect it
is really more relevant when doing straight ssh rather than sftp)

From the information provided, the error appears to be generated by the
ssh2 module, which I have no control over. However, I also suspect that
the extreme size of the value you are setting is the issue. Make sure
you have read the ssh2 documentation on this setting and you understand
how it works. Setting it to 20s seems excessive and unlikely to work
correctly.

For the record, I just ran that script with the same keepaliveInterval
as you used and got no error. However, this was with node 23.1.0. Do you
also get the error without setting a keepaliveInterval or with other
values for keepaliveInterval?

**Comment by theophilusx** [comment]
Using the examples/stream-get.js scripts and providing a filename for a
file which does not exist on the server results in the following main:

❯ node --version
v23.1.0
    ...  examples  master  ?4 ~2  0.046s                                                                  tim / mole  4:31:00 PM
❯ node ./stream-get.js not-exist.txt not-exist.txt
main: Error get: No such file not-exist.txt
    ...  examples  master  ?5 ~2  0.465s                                                                  tim / mole  4:39:05 PM

I have never encountered the sort of low level ssh2 errors you are
encountering and suspect there is somethig amiss with your
environment. I would recommend deleting node_modules and doing a fresh
npm i.

**Comment by theophilusx** [comment]
Version 9.x has known issues and is unsupported. From memory, it also
uses a version of ssh2 which has known security vulnerabilities. It also
uses node library calls that are deprecated in node 20+. Use at your own
risk.

**Comment by devgk882** [comment]
I tried with v18.20.4 I didn't try with node v23.1.0.

**Comment by theophilusx** [comment]
I tested with node v18.20.5 and got the same results. I cannot reproduce
the errors you are seeing.

**Comment by devgk882** [comment]
ok thanks will close
